In [2]:
import pandas as pd

# headers = requests.utils.default_headers()
# headers.update({
#     'User-Agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0',
# })

# pmd_24_25_harvest_link = requests.get("https://news.maryland.gov/dnr/2025/02/14/maryland-hunters-harvest-84201-deer-for-2024-2025-season/", headers=headers)
# pmd_24_25_harvest_content = BeautifulSoup(pmd_24_25_harvest_link.text, 'html.parser')

#https://stackoverflow.com/questions/43440397/requests-using-beautiful-soup-gets-blocked

In [3]:
#2025-2026 Processed Harvest Data pt. 1
df_pmd_25_26 = pd.read_html("https://news.maryland.gov/dnr/2026/02/12/maryland-hunters-harvest-71649-deer-for-2025-2026-season/", storage_options={"User-Agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0"})
df_pmd_25_26 = df_pmd_25_26[0]
#type(df_pmd_25_26_one)
df_pmd_25_26.to_csv("df_pmd_25_26.csv")

In [4]:
#2025-2026 Processed Harvest Data pt. 2 - COMBINING HEADERS

header_row_two_2526 = df_pmd_25_26.iloc[1]
header_row_three_2526 = df_pmd_25_26.iloc[2]

#first row iloc[0] is title of the table 
#second row is antlered, anterless, and total
#third row is previous hunting season, the hunting season that just concluded, percentage change in harvest
#this third row is grouped under antlered, anterless, and total 

#because I want to combine second and third rows, start by create variables that extract values in second and third rows

#this for loop creates a list of strings, which are the combined header names, which will then be applied to the dataframe as names for the new column
new_columns = []
#need to create an empty list in order to store the combined column names (combining current names of rows 2 and 3)

#this for loop loops through both header rows at the same time, since the change needs to apply to both 
#zip() pairs values from the two rows column-by-column 
for header_two, header_three in zip(header_row_two_2526, header_row_three_2526):
    if pd.isna(header_two):
    #https://pandas.pydata.org/docs/reference/api/pandas.isna.html 
        #using isna because there's a cell above county (appears in third row) that's empty in the second row. 
        #this is saying if the upper header is missing (header_two) then just use the name in header_three, the lower header 
        combined_header = header_three 
    else:
        combined_header = f"{header_two}_{header_three}"
    new_columns.append(combined_header)

#replaces dataframe's current column names with new combined names stored in new_columns
df_pmd_25_26.columns = new_columns

#removes the header rows from the data 
#colon is python's slicing operator. It's keeping all rows starting at position 3 (which is position of the new column names)
#discarding rows 0-2, which were used for the old header names and the table title, which was repeated across all row cells 
df_pmd_25_26 = df_pmd_25_26.iloc[3:]
#https://www.datacamp.com/tutorial/loc-vs-iloc

df_pmd_25_26 = df_pmd_25_26.reset_index(drop=True)
#reset index after removing old header rows
#drop=True gets rid of old index, preventing it from taking up space as a meaningless column 

#SAVE TO CSV (PROCESSED DATA FOLDER)
df_pmd_25_26.to_csv("df_pmd_25_26.csv")

In [5]:
#---------2025-2026 MORE CLEANING: REPLACING * , DROPPING LAST ROW, CHANGING DATATYPES, DROPPING % COLUMNS---------#

#1. Replace asterisks with NaN
import numpy as np
df_pmd_25_26=df_pmd_25_26.replace(r'^\*$', np.nan, regex=True)
##https://stackoverflow.com/questions/45311262/replace-a-variable-number-of-asterisks-with-nan-in-a-dataframe 

#2. Drop last row, which just has "small sample size" text
df_pmd_25_26 = df_pmd_25_26[:-1]

#3. Change all datatypes (except those in county) to floats 
#found this on stack overflow to change datatypes of all but one column 

ignore = ['County']

#NEED TO SAVE THIS TO THE CURRENT DATAFRAME WITH DF=
df_pmd_25_26 = (df_pmd_25_26.set_index(ignore, append=True)
        .astype(float)
        .reset_index(ignore)
       )

#df_pmd_25_26.info()

#https://stackoverflow.com/questions/70893764/how-to-change-the-column-type-of-all-columns-except-the-first-in-pandas

#4.Drop percentage columns and then recalculate later 
df_pmd_25_26=df_pmd_25_26.drop(["Antlered_% Change", "Antlerless_% Change", "Total_% Change"], axis=1)

In [6]:
#---------2025-2026 MORE CLEANING: TEST TRIAL FOR COMBINING SUMS---------#
#5. Add whitetail and sika counts for each county manually, and then fill those sums into currently NaN county row 
caroline_whitetail = df_pmd_25_26.iloc[5]
caroline_sika = df_pmd_25_26.iloc[6] 

df_pmd_25_26.iloc[4, 1] = df_pmd_25_26.iloc[[5, 6], 1].sum()
df_pmd_25_26.iloc[4, 2] = df_pmd_25_26.iloc[[5,6], 2].sum()
df_pmd_25_26.iloc[4, 3] = df_pmd_25_26.iloc[[5, 6], 3].sum()
df_pmd_25_26.iloc[4, 4] = df_pmd_25_26.iloc[[5,6], 4].sum()
df_pmd_25_26.iloc[4, 5]= df_pmd_25_26.iloc[[5, 6], 5].sum()
df_pmd_25_26.iloc[4, 6] = df_pmd_25_26.iloc[[5,6], 6].sum()

df_pmd_25_26

,County,Antlered_2024-25,Antlered_2025-26,Antlerless_2024-25,Antlerless_2025-26,Total_2024-25,Total_2025-26
0,Allegany,1868.0,1739.0,1544.0,1185.0,3412.0,2924.0
1,Anne Arundel,898.0,579.0,1371.0,843.0,2269.0,1422.0
2,Baltimore,2109.0,2008.0,3130.0,2771.0,5239.0,4779.0
3,Calvert,658.0,524.0,1062.0,700.0,1720.0,1224.0
4,Caroline,880.0,916.0,2264.0,1624.0,3144.0,2540.0
5,whitetail,878.0,914.0,2262.0,1622.0,3140.0,2536.0
6,sika,2.0,2.0,2.0,2.0,4.0,4.0
7,Carroll,2368.0,2340.0,3620.0,2928.0,5988.0,5268.0
8,Cecil,1325.0,1320.0,2260.0,1839.0,3585.0,3159.0
9,Charles,1356.0,873.0,2012.0,1222.0,3368.0,2095.0
10,Dorchester,NaN,NaN,NaN,NaN,NaN,NaN
11,whitetail,637.0,698.0,1278.0,967.0,1915.0,1665.0
12,sika,1840.0,1639.0,2319.0,1800.0,4159.0,3439.0
13,Frederick,3012.0,2899.0,3857.0,3443.0,6869.0,6342.0
14,Garrett,3238.0,3058.0,2375.0,2088.0,5613.0,5146.0
15,Harford,1386.0,1286.0,2414.0,1876.0,3800.0,3162.0
16,Howard,852.0,837.0,1329.0,1268.0,2181.0,2105.0
17,Kent,1220.0,1202.0,2284.0,1816.0,3504.0,3018.0
18,Montgomery,1379.0,1229.0,2085.0,1840.0,3464.0,3069.0
19,Prince George’s,755.0,466.0,1051.0,532.0,1806.0,998.0
20,Queen Anne’s,1212.0,1271.0,2554.0,2084.0,3766.0,3355.0
21,St. Mary’s,1003.0,835.0,1470.0,1098.0,2473.0,1933.0
22,Somerset,NaN,NaN,NaN,NaN,NaN,NaN
23,whitetail,730.0,632.0,1373.0,1178.0,2103.0,1810.0
24,sika,26.0,25.0,11.0,11.0,37.0,36.0
25,Talbot,745.0,713.0,1557.0,1238.0,2302.0,1951.0
26,Washington,2477.0,2337.0,2589.0,2223.0,5066.0,4560.0
27,Wicomico,NaN,NaN,NaN,NaN,NaN,NaN
28,whitetail,945.0,949.0,1832.0,1525.0,2777.0,2474.0
29,sika,222.0,163.0,227.0,150.0,449.0,313.0
30,Worcester,NaN,NaN,NaN,NaN,NaN,NaN
31,whitetail,1097.0,1105.0,1962.0,1639.0,3059.0,2744.0
32,sika,53.0,45.0,80.0,73.0,133.0,118.0
33,Total,34291.0,31688.0,49910.0,39961.0,84201.0,71649.0

In [7]:
#---------2025-2026 MORE CLEANING: COMBINING ALL SUMS FOR WHITETAIL AND SIKA FOR ALL APPLICABLE COUNTIES---------#

#Dorchester
dorchester_whitetail = df_pmd_25_26.iloc[11]
dorchester_sika = df_pmd_25_26.iloc[12]

df_pmd_25_26.iloc[10, 1] = df_pmd_25_26.iloc[[11, 12], 1].sum()
df_pmd_25_26.iloc[10, 2] = df_pmd_25_26.iloc[[11,12], 2].sum()
df_pmd_25_26.iloc[10, 3] = df_pmd_25_26.iloc[[11, 12], 3].sum()
df_pmd_25_26.iloc[10, 4] = df_pmd_25_26.iloc[[11,12], 4].sum()
df_pmd_25_26.iloc[10, 5] = df_pmd_25_26.iloc[[11, 12], 5].sum()
df_pmd_25_26.iloc[10, 6] = df_pmd_25_26.iloc[[11,12], 6].sum()

#Somerset
somerset_whitetail = df_pmd_25_26.iloc[23]
somerset_sika = df_pmd_25_26.iloc[24]

df_pmd_25_26.iloc[22, 1] = df_pmd_25_26.iloc[[23, 24], 1].sum()
df_pmd_25_26.iloc[22, 2] = df_pmd_25_26.iloc[[23,24], 2].sum()
df_pmd_25_26.iloc[22, 3] = df_pmd_25_26.iloc[[23, 24], 3].sum()
df_pmd_25_26.iloc[22, 4] = df_pmd_25_26.iloc[[23,24], 4].sum()
df_pmd_25_26.iloc[22, 5] = df_pmd_25_26.iloc[[23, 24], 5].sum()
df_pmd_25_26.iloc[22, 6] = df_pmd_25_26.iloc[[23,24], 6].sum()

# #Wicomico
wicomico_whitetail = df_pmd_25_26.iloc[28]
wicomico_sika = df_pmd_25_26.iloc[29]

df_pmd_25_26.iloc[27, 1] = df_pmd_25_26.iloc[[28, 29], 1].sum()
df_pmd_25_26.iloc[27, 2] = df_pmd_25_26.iloc[[28,29], 2].sum()
df_pmd_25_26.iloc[27, 3] = df_pmd_25_26.iloc[[28, 29], 3].sum()
df_pmd_25_26.iloc[27, 4] = df_pmd_25_26.iloc[[28,29], 4].sum()
df_pmd_25_26.iloc[27, 5] = df_pmd_25_26.iloc[[28, 29], 5].sum()
df_pmd_25_26.iloc[27, 6] = df_pmd_25_26.iloc[[28,29], 6].sum()

# #Worcester
worcester_whitetail = df_pmd_25_26.iloc[31]
worcester_sika = df_pmd_25_26.iloc[32]

df_pmd_25_26.iloc[30, 1] = df_pmd_25_26.iloc[[31, 32], 1].sum()
df_pmd_25_26.iloc[30, 2] = df_pmd_25_26.iloc[[31,32], 2].sum()
df_pmd_25_26.iloc[30, 3] = df_pmd_25_26.iloc[[31, 32], 3].sum()
df_pmd_25_26.iloc[30, 4] = df_pmd_25_26.iloc[[31,32], 4].sum()
df_pmd_25_26.iloc[30, 5] = df_pmd_25_26.iloc[[31, 32], 5].sum()
df_pmd_25_26.iloc[30, 6] = df_pmd_25_26.iloc[[31,32], 6].sum()

df_pmd_25_26

,County,Antlered_2024-25,Antlered_2025-26,Antlerless_2024-25,Antlerless_2025-26,Total_2024-25,Total_2025-26
0,Allegany,1868.0,1739.0,1544.0,1185.0,3412.0,2924.0
1,Anne Arundel,898.0,579.0,1371.0,843.0,2269.0,1422.0
2,Baltimore,2109.0,2008.0,3130.0,2771.0,5239.0,4779.0
3,Calvert,658.0,524.0,1062.0,700.0,1720.0,1224.0
4,Caroline,880.0,916.0,2264.0,1624.0,3144.0,2540.0
5,whitetail,878.0,914.0,2262.0,1622.0,3140.0,2536.0
6,sika,2.0,2.0,2.0,2.0,4.0,4.0
7,Carroll,2368.0,2340.0,3620.0,2928.0,5988.0,5268.0
8,Cecil,1325.0,1320.0,2260.0,1839.0,3585.0,3159.0
9,Charles,1356.0,873.0,2012.0,1222.0,3368.0,2095.0
10,Dorchester,2477.0,2337.0,3597.0,2767.0,6074.0,5104.0
11,whitetail,637.0,698.0,1278.0,967.0,1915.0,1665.0
12,sika,1840.0,1639.0,2319.0,1800.0,4159.0,3439.0
13,Frederick,3012.0,2899.0,3857.0,3443.0,6869.0,6342.0
14,Garrett,3238.0,3058.0,2375.0,2088.0,5613.0,5146.0
15,Harford,1386.0,1286.0,2414.0,1876.0,3800.0,3162.0
16,Howard,852.0,837.0,1329.0,1268.0,2181.0,2105.0
17,Kent,1220.0,1202.0,2284.0,1816.0,3504.0,3018.0
18,Montgomery,1379.0,1229.0,2085.0,1840.0,3464.0,3069.0
19,Prince George’s,755.0,466.0,1051.0,532.0,1806.0,998.0
20,Queen Anne’s,1212.0,1271.0,2554.0,2084.0,3766.0,3355.0
21,St. Mary’s,1003.0,835.0,1470.0,1098.0,2473.0,1933.0
22,Somerset,756.0,657.0,1384.0,1189.0,2140.0,1846.0
23,whitetail,730.0,632.0,1373.0,1178.0,2103.0,1810.0
24,sika,26.0,25.0,11.0,11.0,37.0,36.0
25,Talbot,745.0,713.0,1557.0,1238.0,2302.0,1951.0
26,Washington,2477.0,2337.0,2589.0,2223.0,5066.0,4560.0
27,Wicomico,1167.0,1112.0,2059.0,1675.0,3226.0,2787.0
28,whitetail,945.0,949.0,1832.0,1525.0,2777.0,2474.0
29,sika,222.0,163.0,227.0,150.0,449.0,313.0
30,Worcester,1150.0,1150.0,2042.0,1712.0,3192.0,2862.0
31,whitetail,1097.0,1105.0,1962.0,1639.0,3059.0,2744.0
32,sika,53.0,45.0,80.0,73.0,133.0,118.0
33,Total,34291.0,31688.0,49910.0,39961.0,84201.0,71649.0

In [8]:
#---------2025-2026 FINAL CLEANING: DROPPING ROWS---------#
#Filter county values for "whitetail" and "sika" and drop those rows. Also drop "Total"
df_pmd_25_26=df_pmd_25_26[ df_pmd_25_26[ "County" ].str.contains( "whitetail|sika" )== False]
df_pmd_25_26 = df_pmd_25_26.reset_index(drop=True)
df_pmd_25_26.to_csv("df_pmd_25_26.csv")

In [9]:
#2024-2025 Processed Harvest Data pt. 1 

#https://pandas.pydata.org/docs/reference/api/pandas.read_html.html
#https://stackoverflow.com/questions/43590153/http-error-403-forbidden-when-reading-html .

df_pmd_24_25 = pd.read_html("https://news.maryland.gov/dnr/2025/02/14/maryland-hunters-harvest-84201-deer-for-2024-2025-season/", storage_options={"User-Agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0"})
#read_html initially returned list of dataframes, so turn the first item in the list into a df 
    #https://stackoverflow.com/questions/39710903/pd-read-html-imports-a-list-rather-than-a-dataframe
df_pmd_24_25 = df_pmd_24_25[0]
df_pmd_24_25.to_csv("df_pmd_24_25.csv")

In [10]:
#2024-2025 Processed Harvest Data pt. 2 = COMBINING HEADERS
header_row_one_2425 = df_pmd_24_25.iloc[1]
header_row_two_2425 = df_pmd_24_25.iloc[2]

new_columns = []

for header_one, header_two in zip(header_row_one_2425, header_row_two_2425):
    if pd.isna(header_one):
    #https://pandas.pydata.org/docs/reference/api/pandas.isna.html 
        combined_header = header_two 
    else:
        combined_header = f"{header_one}_{header_two}"
    new_columns.append(combined_header)
    
df_pmd_24_25.columns = new_columns 

df_pmd_24_25 = df_pmd_24_25.iloc[3:]
#https://www.datacamp.com/tutorial/loc-vs-iloc

df_pmd_24_25 = df_pmd_24_25.reset_index(drop=True)

df_pmd_24_25

,County,Antlered_2023-24,Antlered_2024-25,Antlered_% Change,Antlerless_2023-24,Antlerless_2024-25,Antlerless_% Change,Total_2023-24,Total_2024-25,Total_% Change
0,Allegany,1824,1868,2.4,1128,1544,36.9,2952,3412,15.6
1,Anne Arundel,750,898,19.7,974,1371,40.8,1724,2269,31.6
2,Baltimore,1899,2109,11.1,2651,3130,18.1,4550,5239,15.1
3,Calvert,584,658,12.7,817,1062,30.0,1401,1720,22.8
4,Caroline,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,whitetail,910,878,-3.5,1666,2262,35.8,2576,3140,21.9
6,sika,0,2,*,1,2,*,1,4,*
7,Carroll,2470,2368,-4.1,3259,3620,11.1,5729,5988,4.5
8,Cecil,1177,1325,12.6,1844,2260,22.6,3021,3585,18.7
9,Charles,1050,1356,29.1,1383,2012,45.5,2433,3368,38.4
10,Dorchester,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,whitetail,739,637,-13.8,1138,1278,12.3,1877,1915,2.0
12,sika,1678,1840,9.7,1965,2319,18.0,3643,4159,14.2
13,Frederick,2943,3012,2.3,3606,3857,7.0,6549,6869,4.9
14,Garrett,3152,3238,2.7,1956,2375,21.4,5108,5613,9.9
15,Harford,1147,1386,20.8,1923,2414,25.5,3070,3800,23.8
16,Howard,795,852,7.2,1259,1329,5.6,2054,2181,6.2
17,Kent,1200,1220,1.7,1673,2284,36.5,2873,3504,22.0
18,Montgomery,1316,1379,4.8,2046,2085,1.9,3362,3464,3.0
19,Prince George’s,649,755,16.3,778,1051,35.1,1427,1806,26.6
20,Queen Anne’s,1028,1212,17.9,1789,2554,42.8,2817,3766,33.7
21,St. Mary’s,869,1003,15.4,1116,1470,31.7,1985,2473,24.6
22,Somerset,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,whitetail,632,730,15.5,1058,1373,29.8,1690,2103,24.4
24,sika,18,26,44.4,15,11,-26.7,33,37,12.1
25,Talbot,719,745,3.6,1209,1557,28.8,1928,2302,19.4
26,Washington,2273,2477,9.0,2145,2589,20.7,4418,5066,14.7
27,Wicomico,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,whitetail,921,945,2.6,1494,1832,22.6,2415,2777,15.0
29,sika,167,222,32.9,161,227,41.0,328,449,36.9
30,Worcester,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,whitetail,978,1097,12.2,1599,1962,22.7,2577,3059,18.7
32,sika,49,53,8.2,52,80,53.8,101,133,31.7
33,Total,31937,34291,7.4,40705,49910,22.6,72642,84201,15.9
34,*Small sample size,*Small sample size,*Small sample size,*Small sample size,*Small sample size,*Small sample size,*Small sample size,*Small sample size,*Small sample size,*Small sample size

In [11]:
#---------2024-2025 MORE CLEANING: REPLACING * , DROPPING LAST ROW, CHANGING DATATYPES, DROPPING % COLUMNS---------#

#1. Replace asterisks with NaN
import numpy as np
df_pmd_24_25=df_pmd_24_25.replace(r'^\*$', np.nan, regex=True)
##https://stackoverflow.com/questions/45311262/replace-a-variable-number-of-asterisks-with-nan-in-a-dataframe 

#2. Drop last row, which just has "small sample size" text
df_pmd_24_25 = df_pmd_24_25.iloc[:-1]

#3. Change all datatypes (except those in county) to floats 
#found this on stack overflow to change datatypes of all but one column 

ignore = ['County']

#NEED TO SAVE THIS TO THE CURRENT DATAFRAME WITH DF=
df_pmd_24_25 = (df_pmd_24_25.set_index(ignore, append=True)
        .astype(float)
        .reset_index(ignore)
       )

# df_pmd_24_25.info()

#https://stackoverflow.com/questions/70893764/how-to-change-the-column-type-of-all-columns-except-the-first-in-pandas

#4.Drop percentage columns and then recalculate later 
df_pmd_24_25=df_pmd_24_25.drop(["Antlered_% Change", "Antlerless_% Change", "Total_% Change"], axis=1)
df_pmd_24_25

,County,Antlered_2023-24,Antlered_2024-25,Antlerless_2023-24,Antlerless_2024-25,Total_2023-24,Total_2024-25
0,Allegany,1824.0,1868.0,1128.0,1544.0,2952.0,3412.0
1,Anne Arundel,750.0,898.0,974.0,1371.0,1724.0,2269.0
2,Baltimore,1899.0,2109.0,2651.0,3130.0,4550.0,5239.0
3,Calvert,584.0,658.0,817.0,1062.0,1401.0,1720.0
4,Caroline,NaN,NaN,NaN,NaN,NaN,NaN
5,whitetail,910.0,878.0,1666.0,2262.0,2576.0,3140.0
6,sika,0.0,2.0,1.0,2.0,1.0,4.0
7,Carroll,2470.0,2368.0,3259.0,3620.0,5729.0,5988.0
8,Cecil,1177.0,1325.0,1844.0,2260.0,3021.0,3585.0
9,Charles,1050.0,1356.0,1383.0,2012.0,2433.0,3368.0
10,Dorchester,NaN,NaN,NaN,NaN,NaN,NaN
11,whitetail,739.0,637.0,1138.0,1278.0,1877.0,1915.0
12,sika,1678.0,1840.0,1965.0,2319.0,3643.0,4159.0
13,Frederick,2943.0,3012.0,3606.0,3857.0,6549.0,6869.0
14,Garrett,3152.0,3238.0,1956.0,2375.0,5108.0,5613.0
15,Harford,1147.0,1386.0,1923.0,2414.0,3070.0,3800.0
16,Howard,795.0,852.0,1259.0,1329.0,2054.0,2181.0
17,Kent,1200.0,1220.0,1673.0,2284.0,2873.0,3504.0
18,Montgomery,1316.0,1379.0,2046.0,2085.0,3362.0,3464.0
19,Prince George’s,649.0,755.0,778.0,1051.0,1427.0,1806.0
20,Queen Anne’s,1028.0,1212.0,1789.0,2554.0,2817.0,3766.0
21,St. Mary’s,869.0,1003.0,1116.0,1470.0,1985.0,2473.0
22,Somerset,NaN,NaN,NaN,NaN,NaN,NaN
23,whitetail,632.0,730.0,1058.0,1373.0,1690.0,2103.0
24,sika,18.0,26.0,15.0,11.0,33.0,37.0
25,Talbot,719.0,745.0,1209.0,1557.0,1928.0,2302.0
26,Washington,2273.0,2477.0,2145.0,2589.0,4418.0,5066.0
27,Wicomico,NaN,NaN,NaN,NaN,NaN,NaN
28,whitetail,921.0,945.0,1494.0,1832.0,2415.0,2777.0
29,sika,167.0,222.0,161.0,227.0,328.0,449.0
30,Worcester,NaN,NaN,NaN,NaN,NaN,NaN
31,whitetail,978.0,1097.0,1599.0,1962.0,2577.0,3059.0
32,sika,49.0,53.0,52.0,80.0,101.0,133.0
33,Total,31937.0,34291.0,40705.0,49910.0,72642.0,84201.0

In [12]:
#---------2024-2025 MORE CLEANING: TEST TRIAL FOR COMBINING SUMS---------#
#5. Add whitetail and sika counts for each county manually, and then fill those sums into currently NaN county row 

#CAROLINE COUNTY
df_pmd_24_25.iloc[4, 1] = df_pmd_24_25.iloc[[5, 6], 1].sum()
df_pmd_24_25.iloc[4, 2] = df_pmd_24_25.iloc[[5,6], 2].sum()
df_pmd_24_25.iloc[4, 3] = df_pmd_24_25.iloc[[5, 6], 3].sum()
df_pmd_24_25.iloc[4, 4] = df_pmd_24_25.iloc[[5,6], 4].sum()
df_pmd_24_25.iloc[4, 5]= df_pmd_24_25.iloc[[5, 6], 5].sum()
df_pmd_24_25.iloc[4, 6] = df_pmd_24_25.iloc[[5,6], 6].sum()

df_pmd_24_25

,County,Antlered_2023-24,Antlered_2024-25,Antlerless_2023-24,Antlerless_2024-25,Total_2023-24,Total_2024-25
0,Allegany,1824.0,1868.0,1128.0,1544.0,2952.0,3412.0
1,Anne Arundel,750.0,898.0,974.0,1371.0,1724.0,2269.0
2,Baltimore,1899.0,2109.0,2651.0,3130.0,4550.0,5239.0
3,Calvert,584.0,658.0,817.0,1062.0,1401.0,1720.0
4,Caroline,910.0,880.0,1667.0,2264.0,2577.0,3144.0
5,whitetail,910.0,878.0,1666.0,2262.0,2576.0,3140.0
6,sika,0.0,2.0,1.0,2.0,1.0,4.0
7,Carroll,2470.0,2368.0,3259.0,3620.0,5729.0,5988.0
8,Cecil,1177.0,1325.0,1844.0,2260.0,3021.0,3585.0
9,Charles,1050.0,1356.0,1383.0,2012.0,2433.0,3368.0
10,Dorchester,NaN,NaN,NaN,NaN,NaN,NaN
11,whitetail,739.0,637.0,1138.0,1278.0,1877.0,1915.0
12,sika,1678.0,1840.0,1965.0,2319.0,3643.0,4159.0
13,Frederick,2943.0,3012.0,3606.0,3857.0,6549.0,6869.0
14,Garrett,3152.0,3238.0,1956.0,2375.0,5108.0,5613.0
15,Harford,1147.0,1386.0,1923.0,2414.0,3070.0,3800.0
16,Howard,795.0,852.0,1259.0,1329.0,2054.0,2181.0
17,Kent,1200.0,1220.0,1673.0,2284.0,2873.0,3504.0
18,Montgomery,1316.0,1379.0,2046.0,2085.0,3362.0,3464.0
19,Prince George’s,649.0,755.0,778.0,1051.0,1427.0,1806.0
20,Queen Anne’s,1028.0,1212.0,1789.0,2554.0,2817.0,3766.0
21,St. Mary’s,869.0,1003.0,1116.0,1470.0,1985.0,2473.0
22,Somerset,NaN,NaN,NaN,NaN,NaN,NaN
23,whitetail,632.0,730.0,1058.0,1373.0,1690.0,2103.0
24,sika,18.0,26.0,15.0,11.0,33.0,37.0
25,Talbot,719.0,745.0,1209.0,1557.0,1928.0,2302.0
26,Washington,2273.0,2477.0,2145.0,2589.0,4418.0,5066.0
27,Wicomico,NaN,NaN,NaN,NaN,NaN,NaN
28,whitetail,921.0,945.0,1494.0,1832.0,2415.0,2777.0
29,sika,167.0,222.0,161.0,227.0,328.0,449.0
30,Worcester,NaN,NaN,NaN,NaN,NaN,NaN
31,whitetail,978.0,1097.0,1599.0,1962.0,2577.0,3059.0
32,sika,49.0,53.0,52.0,80.0,101.0,133.0
33,Total,31937.0,34291.0,40705.0,49910.0,72642.0,84201.0

In [13]:
#---------2024-2025 MORE CLEANING: COMBINING ALL SUMS FOR WHITETAIL AND SIKA FOR ALL APPLICABLE COUNTIES---------#

# #Dorchester
df_pmd_24_25.iloc[10, 1] = df_pmd_24_25.iloc[[11, 12], 1].sum()
df_pmd_24_25.iloc[10, 2] = df_pmd_24_25.iloc[[11,12], 2].sum()
df_pmd_24_25.iloc[10, 3] = df_pmd_24_25.iloc[[11, 12], 3].sum()
df_pmd_24_25.iloc[10, 4] = df_pmd_24_25.iloc[[11,12], 4].sum()
df_pmd_24_25.iloc[10, 5] = df_pmd_24_25.iloc[[11, 12], 5].sum()
df_pmd_24_25.iloc[10, 6] = df_pmd_24_25.iloc[[11,12], 6].sum()

# #Somerset
df_pmd_24_25.iloc[22, 1] = df_pmd_24_25.iloc[[23, 24], 1].sum()
df_pmd_24_25.iloc[22, 2] = df_pmd_24_25.iloc[[23,24], 2].sum()
df_pmd_24_25.iloc[22, 3] = df_pmd_24_25.iloc[[23, 24], 3].sum()
df_pmd_24_25.iloc[22, 4] = df_pmd_24_25.iloc[[23,24], 4].sum()
df_pmd_24_25.iloc[22, 5] = df_pmd_24_25.iloc[[23, 24], 5].sum()
df_pmd_24_25.iloc[22, 6] = df_pmd_24_25.iloc[[23,24], 6].sum()

# # #Wicomico
df_pmd_24_25.iloc[27, 1] = df_pmd_24_25.iloc[[28, 29], 1].sum()
df_pmd_24_25.iloc[27, 2] = df_pmd_24_25.iloc[[28,29], 2].sum()
df_pmd_24_25.iloc[27, 3] = df_pmd_24_25.iloc[[28, 29], 3].sum()
df_pmd_24_25.iloc[27, 4] = df_pmd_24_25.iloc[[28,29], 4].sum()
df_pmd_24_25.iloc[27, 5] = df_pmd_24_25.iloc[[28, 29], 5].sum()
df_pmd_24_25.iloc[27, 6] = df_pmd_24_25.iloc[[28,29], 6].sum()

# # #Worcester
df_pmd_24_25.iloc[30, 1] = df_pmd_24_25.iloc[[31, 32], 1].sum()
df_pmd_24_25.iloc[30, 2] = df_pmd_24_25.iloc[[31,32], 2].sum()
df_pmd_24_25.iloc[30, 3] = df_pmd_24_25.iloc[[31, 32], 3].sum()
df_pmd_24_25.iloc[30, 4] = df_pmd_24_25.iloc[[31,32], 4].sum()
df_pmd_24_25.iloc[30, 5] = df_pmd_24_25.iloc[[31, 32], 5].sum()
df_pmd_24_25.iloc[30, 6] = df_pmd_24_25.iloc[[31,32], 6].sum()

df_pmd_24_25

,County,Antlered_2023-24,Antlered_2024-25,Antlerless_2023-24,Antlerless_2024-25,Total_2023-24,Total_2024-25
0,Allegany,1824.0,1868.0,1128.0,1544.0,2952.0,3412.0
1,Anne Arundel,750.0,898.0,974.0,1371.0,1724.0,2269.0
2,Baltimore,1899.0,2109.0,2651.0,3130.0,4550.0,5239.0
3,Calvert,584.0,658.0,817.0,1062.0,1401.0,1720.0
4,Caroline,910.0,880.0,1667.0,2264.0,2577.0,3144.0
5,whitetail,910.0,878.0,1666.0,2262.0,2576.0,3140.0
6,sika,0.0,2.0,1.0,2.0,1.0,4.0
7,Carroll,2470.0,2368.0,3259.0,3620.0,5729.0,5988.0
8,Cecil,1177.0,1325.0,1844.0,2260.0,3021.0,3585.0
9,Charles,1050.0,1356.0,1383.0,2012.0,2433.0,3368.0
10,Dorchester,2417.0,2477.0,3103.0,3597.0,5520.0,6074.0
11,whitetail,739.0,637.0,1138.0,1278.0,1877.0,1915.0
12,sika,1678.0,1840.0,1965.0,2319.0,3643.0,4159.0
13,Frederick,2943.0,3012.0,3606.0,3857.0,6549.0,6869.0
14,Garrett,3152.0,3238.0,1956.0,2375.0,5108.0,5613.0
15,Harford,1147.0,1386.0,1923.0,2414.0,3070.0,3800.0
16,Howard,795.0,852.0,1259.0,1329.0,2054.0,2181.0
17,Kent,1200.0,1220.0,1673.0,2284.0,2873.0,3504.0
18,Montgomery,1316.0,1379.0,2046.0,2085.0,3362.0,3464.0
19,Prince George’s,649.0,755.0,778.0,1051.0,1427.0,1806.0
20,Queen Anne’s,1028.0,1212.0,1789.0,2554.0,2817.0,3766.0
21,St. Mary’s,869.0,1003.0,1116.0,1470.0,1985.0,2473.0
22,Somerset,650.0,756.0,1073.0,1384.0,1723.0,2140.0
23,whitetail,632.0,730.0,1058.0,1373.0,1690.0,2103.0
24,sika,18.0,26.0,15.0,11.0,33.0,37.0
25,Talbot,719.0,745.0,1209.0,1557.0,1928.0,2302.0
26,Washington,2273.0,2477.0,2145.0,2589.0,4418.0,5066.0
27,Wicomico,1088.0,1167.0,1655.0,2059.0,2743.0,3226.0
28,whitetail,921.0,945.0,1494.0,1832.0,2415.0,2777.0
29,sika,167.0,222.0,161.0,227.0,328.0,449.0
30,Worcester,1027.0,1150.0,1651.0,2042.0,2678.0,3192.0
31,whitetail,978.0,1097.0,1599.0,1962.0,2577.0,3059.0
32,sika,49.0,53.0,52.0,80.0,101.0,133.0
33,Total,31937.0,34291.0,40705.0,49910.0,72642.0,84201.0

In [14]:
#---------2024-2025 FINAL CLEANING: DROPPING ROWS---------#
#Filter county values for "whitetail" and "sika" and drop those rows
df_pmd_24_25=df_pmd_24_25[ df_pmd_24_25[ "County" ].str.contains( "whitetail|sika" )== False]
df_pmd_24_25 = df_pmd_24_25.reset_index(drop=True)
df_pmd_24_25.to_csv("df_pmd_24_25.csv")

In [15]:
#2023-2024 Processed Harvest Data Pt. 1

#PANDAS
df_pmd_23_24 = pd.read_html("https://news.maryland.gov/dnr/2024/02/13/maryland-hunters-harvest-72642-deer-for-2023-2024-season/", storage_options={"User-Agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0"})
df_pmd_23_24 = df_pmd_23_24[0]
#type(df_pmd_23_24)
df_pmd_23_24.to_csv("df_pmd_23_24.csv")

In [16]:
#2023-2024 Processed Harvest Data pt. 2 = COMBINING HEADERS

header_row_one_2324 = df_pmd_23_24.iloc[1]
header_row_two_2324 = df_pmd_23_24.iloc[2]

new_columns = []

for header_one, header_two in zip(header_row_one_2324, header_row_two_2324):
    if pd.isna(header_one):
    #https://pandas.pydata.org/docs/reference/api/pandas.isna.html 
        combined_header = header_two 
    else:
        combined_header = f"{header_one}_{header_two}"
    new_columns.append(combined_header)

#STORE NEW COMBINED HEADERS
df_pmd_23_24.columns = new_columns

#REPLACE OLD HEADERS WITH COMBINED
df_pmd_23_24 = df_pmd_23_24.iloc[3:]
df_pmd_23_24 = df_pmd_23_24.reset_index(drop=True)

#df_pmd_23_24

#SAVE TO CSV (PROCESSED DATA FOLDER)
df_pmd_23_24.to_csv("df_pmd_23_24.csv")
df_pmd_23_24

,County,Antlered_2023-24,Antlered_2022-23,Antlered_% Change,Antlerless_2023-24,Antlerless_2022-23,Antlerless_% Change,Total_2023-24,Total_2022-23,Total_% Change
0,Allegany,1824,1925,-5.2,1128,1474,-23.5,2952,3399,-13.2
1,Anne Arundel,750,800,-6.3,974,1083,-10.1,1724,1883,-8.4
2,Baltimore,1899,1856,2.3,2651,2990,-11.3,4550,4846,-6.1
3,Calvert,584,599,-2.5,817,879,-7.1,1401,1478,-5.2
4,Caroline,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,whitetail,910,933,-2.5,1666,1967,-15.3,2576,2900,-11.2
6,sika,0,0,*,1,1,*,1,1,*
7,Carroll,2470,2351,5.1,3259,3434,-5.1,5729,5785,-1
8,Cecil,1177,1230,-4.3,1844,2122,-13.1,3021,3352,-9.9
9,Charles,1050,1136,-7.6,1383,1439,-3.9,2433,2575,-5.5
10,Dorchester,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,whitetail,739,749,-1.3,1138,1318,-13.7,1877,2067,-9.2
12,sika,1678,1701,-1.4,1965,2017,-2.6,3643,3718,-2
13,Frederick,2943,2892,1.8,3606,4043,-10.8,6549,6935,-5.6
14,Garrett,3152,3113,1.3,1956,1876,4.3,5108,4989,2.4
15,Harford,1147,1233,-7,1923,2160,-11,3070,3393,-9.5
16,Howard,795,748,6.3,1259,1361,-7.5,2054,2109,-2.6
17,Kent,1200,1044,14.9,1673,2090,-20,2873,3134,-8.3
18,Montgomery,1316,1262,4.3,2046,2171,-5.8,3362,3433,-2.1
19,Prince George’s,649,715,-9.2,778,932,-16.5,1427,1647,-13.4
20,Queen Anne’s,1028,1083,-5.1,1789,1999,-10.5,2817,3082,-8.6
21,St. Mary’s,869,860,1,1116,1130,-1.2,1985,1990,-0.3
22,Somerset,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,whitetail,632,592,6.8,1058,1213,-12.8,1690,1805,-6.4
24,sika,18,25,*,15,12,*,33,37,*
25,Talbot,719,722,-0.4,1209,1284,-5.8,1928,2006,-3.9
26,Washington,2273,2221,2.3,2145,2379,-9.8,4418,4600,-4
27,Wicomico,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,whitetail,921,778,18.4,1494,1664,-10.2,2415,2442,-1.1
29,sika,167,142,*,161,147,*,328,289,*
30,Worcester,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,whitetail,978,840,16.4,1599,1864,-14.2,2577,2704,-4.7
32,sika,49,40,*,52,48,*,101,88,*
33,Total,31937,31590,1.1,40705,45097,-9.7,72642,76687,-5.3
34,*Small sample size,*Small sample size,*Small sample size,*Small sample size,*Small sample size,*Small sample size,*Small sample size,*Small sample size,*Small sample size,*Small sample size

In [17]:
#---------2023-2024 MORE CLEANING: REPLACING * , DROPPING LAST ROW, CHANGING DATATYPES, DROPPING % COLUMNS---------#

#1. Replace asterisks with NaN
import numpy as np
df_pmd_23_24=df_pmd_23_24.replace(r'^\*$', np.nan, regex=True)
##https://stackoverflow.com/questions/45311262/replace-a-variable-number-of-asterisks-with-nan-in-a-dataframe 

#2. Drop last row, which just has "small sample size" text
df_pmd_23_24 = df_pmd_23_24.iloc[:-1]

#3. Change all datatypes (except those in county) to floats 
#found this on stack overflow to change datatypes of all but one column 

ignore = ['County']

#NEED TO SAVE THIS TO THE CURRENT DATAFRAME WITH DF=
df_pmd_23_24 = (df_pmd_23_24.set_index(ignore, append=True)
        .astype(float)
        .reset_index(ignore)
       )

# df_pmd_23_24.info()

#https://stackoverflow.com/questions/70893764/how-to-change-the-column-type-of-all-columns-except-the-first-in-pandas

#4.Drop percentage columns and then recalculate later 
df_pmd_23_24=df_pmd_23_24.drop(["Antlered_% Change", "Antlerless_% Change", "Total_% Change"], axis=1)
df_pmd_23_24

,County,Antlered_2023-24,Antlered_2022-23,Antlerless_2023-24,Antlerless_2022-23,Total_2023-24,Total_2022-23
0,Allegany,1824.0,1925.0,1128.0,1474.0,2952.0,3399.0
1,Anne Arundel,750.0,800.0,974.0,1083.0,1724.0,1883.0
2,Baltimore,1899.0,1856.0,2651.0,2990.0,4550.0,4846.0
3,Calvert,584.0,599.0,817.0,879.0,1401.0,1478.0
4,Caroline,NaN,NaN,NaN,NaN,NaN,NaN
5,whitetail,910.0,933.0,1666.0,1967.0,2576.0,2900.0
6,sika,0.0,0.0,1.0,1.0,1.0,1.0
7,Carroll,2470.0,2351.0,3259.0,3434.0,5729.0,5785.0
8,Cecil,1177.0,1230.0,1844.0,2122.0,3021.0,3352.0
9,Charles,1050.0,1136.0,1383.0,1439.0,2433.0,2575.0
10,Dorchester,NaN,NaN,NaN,NaN,NaN,NaN
11,whitetail,739.0,749.0,1138.0,1318.0,1877.0,2067.0
12,sika,1678.0,1701.0,1965.0,2017.0,3643.0,3718.0
13,Frederick,2943.0,2892.0,3606.0,4043.0,6549.0,6935.0
14,Garrett,3152.0,3113.0,1956.0,1876.0,5108.0,4989.0
15,Harford,1147.0,1233.0,1923.0,2160.0,3070.0,3393.0
16,Howard,795.0,748.0,1259.0,1361.0,2054.0,2109.0
17,Kent,1200.0,1044.0,1673.0,2090.0,2873.0,3134.0
18,Montgomery,1316.0,1262.0,2046.0,2171.0,3362.0,3433.0
19,Prince George’s,649.0,715.0,778.0,932.0,1427.0,1647.0
20,Queen Anne’s,1028.0,1083.0,1789.0,1999.0,2817.0,3082.0
21,St. Mary’s,869.0,860.0,1116.0,1130.0,1985.0,1990.0
22,Somerset,NaN,NaN,NaN,NaN,NaN,NaN
23,whitetail,632.0,592.0,1058.0,1213.0,1690.0,1805.0
24,sika,18.0,25.0,15.0,12.0,33.0,37.0
25,Talbot,719.0,722.0,1209.0,1284.0,1928.0,2006.0
26,Washington,2273.0,2221.0,2145.0,2379.0,4418.0,4600.0
27,Wicomico,NaN,NaN,NaN,NaN,NaN,NaN
28,whitetail,921.0,778.0,1494.0,1664.0,2415.0,2442.0
29,sika,167.0,142.0,161.0,147.0,328.0,289.0
30,Worcester,NaN,NaN,NaN,NaN,NaN,NaN
31,whitetail,978.0,840.0,1599.0,1864.0,2577.0,2704.0
32,sika,49.0,40.0,52.0,48.0,101.0,88.0
33,Total,31937.0,31590.0,40705.0,45097.0,72642.0,76687.0

In [18]:
#---------2023-2024 MORE CLEANING: TEST TRIAL FOR COMBINING SUMS---------#
#5. Add whitetail and sika counts for each county manually, and then fill those sums into currently NaN county row 

#CAROLINE COUNTY
df_pmd_23_24.iloc[4, 1] = df_pmd_23_24.iloc[[5, 6], 1].sum()
df_pmd_23_24.iloc[4, 2] = df_pmd_23_24.iloc[[5,6], 2].sum()
df_pmd_23_24.iloc[4, 3] = df_pmd_23_24.iloc[[5, 6], 3].sum()
df_pmd_23_24.iloc[4, 4] = df_pmd_23_24.iloc[[5,6], 4].sum()
df_pmd_23_24.iloc[4, 5] = df_pmd_23_24.iloc[[5, 6], 5].sum()
df_pmd_23_24.iloc[4, 6] = df_pmd_23_24.iloc[[5,6], 6].sum()

df_pmd_23_24

,County,Antlered_2023-24,Antlered_2022-23,Antlerless_2023-24,Antlerless_2022-23,Total_2023-24,Total_2022-23
0,Allegany,1824.0,1925.0,1128.0,1474.0,2952.0,3399.0
1,Anne Arundel,750.0,800.0,974.0,1083.0,1724.0,1883.0
2,Baltimore,1899.0,1856.0,2651.0,2990.0,4550.0,4846.0
3,Calvert,584.0,599.0,817.0,879.0,1401.0,1478.0
4,Caroline,910.0,933.0,1667.0,1968.0,2577.0,2901.0
5,whitetail,910.0,933.0,1666.0,1967.0,2576.0,2900.0
6,sika,0.0,0.0,1.0,1.0,1.0,1.0
7,Carroll,2470.0,2351.0,3259.0,3434.0,5729.0,5785.0
8,Cecil,1177.0,1230.0,1844.0,2122.0,3021.0,3352.0
9,Charles,1050.0,1136.0,1383.0,1439.0,2433.0,2575.0
10,Dorchester,NaN,NaN,NaN,NaN,NaN,NaN
11,whitetail,739.0,749.0,1138.0,1318.0,1877.0,2067.0
12,sika,1678.0,1701.0,1965.0,2017.0,3643.0,3718.0
13,Frederick,2943.0,2892.0,3606.0,4043.0,6549.0,6935.0
14,Garrett,3152.0,3113.0,1956.0,1876.0,5108.0,4989.0
15,Harford,1147.0,1233.0,1923.0,2160.0,3070.0,3393.0
16,Howard,795.0,748.0,1259.0,1361.0,2054.0,2109.0
17,Kent,1200.0,1044.0,1673.0,2090.0,2873.0,3134.0
18,Montgomery,1316.0,1262.0,2046.0,2171.0,3362.0,3433.0
19,Prince George’s,649.0,715.0,778.0,932.0,1427.0,1647.0
20,Queen Anne’s,1028.0,1083.0,1789.0,1999.0,2817.0,3082.0
21,St. Mary’s,869.0,860.0,1116.0,1130.0,1985.0,1990.0
22,Somerset,NaN,NaN,NaN,NaN,NaN,NaN
23,whitetail,632.0,592.0,1058.0,1213.0,1690.0,1805.0
24,sika,18.0,25.0,15.0,12.0,33.0,37.0
25,Talbot,719.0,722.0,1209.0,1284.0,1928.0,2006.0
26,Washington,2273.0,2221.0,2145.0,2379.0,4418.0,4600.0
27,Wicomico,NaN,NaN,NaN,NaN,NaN,NaN
28,whitetail,921.0,778.0,1494.0,1664.0,2415.0,2442.0
29,sika,167.0,142.0,161.0,147.0,328.0,289.0
30,Worcester,NaN,NaN,NaN,NaN,NaN,NaN
31,whitetail,978.0,840.0,1599.0,1864.0,2577.0,2704.0
32,sika,49.0,40.0,52.0,48.0,101.0,88.0
33,Total,31937.0,31590.0,40705.0,45097.0,72642.0,76687.0

In [19]:
#---------2023-2024 MORE CLEANING: COMBINING ALL SUMS FOR WHITETAIL AND SIKA FOR ALL APPLICABLE COUNTIES---------#

# #Dorchester
df_pmd_23_24.iloc[10, 1] = df_pmd_23_24.iloc[[11, 12], 1].sum()
df_pmd_23_24.iloc[10, 2] = df_pmd_23_24.iloc[[11,12], 2].sum()
df_pmd_23_24.iloc[10, 3] = df_pmd_23_24.iloc[[11, 12], 3].sum()
df_pmd_23_24.iloc[10, 4] = df_pmd_23_24.iloc[[11,12], 4].sum()
df_pmd_23_24.iloc[10, 5] = df_pmd_23_24.iloc[[11, 12], 5].sum()
df_pmd_23_24.iloc[10, 6] = df_pmd_23_24.iloc[[11,12], 6].sum()

# #Somerset
df_pmd_23_24.iloc[22, 1] = df_pmd_23_24.iloc[[23, 24], 1].sum()
df_pmd_23_24.iloc[22, 2] = df_pmd_23_24.iloc[[23,24], 2].sum()
df_pmd_23_24.iloc[22, 3] = df_pmd_23_24.iloc[[23, 24], 3].sum()
df_pmd_23_24.iloc[22, 4] = df_pmd_23_24.iloc[[23,24], 4].sum()
df_pmd_23_24.iloc[22, 5] = df_pmd_23_24.iloc[[23, 24], 5].sum()
df_pmd_23_24.iloc[22, 6] = df_pmd_23_24.iloc[[23,24], 6].sum()

# # #Wicomico
df_pmd_23_24.iloc[27, 1] = df_pmd_23_24.iloc[[28, 29], 1].sum()
df_pmd_23_24.iloc[27, 2] = df_pmd_23_24.iloc[[28,29], 2].sum()
df_pmd_23_24.iloc[27, 3] = df_pmd_23_24.iloc[[28, 29], 3].sum()
df_pmd_23_24.iloc[27, 4] = df_pmd_23_24.iloc[[28,29], 4].sum()
df_pmd_23_24.iloc[27, 5] = df_pmd_23_24.iloc[[28, 29], 5].sum()
df_pmd_23_24.iloc[27, 6] = df_pmd_23_24.iloc[[28,29], 6].sum()

# # #Worcester
df_pmd_23_24.iloc[30, 1] = df_pmd_23_24.iloc[[31, 32], 1].sum()
df_pmd_23_24.iloc[30, 2] = df_pmd_23_24.iloc[[31,32], 2].sum()
df_pmd_23_24.iloc[30, 3] = df_pmd_23_24.iloc[[31, 32], 3].sum()
df_pmd_23_24.iloc[30, 4] = df_pmd_23_24.iloc[[31,32], 4].sum()
df_pmd_23_24.iloc[30, 5] = df_pmd_23_24.iloc[[31, 32], 5].sum()
df_pmd_23_24.iloc[30, 6] = df_pmd_23_24.iloc[[31,32], 6].sum()

df_pmd_23_24

,County,Antlered_2023-24,Antlered_2022-23,Antlerless_2023-24,Antlerless_2022-23,Total_2023-24,Total_2022-23
0,Allegany,1824.0,1925.0,1128.0,1474.0,2952.0,3399.0
1,Anne Arundel,750.0,800.0,974.0,1083.0,1724.0,1883.0
2,Baltimore,1899.0,1856.0,2651.0,2990.0,4550.0,4846.0
3,Calvert,584.0,599.0,817.0,879.0,1401.0,1478.0
4,Caroline,910.0,933.0,1667.0,1968.0,2577.0,2901.0
5,whitetail,910.0,933.0,1666.0,1967.0,2576.0,2900.0
6,sika,0.0,0.0,1.0,1.0,1.0,1.0
7,Carroll,2470.0,2351.0,3259.0,3434.0,5729.0,5785.0
8,Cecil,1177.0,1230.0,1844.0,2122.0,3021.0,3352.0
9,Charles,1050.0,1136.0,1383.0,1439.0,2433.0,2575.0
10,Dorchester,2417.0,2450.0,3103.0,3335.0,5520.0,5785.0
11,whitetail,739.0,749.0,1138.0,1318.0,1877.0,2067.0
12,sika,1678.0,1701.0,1965.0,2017.0,3643.0,3718.0
13,Frederick,2943.0,2892.0,3606.0,4043.0,6549.0,6935.0
14,Garrett,3152.0,3113.0,1956.0,1876.0,5108.0,4989.0
15,Harford,1147.0,1233.0,1923.0,2160.0,3070.0,3393.0
16,Howard,795.0,748.0,1259.0,1361.0,2054.0,2109.0
17,Kent,1200.0,1044.0,1673.0,2090.0,2873.0,3134.0
18,Montgomery,1316.0,1262.0,2046.0,2171.0,3362.0,3433.0
19,Prince George’s,649.0,715.0,778.0,932.0,1427.0,1647.0
20,Queen Anne’s,1028.0,1083.0,1789.0,1999.0,2817.0,3082.0
21,St. Mary’s,869.0,860.0,1116.0,1130.0,1985.0,1990.0
22,Somerset,650.0,617.0,1073.0,1225.0,1723.0,1842.0
23,whitetail,632.0,592.0,1058.0,1213.0,1690.0,1805.0
24,sika,18.0,25.0,15.0,12.0,33.0,37.0
25,Talbot,719.0,722.0,1209.0,1284.0,1928.0,2006.0
26,Washington,2273.0,2221.0,2145.0,2379.0,4418.0,4600.0
27,Wicomico,1088.0,920.0,1655.0,1811.0,2743.0,2731.0
28,whitetail,921.0,778.0,1494.0,1664.0,2415.0,2442.0
29,sika,167.0,142.0,161.0,147.0,328.0,289.0
30,Worcester,1027.0,880.0,1651.0,1912.0,2678.0,2792.0
31,whitetail,978.0,840.0,1599.0,1864.0,2577.0,2704.0
32,sika,49.0,40.0,52.0,48.0,101.0,88.0
33,Total,31937.0,31590.0,40705.0,45097.0,72642.0,76687.0

In [20]:
#---------2023-2024 FINAL CLEANING: DROPPING ROWS---------#
#Filter county values for "whitetail" and "sika" and drop those rows
df_pmd_23_24=df_pmd_23_24[ df_pmd_23_24[ "County" ].str.contains( "whitetail|sika" )== False]
df_pmd_23_24 = df_pmd_23_24.reset_index(drop=True)
df_pmd_23_24.to_csv("df_pmd_23_24.csv")

In [21]:
#2022-2023 Processed Harvest Data Pt. 1

#PANDAS
df_pmd_22_23 = pd.read_html("https://news.maryland.gov/dnr/2023/02/16/maryland-hunters-harvest-76687-deer-for-2022-2023-season/", storage_options={"User-Agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0"})
df_pmd_22_23 = df_pmd_22_23[0]
#type(df_pmd_22_23)
df_pmd_22_23.to_csv("df_pmd_22_23_one.csv")

In [22]:
#2022-2023 Processed Harvest Data pt. 2 = COMBINING HEADERS

header_row_one_2223 = df_pmd_22_23.iloc[1]
header_row_two_2223 = df_pmd_22_23.iloc[2]

new_columns = []

for header_one, header_two in zip(header_row_one_2223, header_row_two_2223):
    if pd.isna(header_one):
    #https://pandas.pydata.org/docs/reference/api/pandas.isna.html 
        combined_header = header_two 
    else:
        combined_header = f"{header_one}_{header_two}"
    new_columns.append(combined_header)

#STORE NEW COMBINED HEADERS
df_pmd_22_23.columns = new_columns

#REPLACE OLD HEADERS WITH COMBINED
df_pmd_22_23 = df_pmd_22_23.iloc[3:]
df_pmd_22_23 = df_pmd_22_23.reset_index(drop=True)

#SAVE TO CSV (PROCESSED DATA FOLDER)
df_pmd_22_23.to_csv("df_pmd_22_23.csv")

In [23]:
#---------2022-2023 MORE CLEANING: REPLACING * , DROPPING LAST ROW, CHANGING DATATYPES, DROPPING % COLUMNS---------#

#FOR NULL COUNTY ROWS 

#1. Replace asterisks with NaN
import numpy as np
df_pmd_22_23=df_pmd_22_23.replace(r'^\*$', np.nan, regex=True)
##https://stackoverflow.com/questions/45311262/replace-a-variable-number-of-asterisks-with-nan-in-a-dataframe 

#2. Drop last row, which just has "small sample size" text
df_pmd_22_23 = df_pmd_22_23.iloc[:-1]

#3. NEW STEP 
df_pmd_22_23.iloc[4, 1:10] = np.nan
df_pmd_22_23.iloc[10, 1:10] = np.nan
df_pmd_22_23.iloc[22, 1:10] = np.nan
df_pmd_22_23.iloc[27, 1:10] = np.nan
df_pmd_22_23.iloc[30, 1:10] = np.nan

#4. Change all datatypes (except those in county) to floats 
#found this on stack overflow to change datatypes of all but one column 

ignore = ['County']

#NEED TO SAVE THIS TO THE CURRENT DATAFRAME WITH DF=
df_pmd_22_23 = (df_pmd_22_23.set_index(ignore, append=True)
        .astype(float)
        .reset_index(ignore)
       )

# df_pmd_24_25.info()

#https://stackoverflow.com/questions/70893764/how-to-change-the-column-type-of-all-columns-except-the-first-in-pandas

#4.Drop percentage columns and then recalculate later 
df_pmd_22_23=df_pmd_22_23.drop(["Antlered_% Change", "Antlerless_% Change", "Total_% Change"], axis=1)
df_pmd_22_23

,County,Antlered_2021-22,Antlered_2022-23,Antlerless_2021-22,Antlerless_2022-23,Total_2021-22,Total_2022-23
0,Allegany,1837.0,1925.0,1177.0,1474.0,3014.0,3399.0
1,Anne Arundel,755.0,800.0,1082.0,1083.0,1837.0,1883.0
2,Baltimore,1680.0,1856.0,2821.0,2990.0,4501.0,4846.0
3,Calvert,551.0,599.0,787.0,879.0,1338.0,1478.0
4,Caroline,NaN,NaN,NaN,NaN,NaN,NaN
5,whitetail,908.0,933.0,1576.0,1967.0,2484.0,2900.0
6,sika,0.0,0.0,0.0,1.0,0.0,1.0
7,Carroll,2058.0,2351.0,3013.0,3434.0,5071.0,5785.0
8,Cecil,1197.0,1230.0,1996.0,2122.0,3193.0,3352.0
9,Charles,873.0,1136.0,1082.0,1439.0,1955.0,2575.0
10,Dorchester,NaN,NaN,NaN,NaN,NaN,NaN
11,whitetail,732.0,749.0,1235.0,1318.0,1967.0,2067.0
12,sika,1350.0,1701.0,1703.0,2017.0,3053.0,3718.0
13,Frederick,2674.0,2892.0,3414.0,4043.0,6088.0,6935.0
14,Garrett,2443.0,3113.0,1480.0,1876.0,3923.0,4989.0
15,Harford,1139.0,1233.0,2023.0,2160.0,3162.0,3393.0
16,Howard,775.0,748.0,1244.0,1361.0,2019.0,2109.0
17,Kent,1077.0,1044.0,1954.0,2090.0,3031.0,3134.0
18,Montgomery,1280.0,1262.0,2026.0,2171.0,3306.0,3433.0
19,Prince George’s,702.0,715.0,928.0,932.0,1630.0,1647.0
20,Queen Anne’s,1074.0,1083.0,1884.0,1999.0,2958.0,3082.0
21,St. Mary’s,657.0,860.0,820.0,1130.0,1477.0,1990.0
22,Somerset,NaN,NaN,NaN,NaN,NaN,NaN
23,whitetail,734.0,592.0,1337.0,1213.0,2071.0,1805.0
24,sika,17.0,25.0,8.0,12.0,25.0,37.0
25,Talbot,694.0,722.0,1363.0,1284.0,2057.0,2006.0
26,Washington,1889.0,2221.0,2010.0,2379.0,3899.0,4600.0
27,Wicomico,NaN,NaN,NaN,NaN,NaN,NaN
28,whitetail,1046.0,778.0,1991.0,1664.0,3037.0,2442.0
29,sika,140.0,142.0,112.0,147.0,252.0,289.0
30,Worcester,NaN,NaN,NaN,NaN,NaN,NaN
31,whitetail,1172.0,840.0,2255.0,1864.0,3427.0,2704.0
32,sika,34.0,40.0,36.0,48.0,70.0,88.0
33,Total,29488.0,31590.0,41357.0,45097.0,70845.0,76687.0

In [24]:
#---------2022-2023 MORE CLEANING: TEST TRIAL FOR COMBINING SUMS---------#
#5. Add whitetail and sika counts for each county manually, and then fill those sums into currently NaN county row 

#CAROLINE COUNTY
df_pmd_22_23.iloc[4, 1] = df_pmd_22_23.iloc[[5, 6], 1].sum()
df_pmd_22_23.iloc[4, 2] = df_pmd_22_23.iloc[[5,6], 2].sum()
df_pmd_22_23.iloc[4, 3] = df_pmd_22_23.iloc[[5, 6], 3].sum()
df_pmd_22_23.iloc[4, 4] = df_pmd_22_23.iloc[[5,6], 4].sum()
df_pmd_22_23.iloc[4, 5] = df_pmd_22_23.iloc[[5, 6], 5].sum()
df_pmd_22_23.iloc[4, 6] = df_pmd_22_23.iloc[[5,6], 6].sum()

df_pmd_22_23

,County,Antlered_2021-22,Antlered_2022-23,Antlerless_2021-22,Antlerless_2022-23,Total_2021-22,Total_2022-23
0,Allegany,1837.0,1925.0,1177.0,1474.0,3014.0,3399.0
1,Anne Arundel,755.0,800.0,1082.0,1083.0,1837.0,1883.0
2,Baltimore,1680.0,1856.0,2821.0,2990.0,4501.0,4846.0
3,Calvert,551.0,599.0,787.0,879.0,1338.0,1478.0
4,Caroline,908.0,933.0,1576.0,1968.0,2484.0,2901.0
5,whitetail,908.0,933.0,1576.0,1967.0,2484.0,2900.0
6,sika,0.0,0.0,0.0,1.0,0.0,1.0
7,Carroll,2058.0,2351.0,3013.0,3434.0,5071.0,5785.0
8,Cecil,1197.0,1230.0,1996.0,2122.0,3193.0,3352.0
9,Charles,873.0,1136.0,1082.0,1439.0,1955.0,2575.0
10,Dorchester,NaN,NaN,NaN,NaN,NaN,NaN
11,whitetail,732.0,749.0,1235.0,1318.0,1967.0,2067.0
12,sika,1350.0,1701.0,1703.0,2017.0,3053.0,3718.0
13,Frederick,2674.0,2892.0,3414.0,4043.0,6088.0,6935.0
14,Garrett,2443.0,3113.0,1480.0,1876.0,3923.0,4989.0
15,Harford,1139.0,1233.0,2023.0,2160.0,3162.0,3393.0
16,Howard,775.0,748.0,1244.0,1361.0,2019.0,2109.0
17,Kent,1077.0,1044.0,1954.0,2090.0,3031.0,3134.0
18,Montgomery,1280.0,1262.0,2026.0,2171.0,3306.0,3433.0
19,Prince George’s,702.0,715.0,928.0,932.0,1630.0,1647.0
20,Queen Anne’s,1074.0,1083.0,1884.0,1999.0,2958.0,3082.0
21,St. Mary’s,657.0,860.0,820.0,1130.0,1477.0,1990.0
22,Somerset,NaN,NaN,NaN,NaN,NaN,NaN
23,whitetail,734.0,592.0,1337.0,1213.0,2071.0,1805.0
24,sika,17.0,25.0,8.0,12.0,25.0,37.0
25,Talbot,694.0,722.0,1363.0,1284.0,2057.0,2006.0
26,Washington,1889.0,2221.0,2010.0,2379.0,3899.0,4600.0
27,Wicomico,NaN,NaN,NaN,NaN,NaN,NaN
28,whitetail,1046.0,778.0,1991.0,1664.0,3037.0,2442.0
29,sika,140.0,142.0,112.0,147.0,252.0,289.0
30,Worcester,NaN,NaN,NaN,NaN,NaN,NaN
31,whitetail,1172.0,840.0,2255.0,1864.0,3427.0,2704.0
32,sika,34.0,40.0,36.0,48.0,70.0,88.0
33,Total,29488.0,31590.0,41357.0,45097.0,70845.0,76687.0

In [25]:
#---------2023-2024 MORE CLEANING: COMBINING ALL SUMS FOR WHITETAIL AND SIKA FOR ALL APPLICABLE COUNTIES---------#

# Dorchester
df_pmd_22_23.iloc[10, 1] = df_pmd_22_23.iloc[[11, 12], 1].sum()
df_pmd_22_23.iloc[10, 2] = df_pmd_22_23.iloc[[11,12], 2].sum()
df_pmd_22_23.iloc[10, 3] = df_pmd_22_23.iloc[[11, 12], 3].sum()
df_pmd_22_23.iloc[10, 4] = df_pmd_22_23.iloc[[11,12], 4].sum()
df_pmd_22_23.iloc[10, 5] = df_pmd_22_23.iloc[[11, 12], 5].sum()
df_pmd_22_23.iloc[10, 6] = df_pmd_22_23.iloc[[11,12], 6].sum()

# Somerset
df_pmd_22_23.iloc[22, 1] = df_pmd_22_23.iloc[[23, 24], 1].sum()
df_pmd_22_23.iloc[22, 2] = df_pmd_22_23.iloc[[23,24], 2].sum()
df_pmd_22_23.iloc[22, 3] = df_pmd_22_23.iloc[[23, 24], 3].sum()
df_pmd_22_23.iloc[22, 4] = df_pmd_22_23.iloc[[23,24], 4].sum()
df_pmd_22_23.iloc[22, 5] = df_pmd_22_23.iloc[[23, 24], 5].sum()
df_pmd_22_23.iloc[22, 6] = df_pmd_22_23.iloc[[23,24], 6].sum()

# Wicomico
df_pmd_22_23.iloc[27, 1] = df_pmd_22_23.iloc[[28, 29], 1].sum()
df_pmd_22_23.iloc[27, 2] = df_pmd_22_23.iloc[[28,29], 2].sum()
df_pmd_22_23.iloc[27, 3] = df_pmd_22_23.iloc[[28, 29], 3].sum()
df_pmd_22_23.iloc[27, 4] = df_pmd_22_23.iloc[[28,29], 4].sum()
df_pmd_22_23.iloc[27, 5] = df_pmd_22_23.iloc[[28, 29], 5].sum()
df_pmd_22_23.iloc[27, 6] = df_pmd_22_23.iloc[[28,29], 6].sum()

# Worcester
df_pmd_22_23.iloc[30, 1] = df_pmd_22_23.iloc[[31, 32], 1].sum()
df_pmd_22_23.iloc[30, 2] = df_pmd_22_23.iloc[[31,32], 2].sum()
df_pmd_22_23.iloc[30, 3] = df_pmd_22_23.iloc[[31, 32], 3].sum()
df_pmd_22_23.iloc[30, 4] = df_pmd_22_23.iloc[[31,32], 4].sum()
df_pmd_22_23.iloc[30, 5] = df_pmd_22_23.iloc[[31, 32], 5].sum()
df_pmd_22_23.iloc[30, 6] = df_pmd_22_23.iloc[[31,32], 6].sum()

df_pmd_22_23

,County,Antlered_2021-22,Antlered_2022-23,Antlerless_2021-22,Antlerless_2022-23,Total_2021-22,Total_2022-23
0,Allegany,1837.0,1925.0,1177.0,1474.0,3014.0,3399.0
1,Anne Arundel,755.0,800.0,1082.0,1083.0,1837.0,1883.0
2,Baltimore,1680.0,1856.0,2821.0,2990.0,4501.0,4846.0
3,Calvert,551.0,599.0,787.0,879.0,1338.0,1478.0
4,Caroline,908.0,933.0,1576.0,1968.0,2484.0,2901.0
5,whitetail,908.0,933.0,1576.0,1967.0,2484.0,2900.0
6,sika,0.0,0.0,0.0,1.0,0.0,1.0
7,Carroll,2058.0,2351.0,3013.0,3434.0,5071.0,5785.0
8,Cecil,1197.0,1230.0,1996.0,2122.0,3193.0,3352.0
9,Charles,873.0,1136.0,1082.0,1439.0,1955.0,2575.0
10,Dorchester,2082.0,2450.0,2938.0,3335.0,5020.0,5785.0
11,whitetail,732.0,749.0,1235.0,1318.0,1967.0,2067.0
12,sika,1350.0,1701.0,1703.0,2017.0,3053.0,3718.0
13,Frederick,2674.0,2892.0,3414.0,4043.0,6088.0,6935.0
14,Garrett,2443.0,3113.0,1480.0,1876.0,3923.0,4989.0
15,Harford,1139.0,1233.0,2023.0,2160.0,3162.0,3393.0
16,Howard,775.0,748.0,1244.0,1361.0,2019.0,2109.0
17,Kent,1077.0,1044.0,1954.0,2090.0,3031.0,3134.0
18,Montgomery,1280.0,1262.0,2026.0,2171.0,3306.0,3433.0
19,Prince George’s,702.0,715.0,928.0,932.0,1630.0,1647.0
20,Queen Anne’s,1074.0,1083.0,1884.0,1999.0,2958.0,3082.0
21,St. Mary’s,657.0,860.0,820.0,1130.0,1477.0,1990.0
22,Somerset,751.0,617.0,1345.0,1225.0,2096.0,1842.0
23,whitetail,734.0,592.0,1337.0,1213.0,2071.0,1805.0
24,sika,17.0,25.0,8.0,12.0,25.0,37.0
25,Talbot,694.0,722.0,1363.0,1284.0,2057.0,2006.0
26,Washington,1889.0,2221.0,2010.0,2379.0,3899.0,4600.0
27,Wicomico,1186.0,920.0,2103.0,1811.0,3289.0,2731.0
28,whitetail,1046.0,778.0,1991.0,1664.0,3037.0,2442.0
29,sika,140.0,142.0,112.0,147.0,252.0,289.0
30,Worcester,1206.0,880.0,2291.0,1912.0,3497.0,2792.0
31,whitetail,1172.0,840.0,2255.0,1864.0,3427.0,2704.0
32,sika,34.0,40.0,36.0,48.0,70.0,88.0
33,Total,29488.0,31590.0,41357.0,45097.0,70845.0,76687.0

In [26]:
#---------2022-2023 FINAL CLEANING: DROPPING ROWS---------#
#Filter county values for "whitetail" and "sika" and drop those rows
df_pmd_22_23=df_pmd_22_23[ df_pmd_22_23[ "County" ].str.contains( "whitetail|sika" )== False]
df_pmd_22_23 = df_pmd_22_23.reset_index(drop=True)
df_pmd_22_23.to_csv("df_pmd_22_23.csv")

In [27]:
#2021-2022 Processed Harvest Data Pt. 1

#PANDAS
df_pmd_21_22 = pd.read_html("https://news.maryland.gov/dnr/2022/02/10/maryland-hunters-report-taking-70845-deer-in-2021-2022-season/", storage_options={"User-Agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0"})
df_pmd_21_22 = df_pmd_21_22[0]
#type(df_pmd_21_22)
df_pmd_21_22.to_csv("df_pmd_21_22.csv")

In [28]:
#2021-2022 Processed Harvest Data pt. 2 = COMBINING HEADERS

header_row_one_2122 = df_pmd_21_22.iloc[1]
header_row_two_2122 = df_pmd_21_22.iloc[2]

new_columns = []

for header_one, header_two in zip(header_row_one_2122, header_row_two_2122):
    if pd.isna(header_one):
    #https://pandas.pydata.org/docs/reference/api/pandas.isna.html 
        combined_header = header_two 
    else:
        combined_header = f"{header_one}_{header_two}"
    new_columns.append(combined_header)

#STORE NEW COMBINED HEADERS
df_pmd_21_22.columns = new_columns

#REPLACE OLD HEADERS WITH COMBINED
df_pmd_21_22 = df_pmd_21_22.iloc[3:]
df_pmd_21_22 = df_pmd_21_22.reset_index(drop=True)

df_pmd_21_22

,County,Antlered_2021-22,Antlered_2020-21,Antlered_% Change,Antlerless_2021-22,Antlerless_2020-21,Antlerless_% Change,Total_2021-22,Total_2020-21,Total_% Change
0,Allegany,1837,1921,-4.4,1177,1379,-14.6,3014,3300,-8.7
1,Anne Arundel,755,642,17.6,1082,1277,-15.3,1837,1919,-4.3
2,Baltimore,1680,1781,-5.7,2821,3575,-21.1,4501,5356,-16.0
3,Calvert,551,468,17.7,787,916,-14.1,1338,1384,-3.3
4,Caroline,Caroline,Caroline,Caroline,Caroline,Caroline,Caroline,Caroline,Caroline,Caroline
5,whitetail,908,884,2.7,1576,1894,-16.8,2484,2778,-10.6
6,sika,0,0,*,0,2,*,0,2,*
7,Carroll,2058,2196,-6.3,3013,4006,-24.8,5071,6202,-18.2
8,Cecil,1197,1227,-2.4,1996,2530,-21.1,3193,3757,-15.0
9,Charles,873,1074,-18.7,1082,1557,-30.5,1955,2631,-25.7
10,Dorchester,Dorchester,Dorchester,Dorchester,Dorchester,Dorchester,Dorchester,Dorchester,Dorchester,Dorchester
11,whitetail,732,728,0.5,1235,1327,-6.9,1967,2055,-4.3
12,sika,1350,1337,1.0,1703,1749,-2.6,3.053,3086,-1.1
13,Frederick,2674,2854,-6.3,3414,4488,-23.9,6088,7342,-17.1
14,Garrett,2443,2873,-15.0,1480,2031,-27.1,3923,4904,-20.0
15,Harford,1139,1209,-5.8,2023,2371,-14.7,3162,3580,-11.7
16,Howard,775,807,-4.0,1244,1576,-21.1,2019,2383,-15.3
17,Kent,1077,1044,3.2,1954,2108,-7.3,3031,3152,-3.8
18,Montgomery,1280,1363,-6.1,2026,2741,-26.1,3306,4104,-194
19,Prince George’s,702,662,6.0,928,963,-3.6,1630,1625,0.3
20,Queen Anne’s,1074,1006,6.8,1884,2321,-18.8,2958,3327,-11.1
21,St. Mary’s,657,792,-17.0,820,1264,-35.1,1477,2056,-28.2
22,Somerset,Somerset,Somerset,Somerset,Somerset,Somerset,Somerset,Somerset,Somerset,Somerset
23,whitetail,734,691,6.2,1337,1566,-14.6,2071,2257,-8.2
24,sika,17,7,*,8,9,*,25,16,*
25,Talbot,694,697,-0.4,1363,1576,-13.5,2057,2273,-9.5
26,Washington,1889,2096,-9.9,2010,2616,-23.2,3899,4712,-17.3
27,Wicomico,Wicomico,Wicomico,Wicomico,Wicomico,Wicomico,Wicomico,Wicomico,Wicomico,Wicomico
28,whitetail,1046,1063,-1.6,1991,2289,-13.0,3037,3352,-9.4
29,sika,140,118,*,112,116,*,252,234,*
30,Worcester,Worcester,Worcester,Worcester,Worcester,Worcester,Worcester,Worcester,Worcester,Worcester
31,whitetail,1172,1164,0.7,2255,2662,-15.3,3427,3826,-10.4
32,sika,34,38,*,36,78,*,70,116,*
33,Total,29488,30742,-4.1,41357,50987,-18.9,70845,81729,-13.3
34,*Small sample size,*Small sample size,*Small sample size,*Small sample size,*Small sample size,*Small sample size,*Small sample size,*Small sample size,*Small sample size,*Small sample size

In [29]:
#---------2021-2022 MORE CLEANING: REPLACING * , DROPPING LAST ROW, CHANGING DATATYPES, DROPPING % COLUMNS---------#

#FOR FILLED COUNTY ROWS 

#1. Replace asterisks with NaN
import numpy as np
df_pmd_21_22=df_pmd_21_22.replace(r'^\*$', np.nan, regex=True)
##https://stackoverflow.com/questions/45311262/replace-a-variable-number-of-asterisks-with-nan-in-a-dataframe 

#2. Drop last row, which just has "small sample size" text
df_pmd_21_22 = df_pmd_21_22.iloc[:-1]

#3. NEW STEP 
df_pmd_21_22.iloc[4, 1:10] = np.nan
df_pmd_21_22.iloc[10, 1:10] = np.nan
df_pmd_21_22.iloc[22, 1:10] = np.nan
df_pmd_21_22.iloc[27, 1:10] = np.nan
df_pmd_21_22.iloc[30, 1:10] = np.nan

#4. Change all datatypes (except those in county) to floats 
#found this on stack overflow to change datatypes of all but one column 

ignore = ['County']

# #NEED TO SAVE THIS TO THE CURRENT DATAFRAME WITH DF=
df_pmd_21_22 = (df_pmd_21_22.set_index(ignore, append=True)
        .astype(float)
        .reset_index(ignore)
       )

# # df_pmd_21_22.info()

# #https://stackoverflow.com/questions/70893764/how-to-change-the-column-type-of-all-columns-except-the-first-in-pandas

# #4.Drop percentage columns and then recalculate later 
df_pmd_21_22=df_pmd_21_22.drop(["Antlered_% Change", "Antlerless_% Change", "Total_% Change"], axis=1)
df_pmd_21_22

,County,Antlered_2021-22,Antlered_2020-21,Antlerless_2021-22,Antlerless_2020-21,Total_2021-22,Total_2020-21
0,Allegany,1837.0,1921.0,1177.0,1379.0,3014.000,3300.0
1,Anne Arundel,755.0,642.0,1082.0,1277.0,1837.000,1919.0
2,Baltimore,1680.0,1781.0,2821.0,3575.0,4501.000,5356.0
3,Calvert,551.0,468.0,787.0,916.0,1338.000,1384.0
4,Caroline,NaN,NaN,NaN,NaN,NaN,NaN
5,whitetail,908.0,884.0,1576.0,1894.0,2484.000,2778.0
6,sika,0.0,0.0,0.0,2.0,0.000,2.0
7,Carroll,2058.0,2196.0,3013.0,4006.0,5071.000,6202.0
8,Cecil,1197.0,1227.0,1996.0,2530.0,3193.000,3757.0
9,Charles,873.0,1074.0,1082.0,1557.0,1955.000,2631.0
10,Dorchester,NaN,NaN,NaN,NaN,NaN,NaN
11,whitetail,732.0,728.0,1235.0,1327.0,1967.000,2055.0
12,sika,1350.0,1337.0,1703.0,1749.0,3.053,3086.0
13,Frederick,2674.0,2854.0,3414.0,4488.0,6088.000,7342.0
14,Garrett,2443.0,2873.0,1480.0,2031.0,3923.000,4904.0
15,Harford,1139.0,1209.0,2023.0,2371.0,3162.000,3580.0
16,Howard,775.0,807.0,1244.0,1576.0,2019.000,2383.0
17,Kent,1077.0,1044.0,1954.0,2108.0,3031.000,3152.0
18,Montgomery,1280.0,1363.0,2026.0,2741.0,3306.000,4104.0
19,Prince George’s,702.0,662.0,928.0,963.0,1630.000,1625.0
20,Queen Anne’s,1074.0,1006.0,1884.0,2321.0,2958.000,3327.0
21,St. Mary’s,657.0,792.0,820.0,1264.0,1477.000,2056.0
22,Somerset,NaN,NaN,NaN,NaN,NaN,NaN
23,whitetail,734.0,691.0,1337.0,1566.0,2071.000,2257.0
24,sika,17.0,7.0,8.0,9.0,25.000,16.0
25,Talbot,694.0,697.0,1363.0,1576.0,2057.000,2273.0
26,Washington,1889.0,2096.0,2010.0,2616.0,3899.000,4712.0
27,Wicomico,NaN,NaN,NaN,NaN,NaN,NaN
28,whitetail,1046.0,1063.0,1991.0,2289.0,3037.000,3352.0
29,sika,140.0,118.0,112.0,116.0,252.000,234.0
30,Worcester,NaN,NaN,NaN,NaN,NaN,NaN
31,whitetail,1172.0,1164.0,2255.0,2662.0,3427.000,3826.0
32,sika,34.0,38.0,36.0,78.0,70.000,116.0
33,Total,29488.0,30742.0,41357.0,50987.0,70845.000,81729.0

In [30]:
#---------2021-2022 MORE CLEANING: TEST TRIAL FOR COMBINING SUMS---------#
#5. Add whitetail and sika counts for each county manually, and then fill those sums into currently NaN county row 

#CAROLINE COUNTY
df_pmd_21_22.iloc[4, 1] = df_pmd_21_22.iloc[[5, 6], 1].sum()
df_pmd_21_22.iloc[4, 2] = df_pmd_21_22.iloc[[5,6], 2].sum()
df_pmd_21_22.iloc[4, 3] = df_pmd_21_22.iloc[[5, 6], 3].sum()
df_pmd_21_22.iloc[4, 4] = df_pmd_21_22.iloc[[5,6], 4].sum()
df_pmd_21_22.iloc[4, 5] = df_pmd_21_22.iloc[[5, 6], 5].sum()
df_pmd_21_22.iloc[4, 6] = df_pmd_21_22.iloc[[5,6], 6].sum()

df_pmd_21_22

,County,Antlered_2021-22,Antlered_2020-21,Antlerless_2021-22,Antlerless_2020-21,Total_2021-22,Total_2020-21
0,Allegany,1837.0,1921.0,1177.0,1379.0,3014.000,3300.0
1,Anne Arundel,755.0,642.0,1082.0,1277.0,1837.000,1919.0
2,Baltimore,1680.0,1781.0,2821.0,3575.0,4501.000,5356.0
3,Calvert,551.0,468.0,787.0,916.0,1338.000,1384.0
4,Caroline,908.0,884.0,1576.0,1896.0,2484.000,2780.0
5,whitetail,908.0,884.0,1576.0,1894.0,2484.000,2778.0
6,sika,0.0,0.0,0.0,2.0,0.000,2.0
7,Carroll,2058.0,2196.0,3013.0,4006.0,5071.000,6202.0
8,Cecil,1197.0,1227.0,1996.0,2530.0,3193.000,3757.0
9,Charles,873.0,1074.0,1082.0,1557.0,1955.000,2631.0
10,Dorchester,NaN,NaN,NaN,NaN,NaN,NaN
11,whitetail,732.0,728.0,1235.0,1327.0,1967.000,2055.0
12,sika,1350.0,1337.0,1703.0,1749.0,3.053,3086.0
13,Frederick,2674.0,2854.0,3414.0,4488.0,6088.000,7342.0
14,Garrett,2443.0,2873.0,1480.0,2031.0,3923.000,4904.0
15,Harford,1139.0,1209.0,2023.0,2371.0,3162.000,3580.0
16,Howard,775.0,807.0,1244.0,1576.0,2019.000,2383.0
17,Kent,1077.0,1044.0,1954.0,2108.0,3031.000,3152.0
18,Montgomery,1280.0,1363.0,2026.0,2741.0,3306.000,4104.0
19,Prince George’s,702.0,662.0,928.0,963.0,1630.000,1625.0
20,Queen Anne’s,1074.0,1006.0,1884.0,2321.0,2958.000,3327.0
21,St. Mary’s,657.0,792.0,820.0,1264.0,1477.000,2056.0
22,Somerset,NaN,NaN,NaN,NaN,NaN,NaN
23,whitetail,734.0,691.0,1337.0,1566.0,2071.000,2257.0
24,sika,17.0,7.0,8.0,9.0,25.000,16.0
25,Talbot,694.0,697.0,1363.0,1576.0,2057.000,2273.0
26,Washington,1889.0,2096.0,2010.0,2616.0,3899.000,4712.0
27,Wicomico,NaN,NaN,NaN,NaN,NaN,NaN
28,whitetail,1046.0,1063.0,1991.0,2289.0,3037.000,3352.0
29,sika,140.0,118.0,112.0,116.0,252.000,234.0
30,Worcester,NaN,NaN,NaN,NaN,NaN,NaN
31,whitetail,1172.0,1164.0,2255.0,2662.0,3427.000,3826.0
32,sika,34.0,38.0,36.0,78.0,70.000,116.0
33,Total,29488.0,30742.0,41357.0,50987.0,70845.000,81729.0

In [31]:
#---------2021-2022 MORE CLEANING: COMBINING ALL SUMS FOR WHITETAIL AND SIKA FOR ALL APPLICABLE COUNTIES---------#

# #Dorchester
df_pmd_21_22.iloc[10, 1] = df_pmd_21_22.iloc[[11, 12], 1].sum()
df_pmd_21_22.iloc[10, 2] = df_pmd_21_22.iloc[[11,12], 2].sum()
df_pmd_21_22.iloc[10, 3] = df_pmd_21_22.iloc[[11, 12], 3].sum()
df_pmd_21_22.iloc[10, 4] = df_pmd_21_22.iloc[[11,12], 4].sum()
df_pmd_21_22.iloc[10, 5] = df_pmd_21_22.iloc[[11, 12], 5].sum()
df_pmd_21_22.iloc[10, 6] = df_pmd_21_22.iloc[[11,12], 6].sum()

# #Somerset
df_pmd_21_22.iloc[22, 1] = df_pmd_21_22.iloc[[23, 24], 1].sum()
df_pmd_21_22.iloc[22, 2] = df_pmd_21_22.iloc[[23,24], 2].sum()
df_pmd_21_22.iloc[22, 3] = df_pmd_21_22.iloc[[23, 24], 3].sum()
df_pmd_21_22.iloc[22, 4] = df_pmd_21_22.iloc[[23,24], 4].sum()
df_pmd_21_22.iloc[22, 5] = df_pmd_21_22.iloc[[23, 24], 5].sum()
df_pmd_21_22.iloc[22, 6] = df_pmd_21_22.iloc[[23,24], 6].sum()

# # #Wicomico
df_pmd_21_22.iloc[27, 1] = df_pmd_21_22.iloc[[28, 29], 1].sum()
df_pmd_21_22.iloc[27, 2] = df_pmd_21_22.iloc[[28,29], 2].sum()
df_pmd_21_22.iloc[27, 3] = df_pmd_21_22.iloc[[28, 29], 3].sum()
df_pmd_21_22.iloc[27, 4] = df_pmd_21_22.iloc[[28,29], 4].sum()
df_pmd_21_22.iloc[27, 5] = df_pmd_21_22.iloc[[28, 29], 5].sum()
df_pmd_21_22.iloc[27, 6] = df_pmd_21_22.iloc[[28,29], 6].sum()

# # #Worcester
df_pmd_21_22.iloc[30, 1] = df_pmd_21_22.iloc[[31, 32], 1].sum()
df_pmd_21_22.iloc[30, 2] = df_pmd_21_22.iloc[[31,32], 2].sum()
df_pmd_21_22.iloc[30, 3] = df_pmd_21_22.iloc[[31, 32], 3].sum()
df_pmd_21_22.iloc[30, 4] = df_pmd_21_22.iloc[[31,32], 4].sum()
df_pmd_21_22.iloc[30, 5] = df_pmd_21_22.iloc[[31, 32], 5].sum()
df_pmd_21_22.iloc[30, 6] = df_pmd_21_22.iloc[[31,32], 6].sum()

df_pmd_21_22

,County,Antlered_2021-22,Antlered_2020-21,Antlerless_2021-22,Antlerless_2020-21,Total_2021-22,Total_2020-21
0,Allegany,1837.0,1921.0,1177.0,1379.0,3014.000,3300.0
1,Anne Arundel,755.0,642.0,1082.0,1277.0,1837.000,1919.0
2,Baltimore,1680.0,1781.0,2821.0,3575.0,4501.000,5356.0
3,Calvert,551.0,468.0,787.0,916.0,1338.000,1384.0
4,Caroline,908.0,884.0,1576.0,1896.0,2484.000,2780.0
5,whitetail,908.0,884.0,1576.0,1894.0,2484.000,2778.0
6,sika,0.0,0.0,0.0,2.0,0.000,2.0
7,Carroll,2058.0,2196.0,3013.0,4006.0,5071.000,6202.0
8,Cecil,1197.0,1227.0,1996.0,2530.0,3193.000,3757.0
9,Charles,873.0,1074.0,1082.0,1557.0,1955.000,2631.0
10,Dorchester,2082.0,2065.0,2938.0,3076.0,1970.053,5141.0
11,whitetail,732.0,728.0,1235.0,1327.0,1967.000,2055.0
12,sika,1350.0,1337.0,1703.0,1749.0,3.053,3086.0
13,Frederick,2674.0,2854.0,3414.0,4488.0,6088.000,7342.0
14,Garrett,2443.0,2873.0,1480.0,2031.0,3923.000,4904.0
15,Harford,1139.0,1209.0,2023.0,2371.0,3162.000,3580.0
16,Howard,775.0,807.0,1244.0,1576.0,2019.000,2383.0
17,Kent,1077.0,1044.0,1954.0,2108.0,3031.000,3152.0
18,Montgomery,1280.0,1363.0,2026.0,2741.0,3306.000,4104.0
19,Prince George’s,702.0,662.0,928.0,963.0,1630.000,1625.0
20,Queen Anne’s,1074.0,1006.0,1884.0,2321.0,2958.000,3327.0
21,St. Mary’s,657.0,792.0,820.0,1264.0,1477.000,2056.0
22,Somerset,751.0,698.0,1345.0,1575.0,2096.000,2273.0
23,whitetail,734.0,691.0,1337.0,1566.0,2071.000,2257.0
24,sika,17.0,7.0,8.0,9.0,25.000,16.0
25,Talbot,694.0,697.0,1363.0,1576.0,2057.000,2273.0
26,Washington,1889.0,2096.0,2010.0,2616.0,3899.000,4712.0
27,Wicomico,1186.0,1181.0,2103.0,2405.0,3289.000,3586.0
28,whitetail,1046.0,1063.0,1991.0,2289.0,3037.000,3352.0
29,sika,140.0,118.0,112.0,116.0,252.000,234.0
30,Worcester,1206.0,1202.0,2291.0,2740.0,3497.000,3942.0
31,whitetail,1172.0,1164.0,2255.0,2662.0,3427.000,3826.0
32,sika,34.0,38.0,36.0,78.0,70.000,116.0
33,Total,29488.0,30742.0,41357.0,50987.0,70845.000,81729.0

In [32]:
#---------2021-2022 FINAL CLEANING: DROPPING ROWS---------#
#Filter county values for "whitetail" and "sika" and drop those rows
df_pmd_21_22=df_pmd_21_22[ df_pmd_21_22[ "County" ].str.contains( "whitetail|sika" )== False]
df_pmd_22_23 = df_pmd_22_23.reset_index(drop=True)
df_pmd_21_22.to_csv("df_pmd_21_22.csv")

In [33]:
#2020-2021 Processed Harvest Data Pt. 1

#PANDAS
df_pmd_20_21 = pd.read_html("https://news.maryland.gov/dnr/2021/02/16/maryland-hunters-harvest-81000-deer-during-2020-2021-season/", storage_options={"User-Agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0"})
df_pmd_20_21 = df_pmd_20_21[0]
#type(df_pmd_20_21)
df_pmd_20_21.to_csv("df_pmd_20_21.csv")

In [34]:
#2020-2021 Processed Harvest Data pt. 2 = COMBINING HEADERS

#COMBINE HEADERS 
header_row_one_2021 = df_pmd_20_21.iloc[1]
header_row_two_2021 = df_pmd_20_21.iloc[2]

new_columns = []

for header_one, header_two in zip(header_row_one_2021, header_row_two_2021):
    if pd.isna(header_one):
    #https://pandas.pydata.org/docs/reference/api/pandas.isna.html 
        combined_header = header_two 
    else:
        combined_header = f"{header_one}_{header_two}"
    new_columns.append(combined_header)

#STORE NEW COMBINED HEADERS
df_pmd_20_21.columns = new_columns

#REPLACE OLD HEADERS WITH COMBINED
df_pmd_20_21 = df_pmd_20_21.iloc[3:]
df_pmd_20_21 = df_pmd_20_21.reset_index(drop=True)

df_pmd_20_21

,County,Antlered_2019-20,Antlered_2020-21,Antlered_% Change,Antlerless_2019-20,Antlerless_2020-21,Antlerless_% Change,Total_2019-20,Total_2020-21,Total_% Change
0,Allegany,1667,1921,15.2,1179,1379,17.0,2846,3300,16.0
1,Anne Arundel,966,642,-33.5,1653,1277,-22.7,2619,1919,-26.7
2,Baltimore,1774,1781,0.4,3195,3575,11.9,4969,5356,7.8
3,Calvert,639,468,-26.8,1025,916,-10.6,1664,1384,-16.8
4,Caroline,Caroline,Caroline,Caroline,Caroline,Caroline,Caroline,Caroline,Caroline,Caroline
5,whitetail,785,884,12.6,1797,1894,5.4,2582,2778,7.6
6,sika,0,0,*,1,2,*,1,2,*
7,Carroll,2016,2196,8.9,3537,4006,13.3,5553,6202,11.7
8,Cecil,1226,1227,0.1,2468,2530,2.5,3694,3757,1.7
9,Charles,1349,1074,-20.4,1868,1557,-16.6,3217,2631,-18.2
10,Dorchester,Dorchester,Dorchester,Dorchester,Dorchester,Dorchester,Dorchester,Dorchester,Dorchester,Dorchester
11,whitetail,748,728,-2.7,1203,1327,10.3,1951,2055,5.3
12,sika,1405,1337,-4.8,1711,1749,2.2,3116,3086,-1.0
13,Frederick,2543,2854,12.2,3815,4488,17.6,6358,7342,15.5
14,Garrett,2733,2873,5.1,1874,2031,8.4,4607,4904,6.4
15,Harford,1224,1209,-1.2,2353,2371,0.8,3577,3580,0.1
16,Howard,798,807,1.1,1470,1576,7.2,2268,2383,5.1
17,Kent,1162,1044,-10.2,2020,2108,4.4,3182,3152,-0.9
18,Montgomery,1367,1363,-0.3,2588,2741,5.9,3955,4104,3.8
19,Prince George’s,885,662,-25.2,1311,963,-26.5,2196,1625,-26.0
20,Queen Anne’s,1127,1006,-10.7,2248,2321,3.2,3375,3327,-1.4
21,St. Mary’s,962,792,-17.7,1547,1264,-18.3,2509,2056,-18.1
22,Somerset,Somerset,Somerset,Somerset,Somerset,Somerset,Somerset,Somerset,Somerset,Somerset
23,whitetail,649,691,6.5,1488,1566,5.2,2137,2257,5.6
24,sika,8,7,*,8,8,*,16,16,*
25,Talbot,717,697,-2.8,1637,1576,-3.7,2354,2273,-3.4
26,Washington,1846,2096,13.5,2195,2616,19.2,4041,4712,16.6
27,Wicomico,Wicomico,Wicomico,Wicomico,Wicomico,Wicomico,Wicomico,Wicomico,Wicomico,Wicomico
28,whitetail,975,1063,9.0,1963,2289,16.6,2938,3352,14.1
29,sika,83,118,*,114,116,*,197,234,*
30,Worcester,Worcester,Worcester,Worcester,Worcester,Worcester,Worcester,Worcester,Worcester,Worcester
31,whitetail,1075,1164,8.3,2343,2662,13.6,3418,3826,11.9
32,sika,55,38,*,61,78,*,116,116,*
33,Total,30785,30742,-0.1,48672,50987,4.8,79457,81729,2.9
34,*Small sample size,*Small sample size,*Small sample size,*Small sample size,*Small sample size,*Small sample size,*Small sample size,*Small sample size,*Small sample size,*Small sample size

In [35]:
#---------2020-2021 MORE CLEANING: REPLACING * , DROPPING LAST ROW, CHANGING DATATYPES, DROPPING % COLUMNS---------#

#FOR FILLED COUNTY ROWS 

#1. Replace asterisks with NaN
import numpy as np
df_pmd_20_21=df_pmd_20_21.replace(r'^\*$', np.nan, regex=True)
##https://stackoverflow.com/questions/45311262/replace-a-variable-number-of-asterisks-with-nan-in-a-dataframe 

#2. Drop last row, which just has "small sample size" text
df_pmd_20_21 = df_pmd_20_21.iloc[:-1]

#3. NEW STEP 
df_pmd_20_21.iloc[4, 1:10] = np.nan
df_pmd_20_21.iloc[10, 1:10] = np.nan
df_pmd_20_21.iloc[22, 1:10] = np.nan
df_pmd_20_21.iloc[27, 1:10] = np.nan
df_pmd_20_21.iloc[30, 1:10] = np.nan

#4. Change all datatypes (except those in county) to floats 
#found this on stack overflow to change datatypes of all but one column 

ignore = ['County']

#NEED TO SAVE THIS TO THE CURRENT DATAFRAME WITH DF=
df_pmd_20_21 = (df_pmd_20_21.set_index(ignore, append=True)
        .astype(float)
        .reset_index(ignore)
       )

# df_pmd_20_21.info()

#https://stackoverflow.com/questions/70893764/how-to-change-the-column-type-of-all-columns-except-the-first-in-pandas

#4.Drop percentage columns and then recalculate later 
df_pmd_20_21=df_pmd_20_21.drop(["Antlered_% Change", "Antlerless_% Change", "Total_% Change"], axis=1)
df_pmd_20_21

,County,Antlered_2019-20,Antlered_2020-21,Antlerless_2019-20,Antlerless_2020-21,Total_2019-20,Total_2020-21
0,Allegany,1667.0,1921.0,1179.0,1379.0,2846.0,3300.0
1,Anne Arundel,966.0,642.0,1653.0,1277.0,2619.0,1919.0
2,Baltimore,1774.0,1781.0,3195.0,3575.0,4969.0,5356.0
3,Calvert,639.0,468.0,1025.0,916.0,1664.0,1384.0
4,Caroline,NaN,NaN,NaN,NaN,NaN,NaN
5,whitetail,785.0,884.0,1797.0,1894.0,2582.0,2778.0
6,sika,0.0,0.0,1.0,2.0,1.0,2.0
7,Carroll,2016.0,2196.0,3537.0,4006.0,5553.0,6202.0
8,Cecil,1226.0,1227.0,2468.0,2530.0,3694.0,3757.0
9,Charles,1349.0,1074.0,1868.0,1557.0,3217.0,2631.0
10,Dorchester,NaN,NaN,NaN,NaN,NaN,NaN
11,whitetail,748.0,728.0,1203.0,1327.0,1951.0,2055.0
12,sika,1405.0,1337.0,1711.0,1749.0,3116.0,3086.0
13,Frederick,2543.0,2854.0,3815.0,4488.0,6358.0,7342.0
14,Garrett,2733.0,2873.0,1874.0,2031.0,4607.0,4904.0
15,Harford,1224.0,1209.0,2353.0,2371.0,3577.0,3580.0
16,Howard,798.0,807.0,1470.0,1576.0,2268.0,2383.0
17,Kent,1162.0,1044.0,2020.0,2108.0,3182.0,3152.0
18,Montgomery,1367.0,1363.0,2588.0,2741.0,3955.0,4104.0
19,Prince George’s,885.0,662.0,1311.0,963.0,2196.0,1625.0
20,Queen Anne’s,1127.0,1006.0,2248.0,2321.0,3375.0,3327.0
21,St. Mary’s,962.0,792.0,1547.0,1264.0,2509.0,2056.0
22,Somerset,NaN,NaN,NaN,NaN,NaN,NaN
23,whitetail,649.0,691.0,1488.0,1566.0,2137.0,2257.0
24,sika,8.0,7.0,8.0,8.0,16.0,16.0
25,Talbot,717.0,697.0,1637.0,1576.0,2354.0,2273.0
26,Washington,1846.0,2096.0,2195.0,2616.0,4041.0,4712.0
27,Wicomico,NaN,NaN,NaN,NaN,NaN,NaN
28,whitetail,975.0,1063.0,1963.0,2289.0,2938.0,3352.0
29,sika,83.0,118.0,114.0,116.0,197.0,234.0
30,Worcester,NaN,NaN,NaN,NaN,NaN,NaN
31,whitetail,1075.0,1164.0,2343.0,2662.0,3418.0,3826.0
32,sika,55.0,38.0,61.0,78.0,116.0,116.0
33,Total,30785.0,30742.0,48672.0,50987.0,79457.0,81729.0

In [36]:
#---------2020-2021 MORE CLEANING: TEST TRIAL FOR COMBINING SUMS---------#
#5. Add whitetail and sika counts for each county manually, and then fill those sums into currently NaN county row 

#CAROLINE COUNTY
df_pmd_20_21.iloc[4, 1] = df_pmd_20_21.iloc[[5, 6], 1].sum()
df_pmd_20_21.iloc[4, 2] = df_pmd_20_21.iloc[[5,6], 2].sum()
df_pmd_20_21.iloc[4, 3] = df_pmd_20_21.iloc[[5, 6], 3].sum()
df_pmd_20_21.iloc[4, 4] = df_pmd_20_21.iloc[[5,6], 4].sum()
df_pmd_20_21.iloc[4, 5] = df_pmd_20_21.iloc[[5, 6], 5].sum()
df_pmd_20_21.iloc[4, 6] = df_pmd_20_21.iloc[[5,6], 6].sum()

df_pmd_20_21

,County,Antlered_2019-20,Antlered_2020-21,Antlerless_2019-20,Antlerless_2020-21,Total_2019-20,Total_2020-21
0,Allegany,1667.0,1921.0,1179.0,1379.0,2846.0,3300.0
1,Anne Arundel,966.0,642.0,1653.0,1277.0,2619.0,1919.0
2,Baltimore,1774.0,1781.0,3195.0,3575.0,4969.0,5356.0
3,Calvert,639.0,468.0,1025.0,916.0,1664.0,1384.0
4,Caroline,785.0,884.0,1798.0,1896.0,2583.0,2780.0
5,whitetail,785.0,884.0,1797.0,1894.0,2582.0,2778.0
6,sika,0.0,0.0,1.0,2.0,1.0,2.0
7,Carroll,2016.0,2196.0,3537.0,4006.0,5553.0,6202.0
8,Cecil,1226.0,1227.0,2468.0,2530.0,3694.0,3757.0
9,Charles,1349.0,1074.0,1868.0,1557.0,3217.0,2631.0
10,Dorchester,NaN,NaN,NaN,NaN,NaN,NaN
11,whitetail,748.0,728.0,1203.0,1327.0,1951.0,2055.0
12,sika,1405.0,1337.0,1711.0,1749.0,3116.0,3086.0
13,Frederick,2543.0,2854.0,3815.0,4488.0,6358.0,7342.0
14,Garrett,2733.0,2873.0,1874.0,2031.0,4607.0,4904.0
15,Harford,1224.0,1209.0,2353.0,2371.0,3577.0,3580.0
16,Howard,798.0,807.0,1470.0,1576.0,2268.0,2383.0
17,Kent,1162.0,1044.0,2020.0,2108.0,3182.0,3152.0
18,Montgomery,1367.0,1363.0,2588.0,2741.0,3955.0,4104.0
19,Prince George’s,885.0,662.0,1311.0,963.0,2196.0,1625.0
20,Queen Anne’s,1127.0,1006.0,2248.0,2321.0,3375.0,3327.0
21,St. Mary’s,962.0,792.0,1547.0,1264.0,2509.0,2056.0
22,Somerset,NaN,NaN,NaN,NaN,NaN,NaN
23,whitetail,649.0,691.0,1488.0,1566.0,2137.0,2257.0
24,sika,8.0,7.0,8.0,8.0,16.0,16.0
25,Talbot,717.0,697.0,1637.0,1576.0,2354.0,2273.0
26,Washington,1846.0,2096.0,2195.0,2616.0,4041.0,4712.0
27,Wicomico,NaN,NaN,NaN,NaN,NaN,NaN
28,whitetail,975.0,1063.0,1963.0,2289.0,2938.0,3352.0
29,sika,83.0,118.0,114.0,116.0,197.0,234.0
30,Worcester,NaN,NaN,NaN,NaN,NaN,NaN
31,whitetail,1075.0,1164.0,2343.0,2662.0,3418.0,3826.0
32,sika,55.0,38.0,61.0,78.0,116.0,116.0
33,Total,30785.0,30742.0,48672.0,50987.0,79457.0,81729.0

In [37]:
#---------2020-2021 MORE CLEANING: COMBINING ALL SUMS FOR WHITETAIL AND SIKA FOR ALL APPLICABLE COUNTIES---------#

# #Dorchester
df_pmd_20_21.iloc[10, 1] = df_pmd_20_21.iloc[[11, 12], 1].sum()
df_pmd_20_21.iloc[10, 2] = df_pmd_20_21.iloc[[11,12], 2].sum()
df_pmd_20_21.iloc[10, 3] = df_pmd_20_21.iloc[[11, 12], 3].sum()
df_pmd_20_21.iloc[10, 4] = df_pmd_20_21.iloc[[11,12], 4].sum()
df_pmd_20_21.iloc[10, 5] = df_pmd_20_21.iloc[[11, 12], 5].sum()
df_pmd_20_21.iloc[10, 6] = df_pmd_20_21.iloc[[11,12], 6].sum()

# #Somerset
df_pmd_20_21.iloc[22, 1] = df_pmd_20_21.iloc[[23, 24], 1].sum()
df_pmd_20_21.iloc[22, 2] = df_pmd_20_21.iloc[[23,24], 2].sum()
df_pmd_20_21.iloc[22, 3] = df_pmd_20_21.iloc[[23, 24], 3].sum()
df_pmd_20_21.iloc[22, 4] = df_pmd_20_21.iloc[[23,24], 4].sum()
df_pmd_20_21.iloc[22, 5] = df_pmd_20_21.iloc[[23, 24], 5].sum()
df_pmd_20_21.iloc[22, 6] = df_pmd_20_21.iloc[[23,24], 6].sum()

# # #Wicomico
df_pmd_20_21.iloc[27, 1] = df_pmd_20_21.iloc[[28, 29], 1].sum()
df_pmd_20_21.iloc[27, 2] = df_pmd_20_21.iloc[[28,29], 2].sum()
df_pmd_20_21.iloc[27, 3] = df_pmd_20_21.iloc[[28, 29], 3].sum()
df_pmd_20_21.iloc[27, 4] = df_pmd_20_21.iloc[[28,29], 4].sum()
df_pmd_20_21.iloc[27, 5] = df_pmd_20_21.iloc[[28, 29], 5].sum()
df_pmd_20_21.iloc[27, 6] = df_pmd_20_21.iloc[[28,29], 6].sum()

# # #Worcester
df_pmd_20_21.iloc[30, 1] = df_pmd_20_21.iloc[[31, 32], 1].sum()
df_pmd_20_21.iloc[30, 2] = df_pmd_20_21.iloc[[31,32], 2].sum()
df_pmd_20_21.iloc[30, 3] = df_pmd_20_21.iloc[[31, 32], 3].sum()
df_pmd_20_21.iloc[30, 4] = df_pmd_20_21.iloc[[31,32], 4].sum()
df_pmd_20_21.iloc[30, 5] = df_pmd_20_21.iloc[[31, 32], 5].sum()
df_pmd_20_21.iloc[30, 6] = df_pmd_20_21.iloc[[31,32], 6].sum()

df_pmd_20_21

,County,Antlered_2019-20,Antlered_2020-21,Antlerless_2019-20,Antlerless_2020-21,Total_2019-20,Total_2020-21
0,Allegany,1667.0,1921.0,1179.0,1379.0,2846.0,3300.0
1,Anne Arundel,966.0,642.0,1653.0,1277.0,2619.0,1919.0
2,Baltimore,1774.0,1781.0,3195.0,3575.0,4969.0,5356.0
3,Calvert,639.0,468.0,1025.0,916.0,1664.0,1384.0
4,Caroline,785.0,884.0,1798.0,1896.0,2583.0,2780.0
5,whitetail,785.0,884.0,1797.0,1894.0,2582.0,2778.0
6,sika,0.0,0.0,1.0,2.0,1.0,2.0
7,Carroll,2016.0,2196.0,3537.0,4006.0,5553.0,6202.0
8,Cecil,1226.0,1227.0,2468.0,2530.0,3694.0,3757.0
9,Charles,1349.0,1074.0,1868.0,1557.0,3217.0,2631.0
10,Dorchester,2153.0,2065.0,2914.0,3076.0,5067.0,5141.0
11,whitetail,748.0,728.0,1203.0,1327.0,1951.0,2055.0
12,sika,1405.0,1337.0,1711.0,1749.0,3116.0,3086.0
13,Frederick,2543.0,2854.0,3815.0,4488.0,6358.0,7342.0
14,Garrett,2733.0,2873.0,1874.0,2031.0,4607.0,4904.0
15,Harford,1224.0,1209.0,2353.0,2371.0,3577.0,3580.0
16,Howard,798.0,807.0,1470.0,1576.0,2268.0,2383.0
17,Kent,1162.0,1044.0,2020.0,2108.0,3182.0,3152.0
18,Montgomery,1367.0,1363.0,2588.0,2741.0,3955.0,4104.0
19,Prince George’s,885.0,662.0,1311.0,963.0,2196.0,1625.0
20,Queen Anne’s,1127.0,1006.0,2248.0,2321.0,3375.0,3327.0
21,St. Mary’s,962.0,792.0,1547.0,1264.0,2509.0,2056.0
22,Somerset,657.0,698.0,1496.0,1574.0,2153.0,2273.0
23,whitetail,649.0,691.0,1488.0,1566.0,2137.0,2257.0
24,sika,8.0,7.0,8.0,8.0,16.0,16.0
25,Talbot,717.0,697.0,1637.0,1576.0,2354.0,2273.0
26,Washington,1846.0,2096.0,2195.0,2616.0,4041.0,4712.0
27,Wicomico,1058.0,1181.0,2077.0,2405.0,3135.0,3586.0
28,whitetail,975.0,1063.0,1963.0,2289.0,2938.0,3352.0
29,sika,83.0,118.0,114.0,116.0,197.0,234.0
30,Worcester,1130.0,1202.0,2404.0,2740.0,3534.0,3942.0
31,whitetail,1075.0,1164.0,2343.0,2662.0,3418.0,3826.0
32,sika,55.0,38.0,61.0,78.0,116.0,116.0
33,Total,30785.0,30742.0,48672.0,50987.0,79457.0,81729.0

In [38]:
#---------2020-2021 FINAL CLEANING: DROPPING ROWS---------#
#Filter county values for "whitetail" and "sika" and drop those rows
df_pmd_20_21=df_pmd_20_21[ df_pmd_20_21[ "County" ].str.contains( "whitetail|sika" )== False]
df_pmd_20_21 = df_pmd_20_21.reset_index(drop=True)
df_pmd_20_21.to_csv("df_pmd_20_21.csv")

In [39]:
#2019-2020 Processed Harvest Data Pt. 1

#PANDAS
df_pmd_19_20 = pd.read_html("https://news.maryland.gov/dnr/2020/02/13/maryland-hunters-harvest-nearly-80000-deer-during-2019-2020-season/", storage_options={"User-Agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0"})
df_pmd_19_20 = df_pmd_19_20[0]
#type(df_pmd_19_20)
df_pmd_19_20.to_csv("df_pmd_19_20.csv")

In [40]:
#2019-2020 Processed Harvest Data pt. 2 = COMBINING HEADERS 

header_row_one_1920 = df_pmd_19_20.iloc[1]
header_row_two_1920 = df_pmd_19_20.iloc[2]

new_columns = []

for header_one, header_two in zip(header_row_one_1920, header_row_two_1920):
    if pd.isna(header_one):
    #https://pandas.pydata.org/docs/reference/api/pandas.isna.html 
        combined_header = header_two 
    else:
        combined_header = f"{header_one}_{header_two}"
    new_columns.append(combined_header)

#STORE NEW COMBINED HEADERS
df_pmd_19_20.columns = new_columns

#REPLACE OLD HEADERS WITH COMBINED
df_pmd_19_20 = df_pmd_19_20.iloc[3:]
df_pmd_19_20 = df_pmd_19_20.reset_index(drop=True)

df_pmd_19_20

,County,Antlered_2019-20,Antlered_2018-19,Antlered_% Change,Antlerless_2019-20,Antlerless_2018-19,Antlerless_% Change,Total_2019-20,Total_2018-19,Total_% Change
0,Allegany,1667,2017,-17.4,1179,1444,-18.4,2846,3461,-17.8
1,Anne Arundel,966,920,5.0,1653,1562,5.8,2619,2482,5.5
2,Baltimore,1774,1641,8.1,3195,2963,7.8,4969,4604,7.9
3,Calvert,639,614,4.1,1025,947,8.2,1664,1561,6.6
4,Caroline,Caroline,Caroline,Caroline,Caroline,Caroline,Caroline,Caroline,Caroline,Caroline
5,whitetail,785,829,-5.3,1797,1727,4.1,2582,2556,1.0
6,sika,0,0,*,1,1,*,1,1,*
7,Carroll,2016,2197,-8.2,3537,3224,9.7,5553,5421,2.4
8,Cecil,Cecil,Cecil,Cecil,Cecil,Cecil,Cecil,Cecil,Cecil,Cecil
9,whitetail,1226,1237,-0.9,2468,2269,8.8,3694,3506,5.4
10,sika,1,0,*,1,0,*,1,0,*
11,Charles,1349,1031,30.8,1868,1328,40.7,3217,2359,36.4
12,Dorchester,Dorchester,Dorchester,Dorchester,Dorchester,Dorchester,Dorchester,Dorchester,Dorchester,Dorchester
13,whitetail,748,734,1.9,1203,1161,3.6,1951,1895,3.0
14,sika,1405,1466,-4.2,1711,1712,-0.1,3116,3178,-2.0
15,Frederick,2543,2692,-5.5,3815,3853,-1.0,6358,6545,-2.9
16,Garrett,2733,2827,-3.3,1874,2146,-12.7,4607,4973,-7.4
17,Harford,1224,1145,6.9,2353,2165,8.7,3577,3310,8.1
18,Howard,798,741,7.7,1470,1286,14.3,2268,2027,11.9
19,Kent,1162,1144,1.6,2020,1949,3.6,3182,3093,2.9
20,Montgomery,1367,1378,-0.8,2588,2507,3.2,3955,3885,1.8
21,Prince George’s,885,799,10.8,1311,1263,3.8,2196,2062,6.5
22,Queen Anne’s,1127,1133,-0.5,2248,2060,9.1,3375,3193,5.7
23,St. Mary’s,962,740,30.0,1547,1137,36.1,2509,1877,33.7
24,Somerset,Somerset,Somerset,Somerset,Somerset,Somerset,Somerset,Somerset,Somerset,Somerset
25,whitetail,649,746,-13.0,1488,1292,15.2,2137,2038,4.9
26,sika,8,11,*,8,5,*,16,16,*
27,Talbot,717,784,-8.5,1637,1535,6.6,2354,2319,1.5
28,Washington,1846,2166,-14.8,2195,2454,-10.6,4041,4620,-12.5
29,Wicomico,Wicomico,Wicomico,Wicomico,Wicomico,Wicomico,Wicomico,Wicomico,Wicomico,Wicomico
30,whitetail,975,1036,-5.9,1963,1819,7.9,2938,2855,2.9
31,sika,83,110,*,114,81,*,197,191,*
32,Worcester,Worcester,Worcester,Worcester,Worcester,Worcester,Worcester,Worcester,Worcester,Worcester
33,whitetail,1075,1148,-6.4,2343,2158,8.6,3418,3306,3.4
34,sika,55,22,*,61,26,*,116,48,*
35,Total,30785,31308,-1.7,48672,46074,5.6,79457,77382,2.7
36,*Small sample size,*Small sample size,*Small sample size,*Small sample size,*Small sample size,*Small sample size,*Small sample size,*Small sample size,*Small sample size,*Small sample size

In [41]:
#---------2019-2020 MORE CLEANING: REPLACING * , DROPPING LAST ROW, CHANGING DATATYPES, DROPPING % COLUMNS---------#

#FOR FILLED COUNTY ROWS 

#1. Replace asterisks with NaN
import numpy as np
df_pmd_19_20=df_pmd_19_20.replace(r'^\*$', np.nan, regex=True)
##https://stackoverflow.com/questions/45311262/replace-a-variable-number-of-asterisks-with-nan-in-a-dataframe 

#2. Drop last row, which just has "small sample size" text
df_pmd_19_20 = df_pmd_19_20.iloc[:-1]

#3. NEW STEP 
df_pmd_19_20.iloc[4, 1:10] = np.nan
df_pmd_19_20.iloc[8, 1:10] = np.nan
df_pmd_19_20.iloc[12, 1:10] = np.nan
df_pmd_19_20.iloc[24, 1:10] = np.nan
df_pmd_19_20.iloc[29, 1:10] = np.nan
df_pmd_19_20.iloc[32, 1:10] = np.nan

#4. Change all datatypes (except those in county) to floats 
#found this on stack overflow to change datatypes of all but one column 

ignore = ['County']

#NEED TO SAVE THIS TO THE CURRENT DATAFRAME WITH DF=
df_pmd_19_20 = (df_pmd_19_20.set_index(ignore, append=True)
        .astype(float)
        .reset_index(ignore)
       )

# df_pmd_19_20.info()

#https://stackoverflow.com/questions/70893764/how-to-change-the-column-type-of-all-columns-except-the-first-in-pandas

#4.Drop percentage columns and then recalculate later 
df_pmd_19_20=df_pmd_19_20.drop(["Antlered_% Change", "Antlerless_% Change", "Total_% Change"], axis=1)
df_pmd_19_20

,County,Antlered_2019-20,Antlered_2018-19,Antlerless_2019-20,Antlerless_2018-19,Total_2019-20,Total_2018-19
0,Allegany,1667.0,2017.0,1179.0,1444.0,2846.0,3461.0
1,Anne Arundel,966.0,920.0,1653.0,1562.0,2619.0,2482.0
2,Baltimore,1774.0,1641.0,3195.0,2963.0,4969.0,4604.0
3,Calvert,639.0,614.0,1025.0,947.0,1664.0,1561.0
4,Caroline,NaN,NaN,NaN,NaN,NaN,NaN
5,whitetail,785.0,829.0,1797.0,1727.0,2582.0,2556.0
6,sika,0.0,0.0,1.0,1.0,1.0,1.0
7,Carroll,2016.0,2197.0,3537.0,3224.0,5553.0,5421.0
8,Cecil,NaN,NaN,NaN,NaN,NaN,NaN
9,whitetail,1226.0,1237.0,2468.0,2269.0,3694.0,3506.0
10,sika,1.0,0.0,1.0,0.0,1.0,0.0
11,Charles,1349.0,1031.0,1868.0,1328.0,3217.0,2359.0
12,Dorchester,NaN,NaN,NaN,NaN,NaN,NaN
13,whitetail,748.0,734.0,1203.0,1161.0,1951.0,1895.0
14,sika,1405.0,1466.0,1711.0,1712.0,3116.0,3178.0
15,Frederick,2543.0,2692.0,3815.0,3853.0,6358.0,6545.0
16,Garrett,2733.0,2827.0,1874.0,2146.0,4607.0,4973.0
17,Harford,1224.0,1145.0,2353.0,2165.0,3577.0,3310.0
18,Howard,798.0,741.0,1470.0,1286.0,2268.0,2027.0
19,Kent,1162.0,1144.0,2020.0,1949.0,3182.0,3093.0
20,Montgomery,1367.0,1378.0,2588.0,2507.0,3955.0,3885.0
21,Prince George’s,885.0,799.0,1311.0,1263.0,2196.0,2062.0
22,Queen Anne’s,1127.0,1133.0,2248.0,2060.0,3375.0,3193.0
23,St. Mary’s,962.0,740.0,1547.0,1137.0,2509.0,1877.0
24,Somerset,NaN,NaN,NaN,NaN,NaN,NaN
25,whitetail,649.0,746.0,1488.0,1292.0,2137.0,2038.0
26,sika,8.0,11.0,8.0,5.0,16.0,16.0
27,Talbot,717.0,784.0,1637.0,1535.0,2354.0,2319.0
28,Washington,1846.0,2166.0,2195.0,2454.0,4041.0,4620.0
29,Wicomico,NaN,NaN,NaN,NaN,NaN,NaN
30,whitetail,975.0,1036.0,1963.0,1819.0,2938.0,2855.0
31,sika,83.0,110.0,114.0,81.0,197.0,191.0
32,Worcester,NaN,NaN,NaN,NaN,NaN,NaN
33,whitetail,1075.0,1148.0,2343.0,2158.0,3418.0,3306.0
34,sika,55.0,22.0,61.0,26.0,116.0,48.0
35,Total,30785.0,31308.0,48672.0,46074.0,79457.0,77382.0

In [42]:
#---------2019-2020 MORE CLEANING: TEST TRIAL FOR COMBINING SUMS---------#
#5. Add whitetail and sika counts for each county manually, and then fill those sums into currently NaN county row 

#CAROLINE COUNTY
df_pmd_19_20.iloc[4, 1] = df_pmd_19_20.iloc[[5, 6], 1].sum()
df_pmd_19_20.iloc[4, 2] = df_pmd_19_20.iloc[[5,6], 2].sum()
df_pmd_19_20.iloc[4, 3] = df_pmd_19_20.iloc[[5, 6], 3].sum()
df_pmd_19_20.iloc[4, 4] = df_pmd_19_20.iloc[[5,6], 4].sum()
df_pmd_19_20.iloc[4, 5] = df_pmd_19_20.iloc[[5, 6], 5].sum()
df_pmd_19_20.iloc[4, 6] = df_pmd_19_20.iloc[[5,6], 6].sum()

df_pmd_19_20

,County,Antlered_2019-20,Antlered_2018-19,Antlerless_2019-20,Antlerless_2018-19,Total_2019-20,Total_2018-19
0,Allegany,1667.0,2017.0,1179.0,1444.0,2846.0,3461.0
1,Anne Arundel,966.0,920.0,1653.0,1562.0,2619.0,2482.0
2,Baltimore,1774.0,1641.0,3195.0,2963.0,4969.0,4604.0
3,Calvert,639.0,614.0,1025.0,947.0,1664.0,1561.0
4,Caroline,785.0,829.0,1798.0,1728.0,2583.0,2557.0
5,whitetail,785.0,829.0,1797.0,1727.0,2582.0,2556.0
6,sika,0.0,0.0,1.0,1.0,1.0,1.0
7,Carroll,2016.0,2197.0,3537.0,3224.0,5553.0,5421.0
8,Cecil,NaN,NaN,NaN,NaN,NaN,NaN
9,whitetail,1226.0,1237.0,2468.0,2269.0,3694.0,3506.0
10,sika,1.0,0.0,1.0,0.0,1.0,0.0
11,Charles,1349.0,1031.0,1868.0,1328.0,3217.0,2359.0
12,Dorchester,NaN,NaN,NaN,NaN,NaN,NaN
13,whitetail,748.0,734.0,1203.0,1161.0,1951.0,1895.0
14,sika,1405.0,1466.0,1711.0,1712.0,3116.0,3178.0
15,Frederick,2543.0,2692.0,3815.0,3853.0,6358.0,6545.0
16,Garrett,2733.0,2827.0,1874.0,2146.0,4607.0,4973.0
17,Harford,1224.0,1145.0,2353.0,2165.0,3577.0,3310.0
18,Howard,798.0,741.0,1470.0,1286.0,2268.0,2027.0
19,Kent,1162.0,1144.0,2020.0,1949.0,3182.0,3093.0
20,Montgomery,1367.0,1378.0,2588.0,2507.0,3955.0,3885.0
21,Prince George’s,885.0,799.0,1311.0,1263.0,2196.0,2062.0
22,Queen Anne’s,1127.0,1133.0,2248.0,2060.0,3375.0,3193.0
23,St. Mary’s,962.0,740.0,1547.0,1137.0,2509.0,1877.0
24,Somerset,NaN,NaN,NaN,NaN,NaN,NaN
25,whitetail,649.0,746.0,1488.0,1292.0,2137.0,2038.0
26,sika,8.0,11.0,8.0,5.0,16.0,16.0
27,Talbot,717.0,784.0,1637.0,1535.0,2354.0,2319.0
28,Washington,1846.0,2166.0,2195.0,2454.0,4041.0,4620.0
29,Wicomico,NaN,NaN,NaN,NaN,NaN,NaN
30,whitetail,975.0,1036.0,1963.0,1819.0,2938.0,2855.0
31,sika,83.0,110.0,114.0,81.0,197.0,191.0
32,Worcester,NaN,NaN,NaN,NaN,NaN,NaN
33,whitetail,1075.0,1148.0,2343.0,2158.0,3418.0,3306.0
34,sika,55.0,22.0,61.0,26.0,116.0,48.0
35,Total,30785.0,31308.0,48672.0,46074.0,79457.0,77382.0

In [43]:
#---------2019-2020 MORE CLEANING: COMBINING ALL SUMS FOR WHITETAIL AND SIKA FOR ALL APPLICABLE COUNTIES---------#

# Cecil
df_pmd_19_20.iloc[8, 1] = df_pmd_19_20.iloc[[9, 10], 1].sum()
df_pmd_19_20.iloc[8, 2] = df_pmd_19_20.iloc[[9, 10], 2].sum()
df_pmd_19_20.iloc[8, 3] = df_pmd_19_20.iloc[[9, 10], 3].sum()
df_pmd_19_20.iloc[8, 4] = df_pmd_19_20.iloc[[9, 10], 4].sum()
df_pmd_19_20.iloc[8, 5] = df_pmd_19_20.iloc[[9, 10], 5].sum()
df_pmd_19_20.iloc[8, 6] = df_pmd_19_20.iloc[[9, 10], 6].sum()

# #Dorchester
df_pmd_19_20.iloc[12, 1] = df_pmd_19_20.iloc[[13, 14], 1].sum()
df_pmd_19_20.iloc[12, 2] = df_pmd_19_20.iloc[[13,14], 2].sum()
df_pmd_19_20.iloc[12, 3] = df_pmd_19_20.iloc[[13, 14], 3].sum()
df_pmd_19_20.iloc[12, 4] = df_pmd_19_20.iloc[[13,14], 4].sum()
df_pmd_19_20.iloc[12, 5] = df_pmd_19_20.iloc[[13, 14], 5].sum()
df_pmd_19_20.iloc[12, 6] = df_pmd_19_20.iloc[[13,14], 6].sum()

# #Somerset
df_pmd_19_20.iloc[24, 1] = df_pmd_19_20.iloc[[25, 26], 1].sum()
df_pmd_19_20.iloc[24, 2] = df_pmd_19_20.iloc[[25,26], 2].sum()
df_pmd_19_20.iloc[24, 3] = df_pmd_19_20.iloc[[25, 26], 3].sum()
df_pmd_19_20.iloc[24, 4] = df_pmd_19_20.iloc[[25,26], 4].sum()
df_pmd_19_20.iloc[24, 5] = df_pmd_19_20.iloc[[25, 26], 5].sum()
df_pmd_19_20.iloc[24, 6] = df_pmd_19_20.iloc[[25,26], 6].sum()

# # #Wicomico
df_pmd_19_20.iloc[29, 1] = df_pmd_19_20.iloc[[30, 31], 1].sum()
df_pmd_19_20.iloc[29, 2] = df_pmd_19_20.iloc[[30,31], 2].sum()
df_pmd_19_20.iloc[29, 3] = df_pmd_19_20.iloc[[30, 31], 3].sum()
df_pmd_19_20.iloc[29, 4] = df_pmd_19_20.iloc[[30,31], 4].sum()
df_pmd_19_20.iloc[29, 5] = df_pmd_19_20.iloc[[30, 31], 5].sum()
df_pmd_19_20.iloc[29, 6] = df_pmd_19_20.iloc[[30,31], 6].sum()

# # #Worcester
df_pmd_19_20.iloc[32, 1] = df_pmd_19_20.iloc[[33, 34], 1].sum()
df_pmd_19_20.iloc[32, 2] = df_pmd_19_20.iloc[[33,34], 2].sum()
df_pmd_19_20.iloc[32, 3] = df_pmd_19_20.iloc[[33, 34], 3].sum()
df_pmd_19_20.iloc[32, 4] = df_pmd_19_20.iloc[[33,34], 4].sum()
df_pmd_19_20.iloc[32, 5] = df_pmd_19_20.iloc[[33, 34], 5].sum()
df_pmd_19_20.iloc[32, 6] = df_pmd_19_20.iloc[[33,34], 6].sum()

df_pmd_19_20

,County,Antlered_2019-20,Antlered_2018-19,Antlerless_2019-20,Antlerless_2018-19,Total_2019-20,Total_2018-19
0,Allegany,1667.0,2017.0,1179.0,1444.0,2846.0,3461.0
1,Anne Arundel,966.0,920.0,1653.0,1562.0,2619.0,2482.0
2,Baltimore,1774.0,1641.0,3195.0,2963.0,4969.0,4604.0
3,Calvert,639.0,614.0,1025.0,947.0,1664.0,1561.0
4,Caroline,785.0,829.0,1798.0,1728.0,2583.0,2557.0
5,whitetail,785.0,829.0,1797.0,1727.0,2582.0,2556.0
6,sika,0.0,0.0,1.0,1.0,1.0,1.0
7,Carroll,2016.0,2197.0,3537.0,3224.0,5553.0,5421.0
8,Cecil,1227.0,1237.0,2469.0,2269.0,3695.0,3506.0
9,whitetail,1226.0,1237.0,2468.0,2269.0,3694.0,3506.0
10,sika,1.0,0.0,1.0,0.0,1.0,0.0
11,Charles,1349.0,1031.0,1868.0,1328.0,3217.0,2359.0
12,Dorchester,2153.0,2200.0,2914.0,2873.0,5067.0,5073.0
13,whitetail,748.0,734.0,1203.0,1161.0,1951.0,1895.0
14,sika,1405.0,1466.0,1711.0,1712.0,3116.0,3178.0
15,Frederick,2543.0,2692.0,3815.0,3853.0,6358.0,6545.0
16,Garrett,2733.0,2827.0,1874.0,2146.0,4607.0,4973.0
17,Harford,1224.0,1145.0,2353.0,2165.0,3577.0,3310.0
18,Howard,798.0,741.0,1470.0,1286.0,2268.0,2027.0
19,Kent,1162.0,1144.0,2020.0,1949.0,3182.0,3093.0
20,Montgomery,1367.0,1378.0,2588.0,2507.0,3955.0,3885.0
21,Prince George’s,885.0,799.0,1311.0,1263.0,2196.0,2062.0
22,Queen Anne’s,1127.0,1133.0,2248.0,2060.0,3375.0,3193.0
23,St. Mary’s,962.0,740.0,1547.0,1137.0,2509.0,1877.0
24,Somerset,657.0,757.0,1496.0,1297.0,2153.0,2054.0
25,whitetail,649.0,746.0,1488.0,1292.0,2137.0,2038.0
26,sika,8.0,11.0,8.0,5.0,16.0,16.0
27,Talbot,717.0,784.0,1637.0,1535.0,2354.0,2319.0
28,Washington,1846.0,2166.0,2195.0,2454.0,4041.0,4620.0
29,Wicomico,1058.0,1146.0,2077.0,1900.0,3135.0,3046.0
30,whitetail,975.0,1036.0,1963.0,1819.0,2938.0,2855.0
31,sika,83.0,110.0,114.0,81.0,197.0,191.0
32,Worcester,1130.0,1170.0,2404.0,2184.0,3534.0,3354.0
33,whitetail,1075.0,1148.0,2343.0,2158.0,3418.0,3306.0
34,sika,55.0,22.0,61.0,26.0,116.0,48.0
35,Total,30785.0,31308.0,48672.0,46074.0,79457.0,77382.0

In [44]:
#---------2019-2020 FINAL CLEANING: DROPPING ROWS---------#
#Filter county values for "whitetail" and "sika" and drop those rows
df_pmd_19_20=df_pmd_19_20[ df_pmd_19_20[ "County" ].str.contains( "whitetail|sika" )== False]
df_pmd_19_20 = df_pmd_19_20.reset_index(drop=True)
df_pmd_19_20.to_csv("df_pmd_19_20.csv")

In [45]:
#2018-2019 Processed Harvest Data Pt. 1

#PANDAS
df_pmd_18_19 = pd.read_html("https://news.maryland.gov/dnr/2019/02/15/maryland-hunters-harvest-77000-deer-during-2018-2019-season/ ", storage_options={"User-Agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0"})
df_pmd_18_19 = df_pmd_18_19[0]
#type(df_pmd_18_19)
df_pmd_18_19.to_csv("df_pmd_18_19.csv")

In [46]:
#2018-2019 Processed Harvest Data pt. 2 = COMBINING HEADERS

header_row_one_1819 = df_pmd_18_19.iloc[1]
header_row_two_1819 = df_pmd_18_19.iloc[2]

new_columns = []

for header_one, header_two in zip(header_row_one_1819, header_row_two_1819):
    if pd.isna(header_one):
    #https://pandas.pydata.org/docs/reference/api/pandas.isna.html 
        combined_header = header_two 
    else:
        combined_header = f"{header_one}_{header_two}"
    new_columns.append(combined_header)

#STORE NEW COMBINED HEADERS
df_pmd_18_19.columns = new_columns

#REPLACE OLD HEADERS WITH COMBINED
df_pmd_18_19 = df_pmd_18_19.iloc[3:]
df_pmd_18_19 = df_pmd_18_19.reset_index(drop=True)

df_pmd_18_19

,County,Antlered_2017-18,Antlered_2018-19,Antlered_% Change,Antlerless_2017-18,Antlerless_2018-19,Antlerless_% Change,Total_2017-18,Total_2018-19,Total_% Change
0,Allegany,2078,2017,-2.9,1283,1444,12.5,3361,3461,3.0
1,Anne Arundel,978,920,-5.9,2001,1562,-21.9,2979,2482,-16.7
2,Baltimore,1754,1641,-6.4,3805,2963,-22.1,5559,4604,-17.2
3,Calvert,558,614,10.0,1130,947,-16.2,1688,1561,-7.5
4,Caroline,Caroline,Caroline,Caroline,Caroline,Caroline,Caroline,Caroline,Caroline,Caroline
5,whitetail,756,829,9.7,1824,1727,-5.3,2580,2556,-0.9
6,sika,1,0,*,1,1,*,2,1,*
7,Carroll,2116,2197,3.8,3780,3224,-14.7,5896,5421,-8.1
8,Cecil,1261,1237,-1.9,2442,2269,-7.1,3703,3506,-5.3
9,Charles,1166,1031,-11.6,2246,1328,-40.9,3412,2359,-30.9
10,Dorchester,Dorchester,Dorchester,Dorchester,Dorchester,Dorchester,Dorchester,Dorchester,Dorchester,Dorchester
11,whitetail,678,734,8.3,1482,1161,-21.7,2160,1895,-12.3
12,sika,1306,1466,12.3,1622,1712,5.5,2928,3178,8.5
13,Frederick,2666,2692,1.0,4688,3853,-17.8,7354,6545,-11.0
14,Garrett,3335,2827,-15.2,2014,2146,6.6,5349,4973,-7.0
15,Harford,1211,1145,-5.5,2466,2165,-12.2,3677,3310,-10.0
16,Howard,738,741,0.4,1689,1286,-23.9,2427,2027,-16.5
17,Kent,1156,1144,-1.0,2270,1949,-14.1,3426,3093,-9.7
18,Montgomery,1457,1378,-5.4,3326,2507,-24.6,4783,3885,-18.8
19,Prince George’s,828,799,-3.5,1560,1263,-19.0,2388,2062,-13.7
20,Queen Anne’s,1189,1133,-4.7,2701,2060,-23.7,3890,3193,-17.9
21,Saint Mary’s,845,740,-12.4,1847,1137,-38.4,2692,1877,-30.3
22,Somerset,Somerset,Somerset,Somerset,Somerset,Somerset,Somerset,Somerset,Somerset,Somerset
23,whitetail,649,746,14.9,1540,1292,-16.1,2189,2038,-6.9
24,sika,2,11,*,7,5,*,9,16,*
25,Talbot,671,784,16.8,1830,1535,-16.1,2501,2319,-7.3
26,Washington,2135,2166,1.5,2458,2454,-0.2,4593,4620,0.6
27,Wicomico,Wicomico,Wicomico,Wicomico,Wicomico,Wicomico,Wicomico,Wicomico,Wicomico,Wicomico
28,whitetail,952,1036,8.8,2275,1819,-20.0,3227,2855,-11.5
29,sika,85,110,*,83,81,*,168,191,*
30,Worcester,Worcester,Worcester,Worcester,Worcester,Worcester,Worcester,Worcester,Worcester,Worcester
31,whitetail,1070,1148,7.3,2478,2158,-12.9,3548,3306,-6.8
32,sika,29,22,*,24,26,*,53,48,*
33,Total,31670,31308,-1.1,54872,46074,-16.0,86542,77382,-10.6
34,*Small sample size,*Small sample size,*Small sample size,*Small sample size,*Small sample size,*Small sample size,*Small sample size,*Small sample size,*Small sample size,*Small sample size

In [47]:
#---------2018-2019 MORE CLEANING: REPLACING * , DROPPING LAST ROW, CHANGING DATATYPES, DROPPING % COLUMNS---------#

#FOR FILLED COUNTY ROWS 

#1. Replace asterisks with NaN
import numpy as np
df_pmd_18_19=df_pmd_18_19.replace(r'^\*$', np.nan, regex=True)
##https://stackoverflow.com/questions/45311262/replace-a-variable-number-of-asterisks-with-nan-in-a-dataframe 

#2. Drop last row, which just has "small sample size" text
df_pmd_18_19 = df_pmd_18_19.iloc[:-1]

#3. NEW STEP 
df_pmd_18_19.iloc[4, 1:10] = np.nan
df_pmd_18_19.iloc[10, 1:10] = np.nan
df_pmd_18_19.iloc[22, 1:10] = np.nan
df_pmd_18_19.iloc[27, 1:10] = np.nan
df_pmd_18_19.iloc[30, 1:10] = np.nan

#4. Change all datatypes (except those in county) to floats 
#found this on stack overflow to change datatypes of all but one column 

ignore = ['County']

#NEED TO SAVE THIS TO THE CURRENT DATAFRAME WITH DF=
df_pmd_18_19 = (df_pmd_18_19.set_index(ignore, append=True)
        .astype(float)
        .reset_index(ignore)
       )

# df_pmd_18_19.info()

#https://stackoverflow.com/questions/70893764/how-to-change-the-column-type-of-all-columns-except-the-first-in-pandas

#4.Drop percentage columns and then recalculate later 
df_pmd_18_19=df_pmd_18_19.drop(["Antlered_% Change", "Antlerless_% Change", "Total_% Change"], axis=1)
df_pmd_18_19

,County,Antlered_2017-18,Antlered_2018-19,Antlerless_2017-18,Antlerless_2018-19,Total_2017-18,Total_2018-19
0,Allegany,2078.0,2017.0,1283.0,1444.0,3361.0,3461.0
1,Anne Arundel,978.0,920.0,2001.0,1562.0,2979.0,2482.0
2,Baltimore,1754.0,1641.0,3805.0,2963.0,5559.0,4604.0
3,Calvert,558.0,614.0,1130.0,947.0,1688.0,1561.0
4,Caroline,NaN,NaN,NaN,NaN,NaN,NaN
5,whitetail,756.0,829.0,1824.0,1727.0,2580.0,2556.0
6,sika,1.0,0.0,1.0,1.0,2.0,1.0
7,Carroll,2116.0,2197.0,3780.0,3224.0,5896.0,5421.0
8,Cecil,1261.0,1237.0,2442.0,2269.0,3703.0,3506.0
9,Charles,1166.0,1031.0,2246.0,1328.0,3412.0,2359.0
10,Dorchester,NaN,NaN,NaN,NaN,NaN,NaN
11,whitetail,678.0,734.0,1482.0,1161.0,2160.0,1895.0
12,sika,1306.0,1466.0,1622.0,1712.0,2928.0,3178.0
13,Frederick,2666.0,2692.0,4688.0,3853.0,7354.0,6545.0
14,Garrett,3335.0,2827.0,2014.0,2146.0,5349.0,4973.0
15,Harford,1211.0,1145.0,2466.0,2165.0,3677.0,3310.0
16,Howard,738.0,741.0,1689.0,1286.0,2427.0,2027.0
17,Kent,1156.0,1144.0,2270.0,1949.0,3426.0,3093.0
18,Montgomery,1457.0,1378.0,3326.0,2507.0,4783.0,3885.0
19,Prince George’s,828.0,799.0,1560.0,1263.0,2388.0,2062.0
20,Queen Anne’s,1189.0,1133.0,2701.0,2060.0,3890.0,3193.0
21,Saint Mary’s,845.0,740.0,1847.0,1137.0,2692.0,1877.0
22,Somerset,NaN,NaN,NaN,NaN,NaN,NaN
23,whitetail,649.0,746.0,1540.0,1292.0,2189.0,2038.0
24,sika,2.0,11.0,7.0,5.0,9.0,16.0
25,Talbot,671.0,784.0,1830.0,1535.0,2501.0,2319.0
26,Washington,2135.0,2166.0,2458.0,2454.0,4593.0,4620.0
27,Wicomico,NaN,NaN,NaN,NaN,NaN,NaN
28,whitetail,952.0,1036.0,2275.0,1819.0,3227.0,2855.0
29,sika,85.0,110.0,83.0,81.0,168.0,191.0
30,Worcester,NaN,NaN,NaN,NaN,NaN,NaN
31,whitetail,1070.0,1148.0,2478.0,2158.0,3548.0,3306.0
32,sika,29.0,22.0,24.0,26.0,53.0,48.0
33,Total,31670.0,31308.0,54872.0,46074.0,86542.0,77382.0

In [48]:
#---------2018-2019 MORE CLEANING: TEST TRIAL FOR COMBINING SUMS---------#
#5. Add whitetail and sika counts for each county manually, and then fill those sums into currently NaN county row 

#CAROLINE COUNTY
df_pmd_18_19.iloc[4, 1] = df_pmd_18_19.iloc[[5, 6], 1].sum()
df_pmd_18_19.iloc[4, 2] = df_pmd_18_19.iloc[[5,6], 2].sum()
df_pmd_18_19.iloc[4, 3] = df_pmd_18_19.iloc[[5, 6], 3].sum()
df_pmd_18_19.iloc[4, 4] = df_pmd_18_19.iloc[[5,6], 4].sum()
df_pmd_18_19.iloc[4, 5] = df_pmd_18_19.iloc[[5, 6], 5].sum()
df_pmd_18_19.iloc[4, 6] = df_pmd_18_19.iloc[[5,6], 6].sum()

df_pmd_18_19

,County,Antlered_2017-18,Antlered_2018-19,Antlerless_2017-18,Antlerless_2018-19,Total_2017-18,Total_2018-19
0,Allegany,2078.0,2017.0,1283.0,1444.0,3361.0,3461.0
1,Anne Arundel,978.0,920.0,2001.0,1562.0,2979.0,2482.0
2,Baltimore,1754.0,1641.0,3805.0,2963.0,5559.0,4604.0
3,Calvert,558.0,614.0,1130.0,947.0,1688.0,1561.0
4,Caroline,757.0,829.0,1825.0,1728.0,2582.0,2557.0
5,whitetail,756.0,829.0,1824.0,1727.0,2580.0,2556.0
6,sika,1.0,0.0,1.0,1.0,2.0,1.0
7,Carroll,2116.0,2197.0,3780.0,3224.0,5896.0,5421.0
8,Cecil,1261.0,1237.0,2442.0,2269.0,3703.0,3506.0
9,Charles,1166.0,1031.0,2246.0,1328.0,3412.0,2359.0
10,Dorchester,NaN,NaN,NaN,NaN,NaN,NaN
11,whitetail,678.0,734.0,1482.0,1161.0,2160.0,1895.0
12,sika,1306.0,1466.0,1622.0,1712.0,2928.0,3178.0
13,Frederick,2666.0,2692.0,4688.0,3853.0,7354.0,6545.0
14,Garrett,3335.0,2827.0,2014.0,2146.0,5349.0,4973.0
15,Harford,1211.0,1145.0,2466.0,2165.0,3677.0,3310.0
16,Howard,738.0,741.0,1689.0,1286.0,2427.0,2027.0
17,Kent,1156.0,1144.0,2270.0,1949.0,3426.0,3093.0
18,Montgomery,1457.0,1378.0,3326.0,2507.0,4783.0,3885.0
19,Prince George’s,828.0,799.0,1560.0,1263.0,2388.0,2062.0
20,Queen Anne’s,1189.0,1133.0,2701.0,2060.0,3890.0,3193.0
21,Saint Mary’s,845.0,740.0,1847.0,1137.0,2692.0,1877.0
22,Somerset,NaN,NaN,NaN,NaN,NaN,NaN
23,whitetail,649.0,746.0,1540.0,1292.0,2189.0,2038.0
24,sika,2.0,11.0,7.0,5.0,9.0,16.0
25,Talbot,671.0,784.0,1830.0,1535.0,2501.0,2319.0
26,Washington,2135.0,2166.0,2458.0,2454.0,4593.0,4620.0
27,Wicomico,NaN,NaN,NaN,NaN,NaN,NaN
28,whitetail,952.0,1036.0,2275.0,1819.0,3227.0,2855.0
29,sika,85.0,110.0,83.0,81.0,168.0,191.0
30,Worcester,NaN,NaN,NaN,NaN,NaN,NaN
31,whitetail,1070.0,1148.0,2478.0,2158.0,3548.0,3306.0
32,sika,29.0,22.0,24.0,26.0,53.0,48.0
33,Total,31670.0,31308.0,54872.0,46074.0,86542.0,77382.0

In [49]:
#---------2018-2019 MORE CLEANING: COMBINING ALL SUMS FOR WHITETAIL AND SIKA FOR ALL APPLICABLE COUNTIES---------#

# #Dorchester
df_pmd_18_19.iloc[10, 1] = df_pmd_18_19.iloc[[11, 12], 1].sum()
df_pmd_18_19.iloc[10, 2] = df_pmd_18_19.iloc[[11,12], 2].sum()
df_pmd_18_19.iloc[10, 3] = df_pmd_18_19.iloc[[11, 12], 3].sum()
df_pmd_18_19.iloc[10, 4] = df_pmd_18_19.iloc[[11,12], 4].sum()
df_pmd_18_19.iloc[10, 5] = df_pmd_18_19.iloc[[11, 12], 5].sum()
df_pmd_18_19.iloc[10, 6] = df_pmd_18_19.iloc[[11,12], 6].sum()

# #Somerset
df_pmd_18_19.iloc[22, 1] = df_pmd_18_19.iloc[[23, 24], 1].sum()
df_pmd_18_19.iloc[22, 2] = df_pmd_18_19.iloc[[23,24], 2].sum()
df_pmd_18_19.iloc[22, 3] = df_pmd_18_19.iloc[[23, 24], 3].sum()
df_pmd_18_19.iloc[22, 4] = df_pmd_18_19.iloc[[23,24], 4].sum()
df_pmd_18_19.iloc[22, 5] = df_pmd_18_19.iloc[[23, 24], 5].sum()
df_pmd_18_19.iloc[22, 6] = df_pmd_18_19.iloc[[23,24], 6].sum()

# # #Wicomico
df_pmd_18_19.iloc[27, 1] = df_pmd_18_19.iloc[[28, 29], 1].sum()
df_pmd_18_19.iloc[27, 2] = df_pmd_18_19.iloc[[28,29], 2].sum()
df_pmd_18_19.iloc[27, 3] = df_pmd_18_19.iloc[[28, 29], 3].sum()
df_pmd_18_19.iloc[27, 4] = df_pmd_18_19.iloc[[28,29], 4].sum()
df_pmd_18_19.iloc[27, 5] = df_pmd_18_19.iloc[[28, 29], 5].sum()
df_pmd_18_19.iloc[27, 6] = df_pmd_18_19.iloc[[28,29], 6].sum()

# # #Worcester
df_pmd_18_19.iloc[30, 1] = df_pmd_18_19.iloc[[31, 32], 1].sum()
df_pmd_18_19.iloc[30, 2] = df_pmd_18_19.iloc[[31,32], 2].sum()
df_pmd_18_19.iloc[30, 3] = df_pmd_18_19.iloc[[31, 32], 3].sum()
df_pmd_18_19.iloc[30, 4] = df_pmd_18_19.iloc[[31,32], 4].sum()
df_pmd_18_19.iloc[30, 5] = df_pmd_18_19.iloc[[31, 32], 5].sum()
df_pmd_18_19.iloc[30, 6] = df_pmd_18_19.iloc[[31,32], 6].sum()

df_pmd_18_19

,County,Antlered_2017-18,Antlered_2018-19,Antlerless_2017-18,Antlerless_2018-19,Total_2017-18,Total_2018-19
0,Allegany,2078.0,2017.0,1283.0,1444.0,3361.0,3461.0
1,Anne Arundel,978.0,920.0,2001.0,1562.0,2979.0,2482.0
2,Baltimore,1754.0,1641.0,3805.0,2963.0,5559.0,4604.0
3,Calvert,558.0,614.0,1130.0,947.0,1688.0,1561.0
4,Caroline,757.0,829.0,1825.0,1728.0,2582.0,2557.0
5,whitetail,756.0,829.0,1824.0,1727.0,2580.0,2556.0
6,sika,1.0,0.0,1.0,1.0,2.0,1.0
7,Carroll,2116.0,2197.0,3780.0,3224.0,5896.0,5421.0
8,Cecil,1261.0,1237.0,2442.0,2269.0,3703.0,3506.0
9,Charles,1166.0,1031.0,2246.0,1328.0,3412.0,2359.0
10,Dorchester,1984.0,2200.0,3104.0,2873.0,5088.0,5073.0
11,whitetail,678.0,734.0,1482.0,1161.0,2160.0,1895.0
12,sika,1306.0,1466.0,1622.0,1712.0,2928.0,3178.0
13,Frederick,2666.0,2692.0,4688.0,3853.0,7354.0,6545.0
14,Garrett,3335.0,2827.0,2014.0,2146.0,5349.0,4973.0
15,Harford,1211.0,1145.0,2466.0,2165.0,3677.0,3310.0
16,Howard,738.0,741.0,1689.0,1286.0,2427.0,2027.0
17,Kent,1156.0,1144.0,2270.0,1949.0,3426.0,3093.0
18,Montgomery,1457.0,1378.0,3326.0,2507.0,4783.0,3885.0
19,Prince George’s,828.0,799.0,1560.0,1263.0,2388.0,2062.0
20,Queen Anne’s,1189.0,1133.0,2701.0,2060.0,3890.0,3193.0
21,Saint Mary’s,845.0,740.0,1847.0,1137.0,2692.0,1877.0
22,Somerset,651.0,757.0,1547.0,1297.0,2198.0,2054.0
23,whitetail,649.0,746.0,1540.0,1292.0,2189.0,2038.0
24,sika,2.0,11.0,7.0,5.0,9.0,16.0
25,Talbot,671.0,784.0,1830.0,1535.0,2501.0,2319.0
26,Washington,2135.0,2166.0,2458.0,2454.0,4593.0,4620.0
27,Wicomico,1037.0,1146.0,2358.0,1900.0,3395.0,3046.0
28,whitetail,952.0,1036.0,2275.0,1819.0,3227.0,2855.0
29,sika,85.0,110.0,83.0,81.0,168.0,191.0
30,Worcester,1099.0,1170.0,2502.0,2184.0,3601.0,3354.0
31,whitetail,1070.0,1148.0,2478.0,2158.0,3548.0,3306.0
32,sika,29.0,22.0,24.0,26.0,53.0,48.0
33,Total,31670.0,31308.0,54872.0,46074.0,86542.0,77382.0

In [50]:
#---------2018-2019 FINAL CLEANING: DROPPING ROWS---------#
#Filter county values for "whitetail" and "sika" and drop those rows
df_pmd_18_19=df_pmd_18_19[ df_pmd_18_19[ "County" ].str.contains( "whitetail|sika" )== False]
df_pmd_18_19 = df_pmd_18_19.reset_index(drop=True)
df_pmd_18_19.to_csv("df_pmd_18_19.csv")

In [51]:
#2017-2018 Processed Harvest Data Pt. 1

#PANDAS
df_pmd_17_18 = pd.read_html("https://news.maryland.gov/dnr/2018/02/15/maryland-hunters-harvest-86542-deer-in-2017-2018-season/", storage_options={"User-Agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0"})
df_pmd_17_18 = df_pmd_17_18[0]
#type(df_pmd_17_18)
df_pmd_18_19.to_csv("df_pmd_17_18.csv")

In [52]:
#2017-2018 Processed Harvest Data pt. 2 = COMBINING HEADERS

header_row_one_1718 = df_pmd_17_18.iloc[1]
header_row_two_1718 = df_pmd_17_18.iloc[2]

new_columns = []

for header_one, header_two in zip(header_row_one_1718, header_row_two_1718):
    if pd.isna(header_one):
    #https://pandas.pydata.org/docs/reference/api/pandas.isna.html 
        combined_header = header_two 
    else:
        combined_header = f"{header_one}_{header_two}"
    new_columns.append(combined_header)

#STORE NEW COMBINED HEADERS
df_pmd_17_18.columns = new_columns

#REPLACE OLD HEADERS WITH COMBINED
df_pmd_17_18 = df_pmd_17_18.iloc[3:]
df_pmd_17_18 = df_pmd_17_18.reset_index(drop=True)

df_pmd_17_18

#SAVE TO CSV (PROCESSED DATA FOLDER)
df_pmd_17_18.to_csv("df_pmd_17_18.csv")

In [53]:
#---------2017-2018 MORE CLEANING: REPLACING * , DROPPING LAST ROW, CHANGING DATATYPES, DROPPING % COLUMNS---------#

#FOR NULL COUNTY ROWS 

#1. Replace asterisks with NaN
df_pmd_17_18=df_pmd_17_18.replace(r'^\*$', np.nan, regex=True)
##https://stackoverflow.com/questions/45311262/replace-a-variable-number-of-asterisks-with-nan-in-a-dataframe 

#2. Drop last row, which just has "small sample size" text
df_pmd_17_18 = df_pmd_17_18.iloc[:-1]

#3. Change all datatypes (except those in county) to floats 
#found this on stack overflow to change datatypes of all but one column 

ignore = ['County']

#NEED TO SAVE THIS TO THE CURRENT DATAFRAME WITH DF=
df_pmd_17_18 = (df_pmd_17_18.set_index(ignore, append=True)
        .astype(float)
        .reset_index(ignore)
       )

# df_pmd_17_18.info()

#https://stackoverflow.com/questions/70893764/how-to-change-the-column-type-of-all-columns-except-the-first-in-pandas

#4.Drop percentage columns and then recalculate later 
df_pmd_17_18=df_pmd_17_18.drop(["Antlered_% Change", "Antlerless_% Change", "Total_% Change"], axis=1)

In [54]:
#---------2017-2018 MORE CLEANING: TEST TRIAL FOR COMBINING SUMS---------#
#5. Add whitetail and sika counts for each county manually, and then fill those sums into currently NaN county row 

#CAROLINE COUNTY
df_pmd_17_18.iloc[4, 1] = df_pmd_17_18.iloc[[5, 6], 1].sum()
df_pmd_17_18.iloc[4, 2] = df_pmd_17_18.iloc[[5,6], 2].sum()
df_pmd_17_18.iloc[4, 3] = df_pmd_17_18.iloc[[5, 6], 3].sum()
df_pmd_17_18.iloc[4, 4] = df_pmd_17_18.iloc[[5,6], 4].sum()
df_pmd_17_18.iloc[4, 5] = df_pmd_17_18.iloc[[5, 6], 5].sum()
df_pmd_17_18.iloc[4, 6] = df_pmd_17_18.iloc[[5,6], 6].sum()

df_pmd_17_18

,County,Antlered_’16-’17,Antlered_’17-’18,Antlerless_’16-’17,Antlerless_’17-’18,Total_’16-’17,Total_’17-’18
0,Allegany,1662.0,2078.0,1245.0,1283.0,2907.0,3361.0
1,Anne Arundel,900.0,978.0,1890.0,2001.0,2790.0,2979.0
2,Baltimore,1628.0,1754.0,3739.0,3805.0,5367.0,5559.0
3,Calvert,614.0,558.0,1253.0,1130.0,1867.0,1688.0
4,Caroline,918.0,757.0,2034.0,1825.0,2952.0,2582.0
5,whitetail,918.0,756.0,2033.0,1824.0,2951.0,2580.0
6,sika,0.0,1.0,1.0,1.0,1.0,2.0
7,Carroll,2002.0,2116.0,3661.0,3780.0,5663.0,5896.0
8,Cecil,1099.0,1261.0,2311.0,2442.0,3410.0,3703.0
9,Charles,1096.0,1166.0,2000.0,2246.0,3096.0,3412.0
10,Dorchester,NaN,NaN,NaN,NaN,NaN,NaN
11,whitetail,896.0,678.0,1820.0,1482.0,2716.0,2160.0
12,sika,1185.0,1306.0,1459.0,1622.0,2644.0,2928.0
13,Frederick,2680.0,2666.0,4876.0,4688.0,7556.0,7354.0
14,Garrett,2623.0,3335.0,1719.0,2014.0,4342.0,5349.0
15,Harford,1103.0,1211.0,2537.0,2466.0,3640.0,3677.0
16,Howard,685.0,738.0,1715.0,1689.0,2400.0,2427.0
17,Kent,1232.0,1156.0,2182.0,2270.0,3414.0,3426.0
18,Montgomery,1505.0,1457.0,3368.0,3326.0,4873.0,4783.0
19,Prince George’s,832.0,828.0,1645.0,1560.0,2477.0,2388.0
20,Queen Anne’s,1141.0,1189.0,2583.0,2701.0,3724.0,3890.0
21,Saint Mary’s,852.0,845.0,1760.0,1847.0,2612.0,2692.0
22,Somerset,NaN,NaN,NaN,NaN,NaN,NaN
23,whitetail,718.0,649.0,1598.0,1540.0,2316.0,2189.0
24,sika,5.0,2.0,2.0,7.0,7.0,9.0
25,Talbot,812.0,671.0,1981.0,1830.0,2793.0,2501.0
26,Washington,2062.0,2135.0,2674.0,2458.0,4736.0,4593.0
27,Wicomico,NaN,NaN,NaN,NaN,NaN,NaN
28,whitetail,931.0,952.0,2189.0,2275.0,3120.0,3227.0
29,sika,74.0,85.0,66.0,83.0,140.0,168.0
30,Worcester,NaN,NaN,NaN,NaN,NaN,NaN
31,whitetail,1051.0,1070.0,2539.0,2478.0,3590.0,3548.0
32,sika,20.0,29.0,21.0,24.0,41.0,53.0
33,Total,30326.0,31670.0,54867.0,54872.0,85193.0,86542.0

In [55]:
#---------2017-2018 MORE CLEANING: COMBINING ALL SUMS FOR WHITETAIL AND SIKA FOR ALL APPLICABLE COUNTIES---------#

# #Dorchester
df_pmd_17_18.iloc[10, 1] = df_pmd_17_18.iloc[[11, 12], 1].sum()
df_pmd_17_18.iloc[10, 2] = df_pmd_17_18.iloc[[11,12], 2].sum()
df_pmd_17_18.iloc[10, 3] = df_pmd_17_18.iloc[[11, 12], 3].sum()
df_pmd_17_18.iloc[10, 4] = df_pmd_17_18.iloc[[11,12], 4].sum()
df_pmd_17_18.iloc[10, 5] = df_pmd_17_18.iloc[[11, 12], 5].sum()
df_pmd_17_18.iloc[10, 6] = df_pmd_17_18.iloc[[11,12], 6].sum()

# #Somerset
df_pmd_17_18.iloc[22, 1] = df_pmd_17_18.iloc[[23, 24], 1].sum()
df_pmd_17_18.iloc[22, 2] = df_pmd_17_18.iloc[[23,24], 2].sum()
df_pmd_17_18.iloc[22, 3] = df_pmd_17_18.iloc[[23, 24], 3].sum()
df_pmd_17_18.iloc[22, 4] = df_pmd_17_18.iloc[[23,24], 4].sum()
df_pmd_17_18.iloc[22, 5] = df_pmd_17_18.iloc[[23, 24], 5].sum()
df_pmd_17_18.iloc[22, 6] = df_pmd_17_18.iloc[[23,24], 6].sum()

# # #Wicomico
df_pmd_17_18.iloc[27, 1] = df_pmd_17_18.iloc[[28, 29], 1].sum()
df_pmd_17_18.iloc[27, 2] = df_pmd_17_18.iloc[[28,29], 2].sum()
df_pmd_17_18.iloc[27, 3] = df_pmd_17_18.iloc[[28, 29], 3].sum()
df_pmd_17_18.iloc[27, 4] = df_pmd_17_18.iloc[[28,29], 4].sum()
df_pmd_17_18.iloc[27, 5] = df_pmd_17_18.iloc[[28, 29], 5].sum()
df_pmd_17_18.iloc[27, 6] = df_pmd_17_18.iloc[[28,29], 6].sum()

# # #Worcester
df_pmd_17_18.iloc[30, 1] = df_pmd_17_18.iloc[[31, 32], 1].sum()
df_pmd_17_18.iloc[30, 2] = df_pmd_17_18.iloc[[31,32], 2].sum()
df_pmd_17_18.iloc[30, 3] = df_pmd_17_18.iloc[[31, 32], 3].sum()
df_pmd_17_18.iloc[30, 4] = df_pmd_17_18.iloc[[31,32], 4].sum()
df_pmd_17_18.iloc[30, 5] = df_pmd_17_18.iloc[[31, 32], 5].sum()
df_pmd_17_18.iloc[30, 6] = df_pmd_17_18.iloc[[31,32], 6].sum()

df_pmd_17_18

,County,Antlered_’16-’17,Antlered_’17-’18,Antlerless_’16-’17,Antlerless_’17-’18,Total_’16-’17,Total_’17-’18
0,Allegany,1662.0,2078.0,1245.0,1283.0,2907.0,3361.0
1,Anne Arundel,900.0,978.0,1890.0,2001.0,2790.0,2979.0
2,Baltimore,1628.0,1754.0,3739.0,3805.0,5367.0,5559.0
3,Calvert,614.0,558.0,1253.0,1130.0,1867.0,1688.0
4,Caroline,918.0,757.0,2034.0,1825.0,2952.0,2582.0
5,whitetail,918.0,756.0,2033.0,1824.0,2951.0,2580.0
6,sika,0.0,1.0,1.0,1.0,1.0,2.0
7,Carroll,2002.0,2116.0,3661.0,3780.0,5663.0,5896.0
8,Cecil,1099.0,1261.0,2311.0,2442.0,3410.0,3703.0
9,Charles,1096.0,1166.0,2000.0,2246.0,3096.0,3412.0
10,Dorchester,2081.0,1984.0,3279.0,3104.0,5360.0,5088.0
11,whitetail,896.0,678.0,1820.0,1482.0,2716.0,2160.0
12,sika,1185.0,1306.0,1459.0,1622.0,2644.0,2928.0
13,Frederick,2680.0,2666.0,4876.0,4688.0,7556.0,7354.0
14,Garrett,2623.0,3335.0,1719.0,2014.0,4342.0,5349.0
15,Harford,1103.0,1211.0,2537.0,2466.0,3640.0,3677.0
16,Howard,685.0,738.0,1715.0,1689.0,2400.0,2427.0
17,Kent,1232.0,1156.0,2182.0,2270.0,3414.0,3426.0
18,Montgomery,1505.0,1457.0,3368.0,3326.0,4873.0,4783.0
19,Prince George’s,832.0,828.0,1645.0,1560.0,2477.0,2388.0
20,Queen Anne’s,1141.0,1189.0,2583.0,2701.0,3724.0,3890.0
21,Saint Mary’s,852.0,845.0,1760.0,1847.0,2612.0,2692.0
22,Somerset,723.0,651.0,1600.0,1547.0,2323.0,2198.0
23,whitetail,718.0,649.0,1598.0,1540.0,2316.0,2189.0
24,sika,5.0,2.0,2.0,7.0,7.0,9.0
25,Talbot,812.0,671.0,1981.0,1830.0,2793.0,2501.0
26,Washington,2062.0,2135.0,2674.0,2458.0,4736.0,4593.0
27,Wicomico,1005.0,1037.0,2255.0,2358.0,3260.0,3395.0
28,whitetail,931.0,952.0,2189.0,2275.0,3120.0,3227.0
29,sika,74.0,85.0,66.0,83.0,140.0,168.0
30,Worcester,1071.0,1099.0,2560.0,2502.0,3631.0,3601.0
31,whitetail,1051.0,1070.0,2539.0,2478.0,3590.0,3548.0
32,sika,20.0,29.0,21.0,24.0,41.0,53.0
33,Total,30326.0,31670.0,54867.0,54872.0,85193.0,86542.0

In [56]:
#---------2017-2018 FINAL CLEANING: DROPPING ROWS---------#
#Filter county values for "whitetail" and "sika" and drop those rows
df_pmd_17_18=df_pmd_17_18[ df_pmd_17_18[ "County" ].str.contains( "whitetail|sika" )== False]
df_pmd_17_18 = df_pmd_17_18.reset_index(drop=True)
df_pmd_17_18.to_csv("df_pmd_17_18.csv")

In [57]:
#2016-2017 Processed Harvest Data Pt. 1

#PANDAS
df_pmd_16_17 = pd.read_html("https://news.maryland.gov/dnr/2017/02/16/85193-deer-harvested-during-2016-2017-hunting-season/", storage_options={"User-Agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0"})
df_pmd_16_17 = df_pmd_16_17[0]
#type(df_pmd_16_17)
df_pmd_16_17.to_csv("df_pmd_16_17.csv")

In [58]:
#2016-2017 Processed Harvest Data pt. 2 = COMBINING HEADERS

header_row_one_1617 = df_pmd_16_17.iloc[1]
header_row_two_1617 = df_pmd_16_17.iloc[2]

new_columns = []

for header_one, header_two in zip(header_row_one_1617, header_row_two_1617):
    if pd.isna(header_one):
    #https://pandas.pydata.org/docs/reference/api/pandas.isna.html 
        combined_header = header_two 
    else:
        combined_header = f"{header_one}_{header_two}"
    new_columns.append(combined_header)

#STORE NEW COMBINED HEADERS
df_pmd_16_17.columns = new_columns

#REPLACE OLD HEADERS WITH COMBINED
df_pmd_16_17 = df_pmd_16_17.iloc[4:]
#this year's report formatted differently. Extra header row and a bunch of extra null columns 

df_pmd_16_17 = df_pmd_16_17.reset_index(drop=True)

df_pmd_16_17

,County,Antlered_nan,Antlered_2016-17,Antlered_% Change,NaN,Antlerless_nan,Antlerless_2016-17,Antlerless_% Change,NaN,Total_nan,Total_2016-17,Total_% Change,NaN
0,Allegany,NaN,1662,-16.2,NaN,NaN,1245,-10.0,NaN,NaN,2907,-13.7,NaN
1,Anne Arundel,NaN,900,2.0,NaN,NaN,1890,4.4,NaN,NaN,2790,3.6,NaN
2,Baltimore,NaN,1628,11.3,NaN,NaN,3739,6.6,NaN,NaN,5367,8.0,NaN
3,Calvert,NaN,614,4.8,NaN,NaN,1253,16.1,NaN,NaN,1867,12.1,NaN
4,Caroline,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,whitetail,NaN,918,13.5,NaN,NaN,2033,2.2,NaN,NaN,2951,5.5,NaN
6,sika,NaN,0,*,NaN,NaN,1,*,NaN,NaN,1,*,NaN
7,Carroll,NaN,2002,10.6,NaN,NaN,3661,6.8,NaN,NaN,5663,8.1,NaN
8,Cecil,NaN,1099,6.4,NaN,NaN,2311,10.3,NaN,NaN,3410,9.0,NaN
9,Charles,NaN,1096,2.2,NaN,NaN,2000,-2.5,NaN,NaN,3096,-0.9,NaN
10,Dorchester,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,whitetail,NaN,896,8.3,NaN,NaN,1820,7.9,NaN,NaN,2716,8.1,NaN
12,sika,NaN,1185,3.6,NaN,NaN,1459,-7.9,NaN,NaN,2644,-3.1,NaN
13,Frederick,NaN,2680,5.0,NaN,NaN,4876,6.1,NaN,NaN,7556,5.7,NaN
14,Garrett,NaN,2623,-1.3,NaN,NaN,1719,-1.8,NaN,NaN,4342,-1.5,NaN
15,Harford,NaN,1103,5.3,NaN,NaN,2537,4.6,NaN,NaN,3640,4.8,NaN
16,Howard,NaN,685,-2.3,NaN,NaN,1715,5.0,NaN,NaN,2400,2.8,NaN
17,Kent,NaN,1232,12.7,NaN,NaN,2182,5.7,NaN,NaN,3414,8.1,NaN
18,Montgomery,NaN,1505,7.4,NaN,NaN,3368,0.7,NaN,NaN,4873,2.7,NaN
19,Prince George’s,NaN,832,-1.5,NaN,NaN,1645,-1.3,NaN,NaN,2477,-1.4,NaN
20,Queen Anne’s,NaN,1141,-2.1,NaN,NaN,2583,2.6,NaN,NaN,3724,1.1,NaN
21,Saint Mary’s,NaN,852,-5.5,NaN,NaN,1760,-1.5,NaN,NaN,2612,-2.9,NaN
22,Somerset,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,whitetail,NaN,718,-1.2,NaN,NaN,1598,-11.8,NaN,NaN,2316,-8.7,NaN
24,sika,NaN,5,*,NaN,NaN,2,*,NaN,NaN,7,*,NaN
25,Talbot,NaN,812,-2.9,NaN,NaN,1981,-1.1,NaN,NaN,2793,-1.7,NaN
26,Washington,NaN,2062,-10.8,NaN,NaN,2674,-10.0,NaN,NaN,4736,-10.3,NaN
27,Wicomico,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,whitetail,NaN,931,4.6,NaN,NaN,2189,1.8,NaN,NaN,3120,2.6,NaN
29,sika,NaN,74,*,NaN,NaN,66,*,NaN,NaN,140,*,NaN
30,Worcester,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,whitetail,NaN,1051,2.7,NaN,NaN,2539,-6.9,NaN,NaN,3590,-4.3,NaN
32,sika,NaN,20,*,NaN,NaN,21,*,NaN,NaN,41,*,NaN
33,Total,NaN,30326,1.6,NaN,NaN,54867,1.3,NaN,NaN,85193,1.4,NaN
34,*Small sample size,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [59]:
#---------2016-2017 MORE CLEANING: REPLACING * , DROPPING LAST ROW, CHANGING DATATYPES, DROPPING % COLUMNS---------#

#FOR NULL COUNTY ROWS 

#1. Replace asterisks with NaN
df_pmd_16_17=df_pmd_16_17.replace(r'^\*$', np.nan, regex=True)
##https://stackoverflow.com/questions/45311262/replace-a-variable-number-of-asterisks-with-nan-in-a-dataframe 

#2. Drop last row, which just has "small sample size" text
df_pmd_16_17 = df_pmd_16_17.iloc[:-1]

#3. Change all datatypes (except those in county) to floats 
#found this on stack overflow to change datatypes of all but one column 

ignore = ['County']

#NEED TO SAVE THIS TO THE CURRENT DATAFRAME WITH DF=
df_pmd_16_17 = (df_pmd_16_17.set_index(ignore, append=True)
        .astype(float)
        .reset_index(ignore)
       )

df_pmd_16_17.columns

#https://stackoverflow.com/questions/70893764/how-to-change-the-column-type-of-all-columns-except-the-first-in-pandas

#4.Drop percentage columns and then recalculate later 
#This table had additional columns to drop. Here are all the ones that were dropped, or rather not kept: ['Antlered_nan',
#'Antlered_% Change', nan, 'Antlerless_nan', 'Antlerless_% Change', nan, 'Total_nan', 'Total_% Change', nan]

df_pmd_16_17=df_pmd_16_17.loc[:, ['County', 'Antlered_2016-17', 'Antlerless_2016-17', 'Total_2016-17']]
#this table doesn't inlude values from previous years like the later tables do 
df_pmd_16_17

             County  Antlered_2016-17  Antlerless_2016-17  Total_2016-17
0          Allegany            1662.0              1245.0         2907.0
1      Anne Arundel             900.0              1890.0         2790.0
2         Baltimore            1628.0              3739.0         5367.0
3           Calvert             614.0              1253.0         1867.0
4          Caroline               NaN                 NaN            NaN
5         whitetail             918.0              2033.0         2951.0
6              sika               0.0                 1.0            1.0
7           Carroll            2002.0              3661.0         5663.0
8             Cecil            1099.0              2311.0         3410.0
9           Charles            1096.0              2000.0         3096.0
10       Dorchester               NaN                 NaN            NaN
11        whitetail             896.0              1820.0         2716.0
12             sika            1185.0              1459.0         2644.0
13        Frederick            2680.0              4876.0         7556.0
14          Garrett            2623.0              1719.0         4342.0
15          Harford            1103.0              2537.0         3640.0
16           Howard             685.0              1715.0         2400.0
17             Kent            1232.0              2182.0         3414.0
18       Montgomery            1505.0              3368.0         4873.0
19  Prince George’s             832.0              1645.0         2477.0
20     Queen Anne’s            1141.0              2583.0         3724.0
21     Saint Mary’s             852.0              1760.0         2612.0
22         Somerset               NaN                 NaN            NaN
23        whitetail             718.0              1598.0         2316.0
24             sika               5.0                 2.0            7.0
25           Talbot             812.0              1981.0         2793.0
26       Washington            2062.0              2674.0         4736.0
27         Wicomico               NaN                 NaN            NaN
28        whitetail             931.0              2189.0         3120.0
29             sika              74.0                66.0          140.0
30        Worcester               NaN                 NaN            NaN
31        whitetail            1051.0              2539.0         3590.0
32             sika              20.0                21.0           41.0
33            Total           30326.0             54867.0        85193.0

In [60]:
#---------2016-2017 MORE CLEANING: TEST TRIAL FOR COMBINING SUMS---------#
#5. Add whitetail and sika counts for each county manually, and then fill those sums into currently NaN county row 

#CAROLINE COUNTY
df_pmd_16_17.iloc[4, 1] = df_pmd_16_17.iloc[[5, 6], 1].sum()
df_pmd_16_17.iloc[4, 2] = df_pmd_16_17.iloc[[5,6], 2].sum()
df_pmd_16_17.iloc[4, 3] = df_pmd_16_17.iloc[[5, 6], 3].sum()

df_pmd_16_17

             County  Antlered_2016-17  Antlerless_2016-17  Total_2016-17
0          Allegany            1662.0              1245.0         2907.0
1      Anne Arundel             900.0              1890.0         2790.0
2         Baltimore            1628.0              3739.0         5367.0
3           Calvert             614.0              1253.0         1867.0
4          Caroline             918.0              2034.0         2952.0
5         whitetail             918.0              2033.0         2951.0
6              sika               0.0                 1.0            1.0
7           Carroll            2002.0              3661.0         5663.0
8             Cecil            1099.0              2311.0         3410.0
9           Charles            1096.0              2000.0         3096.0
10       Dorchester               NaN                 NaN            NaN
11        whitetail             896.0              1820.0         2716.0
12             sika            1185.0              1459.0         2644.0
13        Frederick            2680.0              4876.0         7556.0
14          Garrett            2623.0              1719.0         4342.0
15          Harford            1103.0              2537.0         3640.0
16           Howard             685.0              1715.0         2400.0
17             Kent            1232.0              2182.0         3414.0
18       Montgomery            1505.0              3368.0         4873.0
19  Prince George’s             832.0              1645.0         2477.0
20     Queen Anne’s            1141.0              2583.0         3724.0
21     Saint Mary’s             852.0              1760.0         2612.0
22         Somerset               NaN                 NaN            NaN
23        whitetail             718.0              1598.0         2316.0
24             sika               5.0                 2.0            7.0
25           Talbot             812.0              1981.0         2793.0
26       Washington            2062.0              2674.0         4736.0
27         Wicomico               NaN                 NaN            NaN
28        whitetail             931.0              2189.0         3120.0
29             sika              74.0                66.0          140.0
30        Worcester               NaN                 NaN            NaN
31        whitetail            1051.0              2539.0         3590.0
32             sika              20.0                21.0           41.0
33            Total           30326.0             54867.0        85193.0

In [61]:
#---------2016-2017 MORE CLEANING: COMBINING ALL SUMS FOR WHITETAIL AND SIKA FOR ALL APPLICABLE COUNTIES---------#

# #Dorchester
df_pmd_16_17.iloc[10, 1] = df_pmd_16_17.iloc[[11, 12], 1].sum()
df_pmd_16_17.iloc[10, 2] = df_pmd_16_17.iloc[[11,12], 2].sum()
df_pmd_16_17.iloc[10, 3] = df_pmd_16_17.iloc[[11, 12], 3].sum()

# #Somerset
df_pmd_16_17.iloc[22, 1] = df_pmd_16_17.iloc[[23, 24], 1].sum()
df_pmd_16_17.iloc[22, 2] = df_pmd_16_17.iloc[[23,24], 2].sum()
df_pmd_16_17.iloc[22, 3] = df_pmd_16_17.iloc[[23, 24], 3].sum()

# # #Wicomico
df_pmd_16_17.iloc[27, 1] = df_pmd_16_17.iloc[[28, 29], 1].sum()
df_pmd_16_17.iloc[27, 2] = df_pmd_16_17.iloc[[28,29], 2].sum()
df_pmd_16_17.iloc[27, 3] = df_pmd_16_17.iloc[[28, 29], 3].sum()

# # #Worcester
df_pmd_16_17.iloc[30, 1] = df_pmd_16_17.iloc[[31, 32], 1].sum()
df_pmd_16_17.iloc[30, 2] = df_pmd_16_17.iloc[[31,32], 2].sum()
df_pmd_16_17.iloc[30, 3] = df_pmd_16_17.iloc[[31, 32], 3].sum()

df_pmd_16_17

             County  Antlered_2016-17  Antlerless_2016-17  Total_2016-17
0          Allegany            1662.0              1245.0         2907.0
1      Anne Arundel             900.0              1890.0         2790.0
2         Baltimore            1628.0              3739.0         5367.0
3           Calvert             614.0              1253.0         1867.0
4          Caroline             918.0              2034.0         2952.0
5         whitetail             918.0              2033.0         2951.0
6              sika               0.0                 1.0            1.0
7           Carroll            2002.0              3661.0         5663.0
8             Cecil            1099.0              2311.0         3410.0
9           Charles            1096.0              2000.0         3096.0
10       Dorchester            2081.0              3279.0         5360.0
11        whitetail             896.0              1820.0         2716.0
12             sika            1185.0              1459.0         2644.0
13        Frederick            2680.0              4876.0         7556.0
14          Garrett            2623.0              1719.0         4342.0
15          Harford            1103.0              2537.0         3640.0
16           Howard             685.0              1715.0         2400.0
17             Kent            1232.0              2182.0         3414.0
18       Montgomery            1505.0              3368.0         4873.0
19  Prince George’s             832.0              1645.0         2477.0
20     Queen Anne’s            1141.0              2583.0         3724.0
21     Saint Mary’s             852.0              1760.0         2612.0
22         Somerset             723.0              1600.0         2323.0
23        whitetail             718.0              1598.0         2316.0
24             sika               5.0                 2.0            7.0
25           Talbot             812.0              1981.0         2793.0
26       Washington            2062.0              2674.0         4736.0
27         Wicomico            1005.0              2255.0         3260.0
28        whitetail             931.0              2189.0         3120.0
29             sika              74.0                66.0          140.0
30        Worcester            1071.0              2560.0         3631.0
31        whitetail            1051.0              2539.0         3590.0
32             sika              20.0                21.0           41.0
33            Total           30326.0             54867.0        85193.0

In [62]:
#---------2016-2017 FINAL CLEANING: DROPPING ROWS---------#
#Filter county values for "whitetail" and "sika" and drop those rows
df_pmd_16_17=df_pmd_16_17[ df_pmd_16_17[ "County" ].str.contains( "whitetail|sika" )== False]
df_pmd_16_17 = df_pmd_16_17.reset_index(drop=True)
df_pmd_16_17.to_csv("df_pmd_16_17.csv")

In [63]:
#2015-2016 Processed Harvest Data Pt. 1

#PANDAS
df_pmd_15_16 = pd.read_html("https://news.maryland.gov/dnr/2016/02/09/84022-deer-harvested-in-maryland-during-2015-2016-hunting-season/", storage_options={"User-Agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0"})
df_pmd_15_16 = df_pmd_15_16[0]
#type(df_pmd_15_16)
df_pmd_15_16.to_csv("df_pmd_15_16.csv")

In [64]:
#2015-2016 Processed Harvest Data pt. 2 = COMBINING HEADERS

header_row_one_1516 = df_pmd_15_16.iloc[1]
header_row_two_1516 = df_pmd_15_16.iloc[2]

new_columns = []

for header_one, header_two in zip(header_row_one_1516, header_row_two_1516):
    if pd.isna(header_one):
    #https://pandas.pydata.org/docs/reference/api/pandas.isna.html 
        combined_header = header_two 
    else:
        combined_header = f"{header_one}_{header_two}"
    new_columns.append(combined_header)

#STORE NEW COMBINED HEADERS
df_pmd_15_16.columns = new_columns

#REPLACE OLD HEADERS WITH COMBINED
df_pmd_15_16 = df_pmd_15_16.iloc[4:]
df_pmd_15_16 = df_pmd_15_16.reset_index(drop=True)

df_pmd_15_16

,County,Antlered_2014-15,Antlered_2015-16,Antlered_% Change,NaN,Antlerless_2014-15,Antlerless_2015-16,Antlerless_% Change,NaN,Total_2014-15,Total_2015-16,Total_% Change,NaN
0,Allegany,1731,1984,14.6,NaN,1320,1384,4.8,NaN,3051,3368,10.4,NaN
1,Anne Arundel,817,882,8.0,NaN,2075,1810,-12.8,NaN,2892,2692,-6.9,NaN
2,Baltimore,1502,1463,-2.6,NaN,3911,3507,-10.3,NaN,5413,4970,-8.2,NaN
3,Calvert,470,586,24.7,NaN,1101,1079,-2.0,NaN,1571,1665,6.0,NaN
4,Caroline,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,whitetail,734,809,10.2,NaN,1704,1989,16.7,NaN,2438,2798,14.8,NaN
6,sika,1,0,*,NaN,1,2,*,NaN,2,2,*,NaN
7,Carroll,1634,1810,10.8,NaN,3830,3428,-10.5,NaN,5464,5238,-4.1,NaN
8,Cecil,1005,1033,2.8,NaN,2455,2095,-14.7,NaN,3460,3128,-9.6,NaN
9,Charles,1132,1072,-5.3,NaN,2392,2051,-14.3,NaN,3524,3123,-11.4,NaN
10,Dorchester,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,whitetail,774,827,6.8,NaN,1865,1686,-9.6,NaN,2639,2513,-4.8,NaN
12,sika,1140,1144,0.4,NaN,1707,1584,-7.2,NaN,2847,2728,-4.2,NaN
13,Frederick,2346,2553,8.8,NaN,4926,4596,-6.7,NaN,7272,7149,-1.7,NaN
14,Garrett,2486,2658,6.9,NaN,1967,1750,-11.0,NaN,4453,4408,-1.0,NaN
15,Harford,1038,1047,0.9,NaN,2660,2425,-8.8,NaN,3698,3472,-6.1,NaN
16,Howard,682,701,2.8,NaN,1899,1633,-14.0,NaN,2581,2334,-9.6,NaN
17,Kent,1052,1093,3.9,NaN,2268,2064,-9.0,NaN,3320,3157,-4.9,NaN
18,Montgomery,1520,1401,-7.8,NaN,3890,3343,-14.1,NaN,5410,4744,-12.3,NaN
19,Prince George’s,820,845,3.0,NaN,1848,1667,-9.8,NaN,2668,2512,-5.8,NaN
20,Queen Anne’s,1096,1166,6.4,NaN,2731,2517,-7.8,NaN,3827,3683,-3.8,NaN
21,Saint Mary’s,848,902,6.4,NaN,1929,1787,-7.4,NaN,2777,2689,-3.2,NaN
22,Somerset,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,whitetail,665,727,9.3,NaN,1826,1811,-0.8,NaN,2491,2538,1.9,NaN
24,sika,1,5,*,NaN,6,5,*,NaN,7,10,*,NaN
25,Talbot,774,836,8.0,NaN,2087,2004,-4.0,NaN,2861,2840,-0.7,NaN
26,Washington,2026,2311,14.1,NaN,3061,2971,-2.9,NaN,5087,5282,3.8,NaN
27,Wicomico,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,whitetail,886,890,0.5,NaN,2248,2151,-4.3,NaN,3134,3041,-3.0,NaN
29,sika,62,57,*,NaN,50,60,*,NaN,112,117,*,NaN
30,Worcester,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,whitetail,1015,1023,0.8,NaN,2809,2728,-2.9,NaN,3824,3751,-1.9,NaN
32,sika,24,30,*,NaN,36,40,*,NaN,60,70,*,NaN
33,Total,28281,29855,5.6,NaN,58602,54167,-7.6,NaN,86883,84022,-3.3,NaN
34,*Small sample size,*Small sample size,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [65]:
#---------2015-2016 MORE CLEANING: REPLACING * , DROPPING LAST ROW, CHANGING DATATYPES, DROPPING % COLUMNS---------#

#FOR NULL COUNTY ROWS 

#1. Replace asterisks with NaN
df_pmd_15_16=df_pmd_15_16.replace(r'^\*$', np.nan, regex=True)
##https://stackoverflow.com/questions/45311262/replace-a-variable-number-of-asterisks-with-nan-in-a-dataframe 

#2. Drop last row, which just has "small sample size" text
df_pmd_15_16 = df_pmd_15_16.iloc[:-1]

#3. Change all datatypes (except those in county) to floats 
#found this on stack overflow to change datatypes of all but one column 

ignore = ['County']

#NEED TO SAVE THIS TO THE CURRENT DATAFRAME WITH DF=
df_pmd_15_16 = (df_pmd_15_16.set_index(ignore, append=True)
        .astype(float)
        .reset_index(ignore)
       )

# #https://stackoverflow.com/questions/70893764/how-to-change-the-column-type-of-all-columns-except-the-first-in-pandas

#df_pmd_15_16.columns

    #Index(['County', 'Antlered_2014-15', 'Antlered_2015-16', 'Antlered_% Change',
          #  nan, 'Antlerless_2014-15', 'Antlerless_2015-16', 'Antlerless_% Change',
          #  nan, 'Total_2014-15', 'Total_2015-16', 'Total_% Change', nan]

#4.Drop percentage columns and then recalculate later 
#This table had additional columns to drop. Here are all the ones that were dropped, or rather not kept: ['Antlered_% Change',
          #  nan, 'Antlerless_% Change', nan, Total_% Change', nan]

df_pmd_15_16=df_pmd_15_16.loc[:, ['County', 'Antlered_2014-15', 'Antlered_2015-16', 'Antlerless_2014-15', 'Antlerless_2015-16', 
                                  'Total_2014-15', 'Total_2015-16']] 
df_pmd_15_16

,County,Antlered_2014-15,Antlered_2015-16,Antlerless_2014-15,Antlerless_2015-16,Total_2014-15,Total_2015-16
0,Allegany,1731.0,1984.0,1320.0,1384.0,3051.0,3368.0
1,Anne Arundel,817.0,882.0,2075.0,1810.0,2892.0,2692.0
2,Baltimore,1502.0,1463.0,3911.0,3507.0,5413.0,4970.0
3,Calvert,470.0,586.0,1101.0,1079.0,1571.0,1665.0
4,Caroline,NaN,NaN,NaN,NaN,NaN,NaN
5,whitetail,734.0,809.0,1704.0,1989.0,2438.0,2798.0
6,sika,1.0,0.0,1.0,2.0,2.0,2.0
7,Carroll,1634.0,1810.0,3830.0,3428.0,5464.0,5238.0
8,Cecil,1005.0,1033.0,2455.0,2095.0,3460.0,3128.0
9,Charles,1132.0,1072.0,2392.0,2051.0,3524.0,3123.0
10,Dorchester,NaN,NaN,NaN,NaN,NaN,NaN
11,whitetail,774.0,827.0,1865.0,1686.0,2639.0,2513.0
12,sika,1140.0,1144.0,1707.0,1584.0,2847.0,2728.0
13,Frederick,2346.0,2553.0,4926.0,4596.0,7272.0,7149.0
14,Garrett,2486.0,2658.0,1967.0,1750.0,4453.0,4408.0
15,Harford,1038.0,1047.0,2660.0,2425.0,3698.0,3472.0
16,Howard,682.0,701.0,1899.0,1633.0,2581.0,2334.0
17,Kent,1052.0,1093.0,2268.0,2064.0,3320.0,3157.0
18,Montgomery,1520.0,1401.0,3890.0,3343.0,5410.0,4744.0
19,Prince George’s,820.0,845.0,1848.0,1667.0,2668.0,2512.0
20,Queen Anne’s,1096.0,1166.0,2731.0,2517.0,3827.0,3683.0
21,Saint Mary’s,848.0,902.0,1929.0,1787.0,2777.0,2689.0
22,Somerset,NaN,NaN,NaN,NaN,NaN,NaN
23,whitetail,665.0,727.0,1826.0,1811.0,2491.0,2538.0
24,sika,1.0,5.0,6.0,5.0,7.0,10.0
25,Talbot,774.0,836.0,2087.0,2004.0,2861.0,2840.0
26,Washington,2026.0,2311.0,3061.0,2971.0,5087.0,5282.0
27,Wicomico,NaN,NaN,NaN,NaN,NaN,NaN
28,whitetail,886.0,890.0,2248.0,2151.0,3134.0,3041.0
29,sika,62.0,57.0,50.0,60.0,112.0,117.0
30,Worcester,NaN,NaN,NaN,NaN,NaN,NaN
31,whitetail,1015.0,1023.0,2809.0,2728.0,3824.0,3751.0
32,sika,24.0,30.0,36.0,40.0,60.0,70.0
33,Total,28281.0,29855.0,58602.0,54167.0,86883.0,84022.0

In [66]:
#---------2015-2016 MORE CLEANING: TEST TRIAL FOR COMBINING SUMS---------#
#5. Add whitetail and sika counts for each county manually, and then fill those sums into currently NaN county row 

#CAROLINE COUNTY
df_pmd_15_16.iloc[4, 1] = df_pmd_15_16.iloc[[5, 6], 1].sum()
df_pmd_15_16.iloc[4, 2] = df_pmd_15_16.iloc[[5,6], 2].sum()
df_pmd_15_16.iloc[4, 3] = df_pmd_15_16.iloc[[5, 6], 3].sum()
df_pmd_15_16.iloc[4, 4] = df_pmd_15_16.iloc[[5,6], 4].sum()
df_pmd_15_16.iloc[4, 5] = df_pmd_15_16.iloc[[5, 6], 5].sum()
df_pmd_15_16.iloc[4, 6] = df_pmd_15_16.iloc[[5,6], 6].sum()

df_pmd_15_16

,County,Antlered_2014-15,Antlered_2015-16,Antlerless_2014-15,Antlerless_2015-16,Total_2014-15,Total_2015-16
0,Allegany,1731.0,1984.0,1320.0,1384.0,3051.0,3368.0
1,Anne Arundel,817.0,882.0,2075.0,1810.0,2892.0,2692.0
2,Baltimore,1502.0,1463.0,3911.0,3507.0,5413.0,4970.0
3,Calvert,470.0,586.0,1101.0,1079.0,1571.0,1665.0
4,Caroline,735.0,809.0,1705.0,1991.0,2440.0,2800.0
5,whitetail,734.0,809.0,1704.0,1989.0,2438.0,2798.0
6,sika,1.0,0.0,1.0,2.0,2.0,2.0
7,Carroll,1634.0,1810.0,3830.0,3428.0,5464.0,5238.0
8,Cecil,1005.0,1033.0,2455.0,2095.0,3460.0,3128.0
9,Charles,1132.0,1072.0,2392.0,2051.0,3524.0,3123.0
10,Dorchester,NaN,NaN,NaN,NaN,NaN,NaN
11,whitetail,774.0,827.0,1865.0,1686.0,2639.0,2513.0
12,sika,1140.0,1144.0,1707.0,1584.0,2847.0,2728.0
13,Frederick,2346.0,2553.0,4926.0,4596.0,7272.0,7149.0
14,Garrett,2486.0,2658.0,1967.0,1750.0,4453.0,4408.0
15,Harford,1038.0,1047.0,2660.0,2425.0,3698.0,3472.0
16,Howard,682.0,701.0,1899.0,1633.0,2581.0,2334.0
17,Kent,1052.0,1093.0,2268.0,2064.0,3320.0,3157.0
18,Montgomery,1520.0,1401.0,3890.0,3343.0,5410.0,4744.0
19,Prince George’s,820.0,845.0,1848.0,1667.0,2668.0,2512.0
20,Queen Anne’s,1096.0,1166.0,2731.0,2517.0,3827.0,3683.0
21,Saint Mary’s,848.0,902.0,1929.0,1787.0,2777.0,2689.0
22,Somerset,NaN,NaN,NaN,NaN,NaN,NaN
23,whitetail,665.0,727.0,1826.0,1811.0,2491.0,2538.0
24,sika,1.0,5.0,6.0,5.0,7.0,10.0
25,Talbot,774.0,836.0,2087.0,2004.0,2861.0,2840.0
26,Washington,2026.0,2311.0,3061.0,2971.0,5087.0,5282.0
27,Wicomico,NaN,NaN,NaN,NaN,NaN,NaN
28,whitetail,886.0,890.0,2248.0,2151.0,3134.0,3041.0
29,sika,62.0,57.0,50.0,60.0,112.0,117.0
30,Worcester,NaN,NaN,NaN,NaN,NaN,NaN
31,whitetail,1015.0,1023.0,2809.0,2728.0,3824.0,3751.0
32,sika,24.0,30.0,36.0,40.0,60.0,70.0
33,Total,28281.0,29855.0,58602.0,54167.0,86883.0,84022.0

In [67]:
#---------2015-2016 MORE CLEANING: COMBINING ALL SUMS FOR WHITETAIL AND SIKA FOR ALL APPLICABLE COUNTIES---------#

# #Dorchester
df_pmd_15_16.iloc[10, 1] = df_pmd_15_16.iloc[[11, 12], 1].sum()
df_pmd_15_16.iloc[10, 2] = df_pmd_15_16.iloc[[11,12], 2].sum()
df_pmd_15_16.iloc[10, 3] = df_pmd_15_16.iloc[[11, 12], 3].sum()
df_pmd_15_16.iloc[10, 4] = df_pmd_15_16.iloc[[11,12], 4].sum()
df_pmd_15_16.iloc[10, 5] = df_pmd_15_16.iloc[[11, 12], 5].sum()
df_pmd_15_16.iloc[10, 6] = df_pmd_15_16.iloc[[11,12], 6].sum()

# #Somerset
df_pmd_15_16.iloc[22, 1] = df_pmd_15_16.iloc[[23, 24], 1].sum()
df_pmd_15_16.iloc[22, 2] = df_pmd_15_16.iloc[[23,24], 2].sum()
df_pmd_15_16.iloc[22, 3] = df_pmd_15_16.iloc[[23, 24], 3].sum()
df_pmd_15_16.iloc[22, 4] = df_pmd_15_16.iloc[[23,24], 4].sum()
df_pmd_15_16.iloc[22, 5] = df_pmd_15_16.iloc[[23, 24], 5].sum()
df_pmd_15_16.iloc[22, 6] = df_pmd_15_16.iloc[[23,24], 6].sum()

# # #Wicomico
df_pmd_15_16.iloc[27, 1] = df_pmd_15_16.iloc[[28, 29], 1].sum()
df_pmd_15_16.iloc[27, 2] = df_pmd_15_16.iloc[[28,29], 2].sum()
df_pmd_15_16.iloc[27, 3] = df_pmd_15_16.iloc[[28, 29], 3].sum()
df_pmd_15_16.iloc[27, 4] = df_pmd_15_16.iloc[[28,29], 4].sum()
df_pmd_15_16.iloc[27, 5] = df_pmd_15_16.iloc[[28, 29], 5].sum()
df_pmd_15_16.iloc[27, 6] = df_pmd_15_16.iloc[[28,29], 6].sum()

# # #Worcester
df_pmd_15_16.iloc[30, 1] = df_pmd_15_16.iloc[[31, 32], 1].sum()
df_pmd_15_16.iloc[30, 2] = df_pmd_15_16.iloc[[31,32], 2].sum()
df_pmd_15_16.iloc[30, 3] = df_pmd_15_16.iloc[[31, 32], 3].sum()
df_pmd_15_16.iloc[30, 4] = df_pmd_15_16.iloc[[31,32], 4].sum()
df_pmd_15_16.iloc[30, 5] = df_pmd_15_16.iloc[[31, 32], 5].sum()
df_pmd_15_16.iloc[30, 6] = df_pmd_15_16.iloc[[31,32], 6].sum()

df_pmd_15_16

,County,Antlered_2014-15,Antlered_2015-16,Antlerless_2014-15,Antlerless_2015-16,Total_2014-15,Total_2015-16
0,Allegany,1731.0,1984.0,1320.0,1384.0,3051.0,3368.0
1,Anne Arundel,817.0,882.0,2075.0,1810.0,2892.0,2692.0
2,Baltimore,1502.0,1463.0,3911.0,3507.0,5413.0,4970.0
3,Calvert,470.0,586.0,1101.0,1079.0,1571.0,1665.0
4,Caroline,735.0,809.0,1705.0,1991.0,2440.0,2800.0
5,whitetail,734.0,809.0,1704.0,1989.0,2438.0,2798.0
6,sika,1.0,0.0,1.0,2.0,2.0,2.0
7,Carroll,1634.0,1810.0,3830.0,3428.0,5464.0,5238.0
8,Cecil,1005.0,1033.0,2455.0,2095.0,3460.0,3128.0
9,Charles,1132.0,1072.0,2392.0,2051.0,3524.0,3123.0
10,Dorchester,1914.0,1971.0,3572.0,3270.0,5486.0,5241.0
11,whitetail,774.0,827.0,1865.0,1686.0,2639.0,2513.0
12,sika,1140.0,1144.0,1707.0,1584.0,2847.0,2728.0
13,Frederick,2346.0,2553.0,4926.0,4596.0,7272.0,7149.0
14,Garrett,2486.0,2658.0,1967.0,1750.0,4453.0,4408.0
15,Harford,1038.0,1047.0,2660.0,2425.0,3698.0,3472.0
16,Howard,682.0,701.0,1899.0,1633.0,2581.0,2334.0
17,Kent,1052.0,1093.0,2268.0,2064.0,3320.0,3157.0
18,Montgomery,1520.0,1401.0,3890.0,3343.0,5410.0,4744.0
19,Prince George’s,820.0,845.0,1848.0,1667.0,2668.0,2512.0
20,Queen Anne’s,1096.0,1166.0,2731.0,2517.0,3827.0,3683.0
21,Saint Mary’s,848.0,902.0,1929.0,1787.0,2777.0,2689.0
22,Somerset,666.0,732.0,1832.0,1816.0,2498.0,2548.0
23,whitetail,665.0,727.0,1826.0,1811.0,2491.0,2538.0
24,sika,1.0,5.0,6.0,5.0,7.0,10.0
25,Talbot,774.0,836.0,2087.0,2004.0,2861.0,2840.0
26,Washington,2026.0,2311.0,3061.0,2971.0,5087.0,5282.0
27,Wicomico,948.0,947.0,2298.0,2211.0,3246.0,3158.0
28,whitetail,886.0,890.0,2248.0,2151.0,3134.0,3041.0
29,sika,62.0,57.0,50.0,60.0,112.0,117.0
30,Worcester,1039.0,1053.0,2845.0,2768.0,3884.0,3821.0
31,whitetail,1015.0,1023.0,2809.0,2728.0,3824.0,3751.0
32,sika,24.0,30.0,36.0,40.0,60.0,70.0
33,Total,28281.0,29855.0,58602.0,54167.0,86883.0,84022.0

In [68]:
#---------2015-2016 FINAL CLEANING: DROPPING ROWS---------#
#Filter county values for "whitetail" and "sika" and drop those rows and reset index
df_pmd_15_16=df_pmd_15_16[ df_pmd_15_16[ "County" ].str.contains( "whitetail|sika" )== False]
df_pmd_15_16= df_pmd_15_16.reset_index(drop=True)
df_pmd_15_16.to_csv("df_pmd_15_16.csv")

In [164]:
#---------COMBINE THROUGH CONCAT, STANDARDIZE LABELS, DOUBLE-CHECK FOR CONSISTENT SPELLING OF COUNTY NAMES---------#

df_combined_harvest = pd.concat([df_pmd_15_16, df_pmd_16_17, df_pmd_17_18, df_pmd_18_19, df_pmd_19_20,
           df_pmd_20_21, df_pmd_21_22, df_pmd_22_23, df_pmd_23_24, df_pmd_24_25, df_pmd_25_26])

df_combined_harvest.columns

#COLUMN LABELS:
    #County
    #Antlered_2014-15
    #Antlerless_2014-15
    #Total_2014-15

#RENAME COLUMNS AS NEEDED TO FOLLOW CONVENTION ABOVE:
#https://www.geeksforgeeks.org/python/how-to-rename-multiple-column-headers-in-a-pandas-dataframe/
# create a dictionary
# key = old name
# value = new name
dict = {'Antlered_’16-’17': 'Antlered_2016-17',
        'Antlered_’17-’18': 'Antlered_2017-18',
        'Antlerless_’16-’17': 'Antlerless_2016-17',
        'Antlerless_’17-’18': 'Antlerless_2017-18',
        'Total_’16-’17': 'Total_2016-17',
        'Total_’17-’18': 'Total_2017-18',
       }
df_combined_harvest.rename(columns=dict,
          inplace=True)
df_combined_harvest.to_csv("df_combined_harvest.csv", index=False)

In [166]:
#DROP "TOTAL" ROWS
df_combined_harvest=df_combined_harvest[ df_combined_harvest[ "County" ].str.contains( "Total" )== False]
df_combined_harvest = df_combined_harvest.reset_index(drop=True)
df_combined_harvest.to_csv("df_combined_harvest.csv", index=False)

In [70]:
# Create population DF based on list of estimated deer population from DNR, Carson Coriell

import csv

md_deer_pop_est_15_25_fromCarson = [236921, 242761, 251609, 223745, 239444, 246919, 264760, 270118, 261832, 268863]

# Column headers
fields = ['Hunting_Season', 'Est_Deer_Population']

# Data rows
rows = [ ['2015-16', '236921'],
         ['2016-17', '242761'],
         ['2017-18', '251609'],
         ['2018-19', '223745'],
         ['2019-20', '239444'],
         ['2020-21', '246919'],
         ['2021-22', '264760'],
         ['2022-23', '270118'],
         ['2023-24', '261832'],
         ['2024-25', '268863'],
         ['2025-26', '268863']
       ]

# Writing to a CSV file
with open('md_deer_pop_est_15_25_fromCarson', 'w', newline='') as f:
    writer = csv.writer(f)
    writer.writerow(fields)     # Write header
    writer.writerows(rows)      # Write data rows
    
md_deer_pop_est_15_25_fromCarson = pd.read_csv("md_deer_pop_est_15_25_fromCarson")

# 10-yr White-tail Pop. Estimates
# Year	Population Estimate     
# 2015	236,921
# 2016	242,761
# 2017	251,609
# 2018	223,745
# 2019	239,444
# 2020	246,919
# 2021	264,760
# 2022	270,118
# 2023	261,832
# 2024	268,863

md_deer_pop_est_15_25_fromCarson.to_csv("md_deer_pop_est_15_25_fromCarson.csv")

In [72]:
# #--------Steps to clean button buck and doe harvest numbers--------#

# #1. FORMAT OF COUNTY NAMES:
#     #strip \n
#     #Anne Arundel
#     #Prince George's 
#     #Queen Anne's

# #2. Replace asterisks with NaN
# # df_pmd_22_23=df_pmd_22_23.replace(r'^\*$', np.nan, regex=True)
# ##https://stackoverflow.com/questions/45311262/replace-a-variable-number-of-asterisks-with-nan-in-a-dataframe 

# #3. Drop last row, which just has "small sample size" text
# #df_pmd_22_23 = df_pmd_22_23.iloc[:-1]

# #4. Change all datatypes (except those in county) to floats 
# #found this on stack overflow to change datatypes of all but one column 

# ignore = ['County']

# #NEED TO SAVE THIS TO THE CURRENT DATAFRAME WITH DF=
# # df_pmd_22_23 = (df_pmd_22_23.set_index(ignore, append=True)
# #         .astype(float)
# #         .reset_index(ignore)
# #        )

# # df_pmd_22_23.info()

# #https://stackoverflow.com/questions/70893764/how-to-change-the-column-type-of-all-columns-except-the-first-in-pandas

# #5. Rename columns
#     #County
#     #Buttonbuck_2015-16
#     #Female_or_Antlerless_2015-16
#     #Total_2015-16

# #6. Drop percent in buttonbuck
# df_pmd_22_23=df_pmd_22_23.drop(["Antlered_% Change", "Antlerless_% Change", "Total_% Change"], axis=1)

In [73]:
#2015-2016 Button buck and doe harvest 

from natural_pdf import PDF

# Open a PDF
pdf = PDF('md_annual_deer_report15-16.pdf')
#had to download PDF bc of 403 error 
page = pdf.pages[11]
page.show(width=700)

table = page.extract_table(method="pdfplumber")
list(table)

import pandas as pd

rows = list(table)

df_pbutton_15_16 = pd.DataFrame(rows)

df_pbutton_15_16.to_csv("df_pbutton_15_16.csv", index=False)

In [74]:
#--------2015-2016 Button Buck and Doe Harvest Cleaning Pt. 1--------#

#1. RENAME COLUMNS BY INDEX
#https://www.geeksforgeeks.org/python/rename-column-by-index-in-pandas/

df_pbutton_15_16.rename(columns={
    df_pbutton_15_16.columns[0]: "County",
    df_pbutton_15_16.columns[1]: "Buttonbuck_2015-16",
    df_pbutton_15_16.columns[2]: "Female_or_Antlerless_2015-16",
    df_pbutton_15_16.columns[3]: "Total_2015-16",
    df_pbutton_15_16.columns[4]: "Percent_Buttonbuck"
    
}, inplace=True)
 
#2. FORMAT OF COUNTY NAMES:
    #strip \n
    #Anne Arundel
    #Prince George's 
    #Queen Anne's
df_pbutton_15_16['County']=df_pbutton_15_16['County'].str.replace("\n", " ")
#https://stackoverflow.com/questions/65666852/why-cant-i-replace-a-newline-in-my-pandas-dataframe

# #https://stackoverflow.com/questions/70893764/how-to-change-the-column-type-of-all-columns-except-the-first-in-pandas

# 3. Drop percent in buttonbuck
df_pbutton_15_16.drop(df_pbutton_15_16.columns[4], axis=1, inplace = True)

In [75]:
df_pbutton_15_16

,County,Buttonbuck_2015-16,Female_or_Antlerless_2015-16,Total_2015-16
0,County,Buttonbuck,Female or\nAntlerless,Total
1,Allegany,192,1192,1384
2,Anne Arundel,305,1505,1810
3,Baltimore,436,3071,3507
4,Calvert,173,906,1079
5,Caroline,,,
6,Whitetail,329,1660,1989
7,Sika,0,2,2
8,Carroll,429,2999,3428
9,Cecil,325,1770,2095
10,Charles,302,1749,2051
11,Dorchester,,,
12,Whitetail,333,1353,1686
13,Sika,103,1481,1584
14,Frederick,514,4082,4596
15,Garrett,247,1503,1750
16,Harford,311,2114,2425
17,Howard,215,1418,1633
18,Kent,293,1771,2064
19,Montgomery,413,2930,3343
20,Prince George’s,275,1392,1667
21,Queen Anne’s,369,2148,2517
22,St. Mary’s,341,1446,1787
23,Somerset,,,
24,Whitetail,313,1498,1811
25,Sika,1,4,5
26,Talbot,383,1621,2004
27,Washington,288,2683,2971
28,Wicomico,,,
29,Whitetail,350,1801,2151
30,Sika,10,50,60
31,Worcester,,,
32,Whitetail,456,2272,2728
33,Sika,1,39,40
34,Total,7707,46460,54167
35,*Small sample size,NaN,NaN,NaN

In [76]:
#--------2015-2016 Button Buck and Doe Harvest Cleaning Pt. 2--------#
import numpy as np 
# 4. Replace asterisks and spaces with NaN
df_pbutton_15_16=df_pbutton_15_16.replace(r'^\*$', np.nan, regex=True)
#https://stackoverflow.com/questions/45311262/replace-a-variable-number-of-asterisks-with-nan-in-a-dataframe

In [77]:
#5. Drop last row, which just has "small sample size" text
df_pbutton_15_16=df_pbutton_15_16.drop(df_pbutton_15_16.index[35])

In [78]:
df_pbutton_15_16

,County,Buttonbuck_2015-16,Female_or_Antlerless_2015-16,Total_2015-16
0,County,Buttonbuck,Female or\nAntlerless,Total
1,Allegany,192,1192,1384
2,Anne Arundel,305,1505,1810
3,Baltimore,436,3071,3507
4,Calvert,173,906,1079
5,Caroline,,,
6,Whitetail,329,1660,1989
7,Sika,0,2,2
8,Carroll,429,2999,3428
9,Cecil,325,1770,2095
10,Charles,302,1749,2051
11,Dorchester,,,
12,Whitetail,333,1353,1686
13,Sika,103,1481,1584
14,Frederick,514,4082,4596
15,Garrett,247,1503,1750
16,Harford,311,2114,2425
17,Howard,215,1418,1633
18,Kent,293,1771,2064
19,Montgomery,413,2930,3343
20,Prince George’s,275,1392,1667
21,Queen Anne’s,369,2148,2517
22,St. Mary’s,341,1446,1787
23,Somerset,,,
24,Whitetail,313,1498,1811
25,Sika,1,4,5
26,Talbot,383,1621,2004
27,Washington,288,2683,2971
28,Wicomico,,,
29,Whitetail,350,1801,2151
30,Sika,10,50,60
31,Worcester,,,
32,Whitetail,456,2272,2728
33,Sika,1,39,40
34,Total,7707,46460,54167

In [79]:
#6. Drop first row
df_pbutton_15_16.drop(labels=0, inplace=True)

#7. Strip commas
df_pbutton_15_16.replace(',','', regex=True, inplace=True)

,County,Buttonbuck_2015-16,Female_or_Antlerless_2015-16,Total_2015-16
1,Allegany,192,1192,1384
2,Anne Arundel,305,1505,1810
3,Baltimore,436,3071,3507
4,Calvert,173,906,1079
5,Caroline,,,
6,Whitetail,329,1660,1989
7,Sika,0,2,2
8,Carroll,429,2999,3428
9,Cecil,325,1770,2095
10,Charles,302,1749,2051
11,Dorchester,,,
12,Whitetail,333,1353,1686
13,Sika,103,1481,1584
14,Frederick,514,4082,4596
15,Garrett,247,1503,1750
16,Harford,311,2114,2425
17,Howard,215,1418,1633
18,Kent,293,1771,2064
19,Montgomery,413,2930,3343
20,Prince George’s,275,1392,1667
21,Queen Anne’s,369,2148,2517
22,St. Mary’s,341,1446,1787
23,Somerset,,,
24,Whitetail,313,1498,1811
25,Sika,1,4,5
26,Talbot,383,1621,2004
27,Washington,288,2683,2971
28,Wicomico,,,
29,Whitetail,350,1801,2151
30,Sika,10,50,60
31,Worcester,,,
32,Whitetail,456,2272,2728
33,Sika,1,39,40
34,Total,7707,46460,54167

In [80]:
df_pbutton_15_16.iloc[4]

County                          Caroline
Buttonbuck_2015-16
Female_or_Antlerless_2015-16
Total_2015-16
Name: 5, dtype: str

In [81]:
#--------2015-2016 Button Buck and Doe Harvest Cleaning Pt. 3--------#

#8. Change datatype from string to float for numeric avlues 
df_pbutton_15_16['Buttonbuck_2015-16'] = pd.to_numeric( df_pbutton_15_16['Buttonbuck_2015-16'], errors="coerce")
df_pbutton_15_16['Female_or_Antlerless_2015-16'] = pd.to_numeric( df_pbutton_15_16['Female_or_Antlerless_2015-16'], errors="coerce")
df_pbutton_15_16['Total_2015-16'] = pd.to_numeric( df_pbutton_15_16['Total_2015-16'], errors="coerce")

#9. Reset index after dropping rows. 
df_pbutton_15_16 = df_pbutton_15_16.reset_index(drop=True)

In [82]:
#--------2015-2016 Button Buck and Doe Harvest Cleaning Pt. 3--------#

#10. Sum whitetail and sika, then move those sums to county row

#CAROLINE COUNTY
df_pbutton_15_16 = df_pbutton_15_16.reset_index(drop=True) 
df_pbutton_15_16.iloc[4, 1] = df_pbutton_15_16.iloc[[5, 6], 1].sum()
df_pbutton_15_16.iloc[4, 2] = df_pbutton_15_16.iloc[[5,6], 2].sum()
df_pbutton_15_16.iloc[4, 3] = df_pbutton_15_16.iloc[[5, 6], 3].sum()

# #Dorchester
df_pbutton_15_16.iloc[10, 1] = df_pbutton_15_16.iloc[[11, 12], 1].sum()
df_pbutton_15_16.iloc[10, 2] = df_pbutton_15_16.iloc[[11,12], 2].sum()
df_pbutton_15_16.iloc[10, 3] = df_pbutton_15_16.iloc[[11, 12], 3].sum()

#Somerset
df_pbutton_15_16.iloc[22, 1] = df_pbutton_15_16.iloc[[23, 24], 1].sum()
df_pbutton_15_16.iloc[22, 2] = df_pbutton_15_16.iloc[[23,24], 2].sum()
df_pbutton_15_16.iloc[22, 3] = df_pbutton_15_16.iloc[[23, 24], 3].sum()

#Wicomico
df_pbutton_15_16.iloc[27, 1] = df_pbutton_15_16.iloc[[28, 29], 1].sum()
df_pbutton_15_16.iloc[27, 2] = df_pbutton_15_16.iloc[[28,29], 2].sum()
df_pbutton_15_16.iloc[27, 3] = df_pbutton_15_16.iloc[[28, 29], 3].sum()

# #Worcester
df_pbutton_15_16.iloc[30, 1] = df_pbutton_15_16.iloc[[31, 32], 1].sum()
df_pbutton_15_16.iloc[30, 2] = df_pbutton_15_16.iloc[[31,32], 2].sum()
df_pbutton_15_16.iloc[30, 3] = df_pbutton_15_16.iloc[[31, 32], 3].sum()

In [83]:
#---------2015-2016 Button Buck and Doe Harvest FINAL CLEANING: DROPPING ROWS---------#
#11. Filter county values for "whitetail" and "sika" and drop those rows
df_pbutton_15_16=df_pbutton_15_16[ df_pbutton_15_16[ "County" ].str.contains( "Whitetail|Sika" )== False]
df_pbutton_15_16= df_pbutton_15_16.reset_index(drop=True)
df_pbutton_15_16.to_csv("df_pbutton_15_16.csv")

In [84]:
df_pbutton_15_16

,County,Buttonbuck_2015-16,Female_or_Antlerless_2015-16,Total_2015-16
0,Allegany,192.0,1192.0,1384.0
1,Anne Arundel,305.0,1505.0,1810.0
2,Baltimore,436.0,3071.0,3507.0
3,Calvert,173.0,906.0,1079.0
4,Caroline,329.0,1662.0,1991.0
5,Carroll,429.0,2999.0,3428.0
6,Cecil,325.0,1770.0,2095.0
7,Charles,302.0,1749.0,2051.0
8,Dorchester,436.0,2834.0,3270.0
9,Frederick,514.0,4082.0,4596.0
10,Garrett,247.0,1503.0,1750.0
11,Harford,311.0,2114.0,2425.0
12,Howard,215.0,1418.0,1633.0
13,Kent,293.0,1771.0,2064.0
14,Montgomery,413.0,2930.0,3343.0
15,Prince George’s,275.0,1392.0,1667.0
16,Queen Anne’s,369.0,2148.0,2517.0
17,St. Mary’s,341.0,1446.0,1787.0
18,Somerset,314.0,1502.0,1816.0
19,Talbot,383.0,1621.0,2004.0
20,Washington,288.0,2683.0,2971.0
21,Wicomico,360.0,1851.0,2211.0
22,Worcester,457.0,2311.0,2768.0
23,Total,7707.0,46460.0,54167.0

In [85]:
#2016-2017 Button buck and doe harvest 

# Open a PDF
pdf = PDF('md_annual_deer_report16-17.pdf')
page = pdf.pages[11]
page.show(width=700)

table = page.extract_table(method="pdfplumber")
list(table)

rows = list(table)

df_pbutton_16_17 = pd.DataFrame(rows)

df_pbutton_16_17.to_csv("df_pbutton_16_17.csv", index=False)

In [86]:
df_pbutton_16_17

,0,1,2,3,4
0,COUNTY,Buttonbuck,Female or\nAntlerless,Total,Percent\nButtonbuck
1,Allegany,174,1071,1245,14.0
2,Anne\nArundel,310,1580,1890,16.4
3,Baltimore,425,3314,3739,11.4
4,Calvert,193,1060,1253,15.4
5,Caroline,,,,
6,Whitetail,338,1695,2033,16.6
7,Sika,0,1,1,*
8,Carroll,505,3156,3661,13.8
9,Cecil,342,1969,2311,14.8
10,Charles,257,1743,2000,12.9
11,Dorchester,,,,
12,Whitetail,337,1483,1820,18.5
13,Sika,84,1375,1459,5.8
14,Frederick,545,4331,4876,11.2
15,Garrett,229,1490,1719,13.3
16,Harford,391,2146,2537,15.4
17,Howard,236,1479,1715,13.8
18,Kent,346,1836,2182,15.9
19,Montgomery,489,2879,3368,14.5
20,Prince\nGeorge’s,277,1368,1645,16.8
21,Queen\nAnne’s,390,2193,2583,15.1
22,St. Mary’s,276,1484,1760,15.7
23,Somerset,,,,
24,Whitetail,245,1353,1598,15.3
25,Sika,0,2,2,*
26,Talbot,349,1632,1981,17.6
27,Washington,267,2407,2674,10.0
28,Wicomico,,,,
29,Whitetail,351,1838,2189,16.0
30,Sika,12,54,66,*
31,Worcester,,,,
32,Whitetail,435,2104,2539,17.1
33,Sika,2,19,21,*
34,Total,7805,47062,54867,14.2
35,*Small sample size,NaN,NaN,NaN,NaN

In [87]:
#--------2016-2017 Button Buck and Doe Harvest Cleaning Pt. 1--------#

#1. RENAME COLUMNS BY INDEX
#https://www.geeksforgeeks.org/python/rename-column-by-index-in-pandas/

df_pbutton_16_17.rename(columns={
    df_pbutton_16_17.columns[0]: "County",
    df_pbutton_16_17.columns[1]: "Buttonbuck_2016-17",
    df_pbutton_16_17.columns[2]: "Female_or_Antlerless_2016-17",
    df_pbutton_16_17.columns[3]: "Total_2016-17",
    df_pbutton_16_17.columns[4]: "Percent_Buttonbuck"
    
}, inplace=True)
 
#2. FORMAT OF COUNTY NAMES:
    #strip \n
    #Anne Arundel
    #Prince George's 
    #Queen Anne's
df_pbutton_16_17['County']=df_pbutton_16_17['County'].str.replace("\n", " ")
#https://stackoverflow.com/questions/65666852/why-cant-i-replace-a-newline-in-my-pandas-dataframe
#https://stackoverflow.com/questions/70893764/how-to-change-the-column-type-of-all-columns-except-the-first-in-pandas

#3. Drop percent in buttonbuck
df_pbutton_16_17 = df_pbutton_16_17.drop(df_pbutton_16_17.columns[4], axis=1)

In [88]:
df_pbutton_16_17

,County,Buttonbuck_2016-17,Female_or_Antlerless_2016-17,Total_2016-17
0,COUNTY,Buttonbuck,Female or\nAntlerless,Total
1,Allegany,174,1071,1245
2,Anne Arundel,310,1580,1890
3,Baltimore,425,3314,3739
4,Calvert,193,1060,1253
5,Caroline,,,
6,Whitetail,338,1695,2033
7,Sika,0,1,1
8,Carroll,505,3156,3661
9,Cecil,342,1969,2311
10,Charles,257,1743,2000
11,Dorchester,,,
12,Whitetail,337,1483,1820
13,Sika,84,1375,1459
14,Frederick,545,4331,4876
15,Garrett,229,1490,1719
16,Harford,391,2146,2537
17,Howard,236,1479,1715
18,Kent,346,1836,2182
19,Montgomery,489,2879,3368
20,Prince George’s,277,1368,1645
21,Queen Anne’s,390,2193,2583
22,St. Mary’s,276,1484,1760
23,Somerset,,,
24,Whitetail,245,1353,1598
25,Sika,0,2,2
26,Talbot,349,1632,1981
27,Washington,267,2407,2674
28,Wicomico,,,
29,Whitetail,351,1838,2189
30,Sika,12,54,66
31,Worcester,,,
32,Whitetail,435,2104,2539
33,Sika,2,19,21
34,Total,7805,47062,54867
35,*Small sample size,NaN,NaN,NaN

In [89]:
#--------2016-2017 Button Buck and Doe Harvest Cleaning Pt. 2--------#

#4. Replace asterisks and spaces with NaN
df_pbutton_16_17=df_pbutton_16_17.replace(r'^\*$', np.nan, regex=True)
##https://stackoverflow.com/questions/45311262/replace-a-variable-number-of-asterisks-with-nan-in-a-dataframe 

#5. Drop last row, which just has "small sample size" text
df_pbutton_16_17 = df_pbutton_16_17.iloc[:-1]

#6. Drop first row
df_pbutton_16_17.drop(labels=0, inplace=True)

#7. Strip commas
df_pbutton_16_17.replace(',','', regex=True, inplace=True)

,County,Buttonbuck_2016-17,Female_or_Antlerless_2016-17,Total_2016-17
1,Allegany,174,1071,1245
2,Anne Arundel,310,1580,1890
3,Baltimore,425,3314,3739
4,Calvert,193,1060,1253
5,Caroline,,,
6,Whitetail,338,1695,2033
7,Sika,0,1,1
8,Carroll,505,3156,3661
9,Cecil,342,1969,2311
10,Charles,257,1743,2000
11,Dorchester,,,
12,Whitetail,337,1483,1820
13,Sika,84,1375,1459
14,Frederick,545,4331,4876
15,Garrett,229,1490,1719
16,Harford,391,2146,2537
17,Howard,236,1479,1715
18,Kent,346,1836,2182
19,Montgomery,489,2879,3368
20,Prince George’s,277,1368,1645
21,Queen Anne’s,390,2193,2583
22,St. Mary’s,276,1484,1760
23,Somerset,,,
24,Whitetail,245,1353,1598
25,Sika,0,2,2
26,Talbot,349,1632,1981
27,Washington,267,2407,2674
28,Wicomico,,,
29,Whitetail,351,1838,2189
30,Sika,12,54,66
31,Worcester,,,
32,Whitetail,435,2104,2539
33,Sika,2,19,21
34,Total,7805,47062,54867

In [90]:
#--------2016-2017 Button Buck and Doe Harvest Cleaning Pt. 3--------#

#7. Change datatype from string to float for numeric avlues 

df_pbutton_16_17['Buttonbuck_2016-17'] = pd.to_numeric( df_pbutton_16_17['Buttonbuck_2016-17'], errors="coerce")
df_pbutton_16_17['Female_or_Antlerless_2016-17'] = pd.to_numeric( df_pbutton_16_17['Female_or_Antlerless_2016-17'], errors="coerce")
df_pbutton_16_17['Total_2016-17'] = pd.to_numeric( df_pbutton_16_17['Total_2016-17'], errors="coerce")

In [91]:
#--------2016-2017 Button Buck and Doe Harvest Cleaning Pt. 4--------#

#8. Reset index after dropping rows. 
df_pbutton_16_17 = df_pbutton_16_17.reset_index(drop=True) 

#9. Sum whitetail and sika, then move those sums to county row 

#CAROLINE COUNTY
df_pbutton_16_17.iloc[4, 1] = df_pbutton_16_17.iloc[[5, 6], 1].sum()
df_pbutton_16_17.iloc[4, 2] = df_pbutton_16_17.iloc[[5,6], 2].sum()
df_pbutton_16_17.iloc[4, 3] = df_pbutton_16_17.iloc[[5, 6], 3].sum()

# #Dorchester
df_pbutton_16_17.iloc[10, 1] = df_pbutton_16_17.iloc[[11, 12], 1].sum()
df_pbutton_16_17.iloc[10, 2] = df_pbutton_16_17.iloc[[11,12], 2].sum()
df_pbutton_16_17.iloc[10, 3] = df_pbutton_16_17.iloc[[11, 12], 3].sum()

#Somerset
df_pbutton_16_17.iloc[22, 1] = df_pbutton_16_17.iloc[[23, 24], 1].sum()
df_pbutton_16_17.iloc[22, 2] = df_pbutton_16_17.iloc[[23,24], 2].sum()
df_pbutton_16_17.iloc[22, 3] = df_pbutton_16_17.iloc[[23, 24], 3].sum()

#Wicomico
df_pbutton_16_17.iloc[27, 1] = df_pbutton_16_17.iloc[[28, 29], 1].sum()
df_pbutton_16_17.iloc[27, 2] = df_pbutton_16_17.iloc[[28,29], 2].sum()
df_pbutton_16_17.iloc[27, 3] = df_pbutton_16_17.iloc[[28, 29], 3].sum()

# #Worcester
df_pbutton_16_17.iloc[30, 1] = df_pbutton_16_17.iloc[[31, 32], 1].sum()
df_pbutton_16_17.iloc[30, 2] = df_pbutton_16_17.iloc[[31,32], 2].sum()
df_pbutton_16_17.iloc[30, 3] = df_pbutton_16_17.iloc[[31, 32], 3].sum()

In [92]:
#---------2016-2017 Button Buck and Doe Harvest FINAL CLEANING: DROPPING ROWS---------#
#Filter county values for "whitetail" and "sika" and drop those rows
df_pbutton_16_17=df_pbutton_16_17[ df_pbutton_16_17[ "County" ].str.contains( "Whitetail|Sika" )== False]
df_pbutton_16_17= df_pbutton_16_17.reset_index(drop=True)
df_pbutton_16_17.to_csv("df_pbutton_16_17.csv")

In [93]:
#2017-2018 Button buck and doe harvest 

# Open a PDF
pdf = PDF('MD-Annual-Deer-Report-2017-2018.pdf')
page = pdf.pages[11]
page.show(width=700)

table = page.extract_table(method="pdfplumber")
list(table)

rows = list(table)

df_pbutton_17_18 = pd.DataFrame(rows)

df_pbutton_17_18.to_csv("df_pbutton_17_18.csv", index=False)

In [94]:
df_pbutton_17_18

,0,1,2,3,4
0,COUNTY,Buttonbuck,Female or\nAntlerless,Total,Percent\nButtonbuck
1,Allegany,146,1137,1283,11.4
2,Anne\nArundel,300,1701,2001,15.0
3,Baltimore,470,3335,3805,12.4
4,Calvert,166,964,1130,14.7
5,Caroline,,,,
6,Whitetail,327,1497,1824,17.9
7,Sika,1,0,1,*
8,Carroll,480,3300,3780,12.7
9,Cecil,347,2095,2442,14.2
10,Charles,304,1942,2246,13.5
11,Dorchester,,,,
12,Whitetail,283,1199,1482,19.1
13,Sika,104,1518,1622,6.4
14,Frederick,545,4143,4688,11.6
15,Garrett,225,1789,2014,11.2
16,Harford,348,2118,2466,14.1
17,Howard,236,1453,1689,14.0
18,Kent,292,1978,2270,12.9
19,Montgomery,470,2856,3326,14.1
20,Prince\nGeorge’s,228,1332,1560,14.6
21,Queen\nAnne’s,423,2278,2701,15.7
22,St. Mary’s,305,1542,1847,16.5
23,Somerset,,,,
24,Whitetail,273,1267,1540,17.7
25,Sika,0,7,7,*
26,Talbot,345,1485,1830,18.9
27,Washington,249,2209,2458,10.1
28,Wicomico,,,,
29,Whitetail,321,1954,2275,14.1
30,Sika,4,79,83,*
31,Worcester,,,,
32,Whitetail,370,2108,2478,14.9
33,Sika,1,23,24,*
34,Total,7563,47309,54872,13.8
35,*Small sample size,NaN,NaN,NaN,NaN

In [95]:
#--------2017-2018 Button Buck and Doe Harvest Cleaning Pt. 1--------#

#1. RENAME COLUMNS BY INDEX
#https://www.geeksforgeeks.org/python/rename-column-by-index-in-pandas/

df_pbutton_17_18.rename(columns={
    df_pbutton_17_18.columns[0]: "County",
    df_pbutton_17_18.columns[1]: "Buttonbuck_2017-18",
    df_pbutton_17_18.columns[2]: "Female_or_Antlerless_2017-18",
    df_pbutton_17_18.columns[3]: "Total_2017-18",
    df_pbutton_17_18.columns[4]: "Percent_Buttonbuck"
    
}, inplace=True)
 
#2. FORMAT OF COUNTY NAMES:
    #strip \n
    #Anne Arundel
    #Prince George's 
    #Queen Anne's
df_pbutton_17_18['County']=df_pbutton_17_18['County'].str.replace("\n", " ")
#https://stackoverflow.com/questions/65666852/why-cant-i-replace-a-newline-in-my-pandas-dataframe
#https://stackoverflow.com/questions/70893764/how-to-change-the-column-type-of-all-columns-except-the-first-in-pandas

#3. Drop percent in buttonbuck
df_pbutton_17_18 = df_pbutton_17_18.drop(df_pbutton_17_18.columns[4], axis=1)

In [96]:
df_pbutton_17_18

,County,Buttonbuck_2017-18,Female_or_Antlerless_2017-18,Total_2017-18
0,COUNTY,Buttonbuck,Female or\nAntlerless,Total
1,Allegany,146,1137,1283
2,Anne Arundel,300,1701,2001
3,Baltimore,470,3335,3805
4,Calvert,166,964,1130
5,Caroline,,,
6,Whitetail,327,1497,1824
7,Sika,1,0,1
8,Carroll,480,3300,3780
9,Cecil,347,2095,2442
10,Charles,304,1942,2246
11,Dorchester,,,
12,Whitetail,283,1199,1482
13,Sika,104,1518,1622
14,Frederick,545,4143,4688
15,Garrett,225,1789,2014
16,Harford,348,2118,2466
17,Howard,236,1453,1689
18,Kent,292,1978,2270
19,Montgomery,470,2856,3326
20,Prince George’s,228,1332,1560
21,Queen Anne’s,423,2278,2701
22,St. Mary’s,305,1542,1847
23,Somerset,,,
24,Whitetail,273,1267,1540
25,Sika,0,7,7
26,Talbot,345,1485,1830
27,Washington,249,2209,2458
28,Wicomico,,,
29,Whitetail,321,1954,2275
30,Sika,4,79,83
31,Worcester,,,
32,Whitetail,370,2108,2478
33,Sika,1,23,24
34,Total,7563,47309,54872
35,*Small sample size,NaN,NaN,NaN

In [97]:
#--------2017-2018 Button Buck and Doe Harvest Cleaning Pt. 2--------#

#4. Replace asterisks and spaces with NaN
df_pbutton_17_18=df_pbutton_17_18.replace(r'^\*$', np.nan, regex=True)
##https://stackoverflow.com/questions/45311262/replace-a-variable-number-of-asterisks-with-nan-in-a-dataframe 

#5. Drop last row, which just has "small sample size" text
df_pbutton_17_18 = df_pbutton_17_18.iloc[:-1]

#6. Drop first row
df_pbutton_17_18.drop(labels=0, inplace=True)

#7. Strip commas
df_pbutton_17_18.replace(',','', regex=True, inplace=True)

,County,Buttonbuck_2017-18,Female_or_Antlerless_2017-18,Total_2017-18
1,Allegany,146,1137,1283
2,Anne Arundel,300,1701,2001
3,Baltimore,470,3335,3805
4,Calvert,166,964,1130
5,Caroline,,,
6,Whitetail,327,1497,1824
7,Sika,1,0,1
8,Carroll,480,3300,3780
9,Cecil,347,2095,2442
10,Charles,304,1942,2246
11,Dorchester,,,
12,Whitetail,283,1199,1482
13,Sika,104,1518,1622
14,Frederick,545,4143,4688
15,Garrett,225,1789,2014
16,Harford,348,2118,2466
17,Howard,236,1453,1689
18,Kent,292,1978,2270
19,Montgomery,470,2856,3326
20,Prince George’s,228,1332,1560
21,Queen Anne’s,423,2278,2701
22,St. Mary’s,305,1542,1847
23,Somerset,,,
24,Whitetail,273,1267,1540
25,Sika,0,7,7
26,Talbot,345,1485,1830
27,Washington,249,2209,2458
28,Wicomico,,,
29,Whitetail,321,1954,2275
30,Sika,4,79,83
31,Worcester,,,
32,Whitetail,370,2108,2478
33,Sika,1,23,24
34,Total,7563,47309,54872

In [98]:
#--------2017-2018 Button Buck and Doe Harvest Cleaning Pt. 3--------#

#7. Change datatype from string to float for numeric values 

df_pbutton_17_18['Buttonbuck_2017-18'] = pd.to_numeric( df_pbutton_17_18['Buttonbuck_2017-18'], errors="coerce")
df_pbutton_17_18['Female_or_Antlerless_2017-18'] = pd.to_numeric( df_pbutton_17_18['Female_or_Antlerless_2017-18'], errors="coerce")
df_pbutton_17_18['Total_2017-18'] = pd.to_numeric( df_pbutton_17_18['Total_2017-18'], errors="coerce")

#8. Reset index after dropping rows. 
df_pbutton_17_18 = df_pbutton_17_18.reset_index(drop=True)

In [99]:
df_pbutton_17_18

,County,Buttonbuck_2017-18,Female_or_Antlerless_2017-18,Total_2017-18
0,Allegany,146.0,1137.0,1283.0
1,Anne Arundel,300.0,1701.0,2001.0
2,Baltimore,470.0,3335.0,3805.0
3,Calvert,166.0,964.0,1130.0
4,Caroline,NaN,NaN,NaN
5,Whitetail,327.0,1497.0,1824.0
6,Sika,1.0,0.0,1.0
7,Carroll,480.0,3300.0,3780.0
8,Cecil,347.0,2095.0,2442.0
9,Charles,304.0,1942.0,2246.0
10,Dorchester,NaN,NaN,NaN
11,Whitetail,283.0,1199.0,1482.0
12,Sika,104.0,1518.0,1622.0
13,Frederick,545.0,4143.0,4688.0
14,Garrett,225.0,1789.0,2014.0
15,Harford,348.0,2118.0,2466.0
16,Howard,236.0,1453.0,1689.0
17,Kent,292.0,1978.0,2270.0
18,Montgomery,470.0,2856.0,3326.0
19,Prince George’s,228.0,1332.0,1560.0
20,Queen Anne’s,423.0,2278.0,2701.0
21,St. Mary’s,305.0,1542.0,1847.0
22,Somerset,NaN,NaN,NaN
23,Whitetail,273.0,1267.0,1540.0
24,Sika,0.0,7.0,7.0
25,Talbot,345.0,1485.0,1830.0
26,Washington,249.0,2209.0,2458.0
27,Wicomico,NaN,NaN,NaN
28,Whitetail,321.0,1954.0,2275.0
29,Sika,4.0,79.0,83.0
30,Worcester,NaN,NaN,NaN
31,Whitetail,370.0,2108.0,2478.0
32,Sika,1.0,23.0,24.0
33,Total,7563.0,47309.0,54872.0

In [100]:
#--------2017-2018 Button Buck and Doe Harvest Cleaning Pt. 4--------# 

#9. Sum whitetail and sika, then move those sums to county row 

#CAROLINE COUNTY
df_pbutton_17_18.iloc[4, 1] = df_pbutton_17_18.iloc[[5, 6], 1].sum()
df_pbutton_17_18.iloc[4, 2] = df_pbutton_17_18.iloc[[5,6], 2].sum()
df_pbutton_17_18.iloc[4, 3] = df_pbutton_17_18.iloc[[5, 6], 3].sum()

# #Dorchester
df_pbutton_17_18.iloc[10, 1] = df_pbutton_17_18.iloc[[11, 12], 1].sum()
df_pbutton_17_18.iloc[10, 2] = df_pbutton_17_18.iloc[[11,12], 2].sum()
df_pbutton_17_18.iloc[10, 3] = df_pbutton_17_18.iloc[[11, 12], 3].sum()

#Somerset
df_pbutton_17_18.iloc[22, 1] = df_pbutton_17_18.iloc[[23, 24], 1].sum()
df_pbutton_17_18.iloc[22, 2] = df_pbutton_17_18.iloc[[23,24], 2].sum()
df_pbutton_17_18.iloc[22, 3] = df_pbutton_17_18.iloc[[23, 24], 3].sum()

#Wicomico
df_pbutton_17_18.iloc[27, 1] = df_pbutton_17_18.iloc[[28, 29], 1].sum()
df_pbutton_17_18.iloc[27, 2] = df_pbutton_17_18.iloc[[28,29], 2].sum()
df_pbutton_17_18.iloc[27, 3] = df_pbutton_17_18.iloc[[28, 29], 3].sum()

# #Worcester
df_pbutton_17_18.iloc[30, 1] = df_pbutton_17_18.iloc[[31, 32], 1].sum()
df_pbutton_17_18.iloc[30, 2] = df_pbutton_17_18.iloc[[31,32], 2].sum()
df_pbutton_17_18.iloc[30, 3] = df_pbutton_17_18.iloc[[31, 32], 3].sum()

In [101]:
#---------2017-2018 Button Buck and Doe Harvest FINAL CLEANING: DROPPING ROWS---------#
#10. Filter county values for "whitetail" and "sika" and drop those rows
df_pbutton_17_18=df_pbutton_17_18[ df_pbutton_17_18[ "County" ].str.contains( "Whitetail|Sika" )== False]
df_pbutton_17_18= df_pbutton_17_18.reset_index(drop=True)
df_pbutton_17_18.to_csv("df_pbutton_17_18.csv")

In [102]:
#2018-2019 Button buck and doe harvest 
from natural_pdf import PDF
# Open a PDF
pdf = PDF('MD-Annual-Deer-Report-2018-2019.pdf')
page = pdf.pages[13]
page.show(width=700)

table = page.extract_table(method="pdfplumber")
list(table)

rows = list(table)

df_pbutton_18_19 = pd.DataFrame(rows)

df_pbutton_18_19.to_csv("df_pbutton_18_19.csv", index=False)

In [103]:
#--------2018-2019 Button Buck and Doe Harvest Cleaning Pt. 1--------#

#1. RENAME COLUMNS BY INDEX
#https://www.geeksforgeeks.org/python/rename-column-by-index-in-pandas/

df_pbutton_18_19.rename(columns={
    df_pbutton_18_19.columns[0]: "County",
    df_pbutton_18_19.columns[1]: "Buttonbuck_2018-19",
    df_pbutton_18_19.columns[2]: "Female_or_Antlerless_2018-19",
    df_pbutton_18_19.columns[3]: "Total_2018-19",
    df_pbutton_18_19.columns[4]: "Percent_Buttonbuck"
    
}, inplace=True)
 
#2. FORMAT OF COUNTY NAMES:
    #strip \n
    #Anne Arundel
    #Prince George's 
    #Queen Anne's
df_pbutton_18_19['County']=df_pbutton_18_19['County'].str.replace("\n", " ")
#https://stackoverflow.com/questions/65666852/why-cant-i-replace-a-newline-in-my-pandas-dataframe
#https://stackoverflow.com/questions/70893764/how-to-change-the-column-type-of-all-columns-except-the-first-in-pandas

#3. Drop percent in buttonbuck
df_pbutton_18_19 = df_pbutton_18_19.drop(df_pbutton_18_19.columns[4], axis=1)

In [104]:
df_pbutton_18_19

,County,Buttonbuck_2018-19,Female_or_Antlerless_2018-19,Total_2018-19
0,COUNTY,Buttonbuck,Female or\nAntlerless,Total
1,Allegany,156,"1,288","1,444"
2,Anne Arundel,219,"1,343","1,562"
3,Baltimore,330,"2,633","2,963"
4,Calvert,130,817,947
5,Caroline,,,
6,Whitetail,257,"1,470","1,727"
7,Sika,0,1,1
8,Carroll,384,"2,840","3,224"
9,Cecil,290,"1,979","2,269"
10,Charles,155,"1,173","1,328"
11,Dorchester,,,
12,Whitetail,226,935,"1,161"
13,Sika,89,"1,623","1,712"
14,Frederick,414,"3,439","3,853"
15,Garrett,235,"1,911","2,146"
16,Harford,294,"1,871","2,165"
17,Howard,150,"1,136","1,286"
18,Kent,248,"1,701","1,949"
19,Montgomery,333,"2,174","2,507"
20,Prince George’s,162,"1,101","1,263"
21,Queen Anne’s,262,"1,798","2,060"
22,St. Mary’s,182,955,"1,137"
23,Somerset,,,
24,Whitetail,188,"1,104","1,292"
25,Sika,1,4,5
26,Talbot,233,"1,302","1,535"
27,Washington,227,"2,227","2,454"
28,Wicomico,,,
29,Whitetail,220,"1,599","1,819"
30,Sika,5,76,81
31,Worcester,,,
32,Whitetail,328,"1,830","2,158"
33,Sika,5,21,26
34,Total,"5,723","40,351","46,074"
35,*Small sample size,NaN,NaN,NaN

In [105]:
#--------2018-2019 Button Buck and Doe Harvest Cleaning Pt. 2--------#
import numpy as np
#4. Replace asterisks and spaces with NaN
df_pbutton_18_19=df_pbutton_18_19.replace(r'^\*$', np.nan, regex=True)
##https://stackoverflow.com/questions/45311262/replace-a-variable-number-of-asterisks-with-nan-in-a-dataframe 

#5. Drop last row, which just has "small sample size" text
df_pbutton_18_19 = df_pbutton_18_19.iloc[:-1]

#6. Drop first row
df_pbutton_18_19.drop(labels=0, inplace=True)

#7. Strip commas
df_pbutton_18_19.replace(',','', regex=True, inplace=True)

,County,Buttonbuck_2018-19,Female_or_Antlerless_2018-19,Total_2018-19
1,Allegany,156,1288,1444
2,Anne Arundel,219,1343,1562
3,Baltimore,330,2633,2963
4,Calvert,130,817,947
5,Caroline,,,
6,Whitetail,257,1470,1727
7,Sika,0,1,1
8,Carroll,384,2840,3224
9,Cecil,290,1979,2269
10,Charles,155,1173,1328
11,Dorchester,,,
12,Whitetail,226,935,1161
13,Sika,89,1623,1712
14,Frederick,414,3439,3853
15,Garrett,235,1911,2146
16,Harford,294,1871,2165
17,Howard,150,1136,1286
18,Kent,248,1701,1949
19,Montgomery,333,2174,2507
20,Prince George’s,162,1101,1263
21,Queen Anne’s,262,1798,2060
22,St. Mary’s,182,955,1137
23,Somerset,,,
24,Whitetail,188,1104,1292
25,Sika,1,4,5
26,Talbot,233,1302,1535
27,Washington,227,2227,2454
28,Wicomico,,,
29,Whitetail,220,1599,1819
30,Sika,5,76,81
31,Worcester,,,
32,Whitetail,328,1830,2158
33,Sika,5,21,26
34,Total,5723,40351,46074

In [106]:
#--------2018-2019 Button Buck and Doe Harvest Cleaning Pt. 3--------#

#8. Change datatype from string to float for numeric values 

df_pbutton_18_19['Buttonbuck_2018-19'] = pd.to_numeric( df_pbutton_18_19['Buttonbuck_2018-19'], errors="coerce")
df_pbutton_18_19['Female_or_Antlerless_2018-19'] = pd.to_numeric( df_pbutton_18_19['Female_or_Antlerless_2018-19'], errors="coerce")
df_pbutton_18_19['Total_2018-19'] = pd.to_numeric( df_pbutton_18_19['Total_2018-19'], errors="coerce")

#9. Reset index after dropping rows. 
df_pbutton_18_19 = df_pbutton_18_19.reset_index(drop=True)

In [107]:
df_pbutton_18_19

,County,Buttonbuck_2018-19,Female_or_Antlerless_2018-19,Total_2018-19
0,Allegany,156.0,1288.0,1444.0
1,Anne Arundel,219.0,1343.0,1562.0
2,Baltimore,330.0,2633.0,2963.0
3,Calvert,130.0,817.0,947.0
4,Caroline,NaN,NaN,NaN
5,Whitetail,257.0,1470.0,1727.0
6,Sika,0.0,1.0,1.0
7,Carroll,384.0,2840.0,3224.0
8,Cecil,290.0,1979.0,2269.0
9,Charles,155.0,1173.0,1328.0
10,Dorchester,NaN,NaN,NaN
11,Whitetail,226.0,935.0,1161.0
12,Sika,89.0,1623.0,1712.0
13,Frederick,414.0,3439.0,3853.0
14,Garrett,235.0,1911.0,2146.0
15,Harford,294.0,1871.0,2165.0
16,Howard,150.0,1136.0,1286.0
17,Kent,248.0,1701.0,1949.0
18,Montgomery,333.0,2174.0,2507.0
19,Prince George’s,162.0,1101.0,1263.0
20,Queen Anne’s,262.0,1798.0,2060.0
21,St. Mary’s,182.0,955.0,1137.0
22,Somerset,NaN,NaN,NaN
23,Whitetail,188.0,1104.0,1292.0
24,Sika,1.0,4.0,5.0
25,Talbot,233.0,1302.0,1535.0
26,Washington,227.0,2227.0,2454.0
27,Wicomico,NaN,NaN,NaN
28,Whitetail,220.0,1599.0,1819.0
29,Sika,5.0,76.0,81.0
30,Worcester,NaN,NaN,NaN
31,Whitetail,328.0,1830.0,2158.0
32,Sika,5.0,21.0,26.0
33,Total,5723.0,40351.0,46074.0

In [108]:
#--------2018-2019 Button Buck and Doe Harvest Cleaning Pt. 4--------#

#10. Sum whitetail and sika, then move those sums to county row 

#CAROLINE COUNTY
df_pbutton_18_19.iloc[4, 1] = df_pbutton_18_19.iloc[[5, 6], 1].sum()
df_pbutton_18_19.iloc[4, 2] = df_pbutton_18_19.iloc[[5,6], 2].sum()
df_pbutton_18_19.iloc[4, 3] = df_pbutton_18_19.iloc[[5, 6], 3].sum()

# #Dorchester
df_pbutton_18_19.iloc[10, 1] = df_pbutton_18_19.iloc[[11, 12], 1].sum()
df_pbutton_18_19.iloc[10, 2] = df_pbutton_18_19.iloc[[11,12], 2].sum()
df_pbutton_18_19.iloc[10, 3] = df_pbutton_18_19.iloc[[11, 12], 3].sum()

#Somerset
df_pbutton_18_19.iloc[22, 1] = df_pbutton_18_19.iloc[[23, 24], 1].sum()
df_pbutton_18_19.iloc[22, 2] = df_pbutton_18_19.iloc[[23,24], 2].sum()
df_pbutton_18_19.iloc[22, 3] = df_pbutton_18_19.iloc[[23, 24], 3].sum()

#Wicomico
df_pbutton_18_19.iloc[27, 1] = df_pbutton_18_19.iloc[[28, 29], 1].sum()
df_pbutton_18_19.iloc[27, 2] = df_pbutton_18_19.iloc[[28,29], 2].sum()
df_pbutton_18_19.iloc[27, 3] = df_pbutton_18_19.iloc[[28, 29], 3].sum()

# #Worcester
df_pbutton_18_19.iloc[30, 1] = df_pbutton_18_19.iloc[[31, 32], 1].sum()
df_pbutton_18_19.iloc[30, 2] = df_pbutton_18_19.iloc[[31,32], 2].sum()
df_pbutton_18_19.iloc[30, 3] = df_pbutton_18_19.iloc[[31, 32], 3].sum()

In [109]:
df_pbutton_18_19

,County,Buttonbuck_2018-19,Female_or_Antlerless_2018-19,Total_2018-19
0,Allegany,156.0,1288.0,1444.0
1,Anne Arundel,219.0,1343.0,1562.0
2,Baltimore,330.0,2633.0,2963.0
3,Calvert,130.0,817.0,947.0
4,Caroline,257.0,1471.0,1728.0
5,Whitetail,257.0,1470.0,1727.0
6,Sika,0.0,1.0,1.0
7,Carroll,384.0,2840.0,3224.0
8,Cecil,290.0,1979.0,2269.0
9,Charles,155.0,1173.0,1328.0
10,Dorchester,315.0,2558.0,2873.0
11,Whitetail,226.0,935.0,1161.0
12,Sika,89.0,1623.0,1712.0
13,Frederick,414.0,3439.0,3853.0
14,Garrett,235.0,1911.0,2146.0
15,Harford,294.0,1871.0,2165.0
16,Howard,150.0,1136.0,1286.0
17,Kent,248.0,1701.0,1949.0
18,Montgomery,333.0,2174.0,2507.0
19,Prince George’s,162.0,1101.0,1263.0
20,Queen Anne’s,262.0,1798.0,2060.0
21,St. Mary’s,182.0,955.0,1137.0
22,Somerset,189.0,1108.0,1297.0
23,Whitetail,188.0,1104.0,1292.0
24,Sika,1.0,4.0,5.0
25,Talbot,233.0,1302.0,1535.0
26,Washington,227.0,2227.0,2454.0
27,Wicomico,225.0,1675.0,1900.0
28,Whitetail,220.0,1599.0,1819.0
29,Sika,5.0,76.0,81.0
30,Worcester,333.0,1851.0,2184.0
31,Whitetail,328.0,1830.0,2158.0
32,Sika,5.0,21.0,26.0
33,Total,5723.0,40351.0,46074.0

In [110]:
#---------2018-2019 Button Buck and Doe Harvest FINAL CLEANING: DROPPING ROWS---------#
#11. Filter county values for "whitetail" and "sika" and drop those rows
df_pbutton_18_19=df_pbutton_18_19[ df_pbutton_18_19[ "County" ].str.contains( "Whitetail|Sika" )== False]
df_pbutton_18_19= df_pbutton_18_19.reset_index(drop=True)
df_pbutton_18_19.to_csv("df_pbutton_18_19.csv")

In [111]:
#2019-2020 Button buck and doe harvest 

# Open a PDF
pdf = PDF('MD-Annual-Deer-Report-2019-2020.pdf')
page = pdf.pages[5]
page.show(width=700)

table = page.extract_table(method="pdfplumber")
list(table)

rows = list(table)

df_pbutton_19_20 = pd.DataFrame(rows)

df_pbutton_19_20.to_csv("df_pbutton_19_20.csv", index=False)

In [112]:
#--------2019-2020 Button Buck and Doe Harvest Cleaning Pt. 1--------#

#1. RENAME COLUMNS BY INDEX
#https://www.geeksforgeeks.org/python/rename-column-by-index-in-pandas/

df_pbutton_19_20.rename(columns={
    df_pbutton_19_20.columns[0]: "County",
    df_pbutton_19_20.columns[1]: "Buttonbuck_2019-20",
    df_pbutton_19_20.columns[2]: "Female_or_Antlerless_2019-20",
    df_pbutton_19_20.columns[3]: "Total_2019-20",
    df_pbutton_19_20.columns[4]: "Percent_Buttonbuck"
    
}, inplace=True)
 
#2. FORMAT OF COUNTY NAMES:
    #strip \n
    #Anne Arundel
    #Prince George's 
    #Queen Anne's
df_pbutton_19_20['County']=df_pbutton_19_20['County'].str.replace("\n", " ")
#https://stackoverflow.com/questions/65666852/why-cant-i-replace-a-newline-in-my-pandas-dataframe
#https://stackoverflow.com/questions/70893764/how-to-change-the-column-type-of-all-columns-except-the-first-in-pandas

#3. Drop percent in buttonbuck
df_pbutton_19_20 = df_pbutton_19_20.drop(df_pbutton_19_20.columns[4], axis=1)

In [113]:
#--------2019-2020 Button Buck and Doe Harvest Cleaning Pt. 2--------#

#4. Replace asterisks and spaces with NaN
df_pbutton_19_20=df_pbutton_19_20.replace(r'^\*$', np.nan, regex=True)
##https://stackoverflow.com/questions/45311262/replace-a-variable-number-of-asterisks-with-nan-in-a-dataframe 

#5. Drop last row, which just has "small sample size" text
df_pbutton_19_20 = df_pbutton_19_20.iloc[:-1]

#6. Drop first row
df_pbutton_19_20.drop(labels=0, inplace=True)

#7. Strip commas
df_pbutton_19_20.replace(',','', regex=True, inplace=True)

,County,Buttonbuck_2019-20,Female_or_Antlerless_2019-20,Total_2019-20
1,Allegany,91,1088,1179
2,Anne Arundel,199,1454,1653
3,Baltimore,386,2809,3195
4,Calvert,148,877,1025
5,Caroline,,,
6,Whitetail,271,1526,1797
7,Sika,0,1,1
8,Carroll,423,3114,3537
9,Cecil,333,2135,2468
10,Charles,257,1611,1868
11,Dorchester,,,
12,Whitetail,226,977,1203
13,Sika,100,1611,1711
14,Frederick,405,3410,3815
15,Garrett,187,1687,1874
16,Harford,254,2099,2353
17,Howard,163,1307,1470
18,Kent,282,1738,2020
19,Montgomery,300,2288,2588
20,Prince George’s,178,1133,1311
21,Queen Anne’s,263,1985,2248
22,St. Mary’s,265,1282,1547
23,Somerset,,,
24,Whitetail,255,1233,1488
25,Sika,0,8,8
26,Talbot,270,1367,1637
27,Washington,206,1989,2195
28,Wicomico,,,
29,Whitetail,263,1700,1963
30,Sika,6,108,114
31,Worcester,,,
32,Whitetail,344,1999,2343
33,Sika,1,60,61
34,Total,6076,42596,48672

In [114]:
#--------2019-2020 Button Buck and Doe Harvest Cleaning Pt. 3--------#

#8. Change datatype from string to float for numeric avlues 

df_pbutton_19_20['Buttonbuck_2019-20'] = pd.to_numeric( df_pbutton_19_20['Buttonbuck_2019-20'], errors="coerce")
df_pbutton_19_20['Female_or_Antlerless_2019-20'] = pd.to_numeric( df_pbutton_19_20['Female_or_Antlerless_2019-20'], errors="coerce")
df_pbutton_19_20['Total_2019-20'] = pd.to_numeric( df_pbutton_19_20['Total_2019-20'], errors="coerce")

#9. Reset index after dropping rows. 
df_pbutton_19_20 = df_pbutton_19_20.reset_index(drop=True)

In [115]:
df_pbutton_19_20

,County,Buttonbuck_2019-20,Female_or_Antlerless_2019-20,Total_2019-20
0,Allegany,91.0,1088.0,1179.0
1,Anne Arundel,199.0,1454.0,1653.0
2,Baltimore,386.0,2809.0,3195.0
3,Calvert,148.0,877.0,1025.0
4,Caroline,NaN,NaN,NaN
5,Whitetail,271.0,1526.0,1797.0
6,Sika,0.0,1.0,1.0
7,Carroll,423.0,3114.0,3537.0
8,Cecil,333.0,2135.0,2468.0
9,Charles,257.0,1611.0,1868.0
10,Dorchester,NaN,NaN,NaN
11,Whitetail,226.0,977.0,1203.0
12,Sika,100.0,1611.0,1711.0
13,Frederick,405.0,3410.0,3815.0
14,Garrett,187.0,1687.0,1874.0
15,Harford,254.0,2099.0,2353.0
16,Howard,163.0,1307.0,1470.0
17,Kent,282.0,1738.0,2020.0
18,Montgomery,300.0,2288.0,2588.0
19,Prince George’s,178.0,1133.0,1311.0
20,Queen Anne’s,263.0,1985.0,2248.0
21,St. Mary’s,265.0,1282.0,1547.0
22,Somerset,NaN,NaN,NaN
23,Whitetail,255.0,1233.0,1488.0
24,Sika,0.0,8.0,8.0
25,Talbot,270.0,1367.0,1637.0
26,Washington,206.0,1989.0,2195.0
27,Wicomico,NaN,NaN,NaN
28,Whitetail,263.0,1700.0,1963.0
29,Sika,6.0,108.0,114.0
30,Worcester,NaN,NaN,NaN
31,Whitetail,344.0,1999.0,2343.0
32,Sika,1.0,60.0,61.0
33,Total,6076.0,42596.0,48672.0

In [116]:
#--------2019-2020 Button Buck and Doe Harvest Cleaning Pt. 4--------#

#10. Sum whitetail and sika, then move those sums to county row 

#CAROLINE COUNTY
df_pbutton_19_20.iloc[4, 1] = df_pbutton_19_20.iloc[[5, 6], 1].sum()
df_pbutton_19_20.iloc[4, 2] = df_pbutton_19_20.iloc[[5,6], 2].sum()
df_pbutton_19_20.iloc[4, 3] = df_pbutton_19_20.iloc[[5, 6], 3].sum()

# #Dorchester
df_pbutton_19_20.iloc[10, 1] = df_pbutton_19_20.iloc[[11, 12], 1].sum()
df_pbutton_19_20.iloc[10, 2] = df_pbutton_19_20.iloc[[11,12], 2].sum()
df_pbutton_19_20.iloc[10, 3] = df_pbutton_19_20.iloc[[11, 12], 3].sum()

#Somerset
df_pbutton_19_20.iloc[22, 1] = df_pbutton_19_20.iloc[[23, 24], 1].sum()
df_pbutton_19_20.iloc[22, 2] = df_pbutton_19_20.iloc[[23,24], 2].sum()
df_pbutton_19_20.iloc[22, 3] = df_pbutton_19_20.iloc[[23, 24], 3].sum()

#Wicomico
df_pbutton_19_20.iloc[27, 1] = df_pbutton_19_20.iloc[[28, 29], 1].sum()
df_pbutton_19_20.iloc[27, 2] = df_pbutton_19_20.iloc[[28,29], 2].sum()
df_pbutton_19_20.iloc[27, 3] = df_pbutton_19_20.iloc[[28, 29], 3].sum()

# #Worcester
df_pbutton_19_20.iloc[30, 1] = df_pbutton_19_20.iloc[[31, 32], 1].sum()
df_pbutton_19_20.iloc[30, 2] = df_pbutton_19_20.iloc[[31,32], 2].sum()
df_pbutton_19_20.iloc[30, 3] = df_pbutton_19_20.iloc[[31, 32], 3].sum()

In [117]:
#---------2019-2020 Button Buck and Doe Harvest FINAL CLEANING: DROPPING ROWS---------#
#11. Filter county values for "whitetail" and "sika" and drop those rows
df_pbutton_19_20=df_pbutton_19_20[ df_pbutton_19_20[ "County" ].str.contains( "Whitetail|Sika" )== False]
df_pbutton_19_20= df_pbutton_19_20.reset_index(drop=True)
df_pbutton_19_20.to_csv("df_pbutton_19_20.csv")

In [118]:
#2020-2021 Button buck and doe harvest 

# Open a PDF
pdf = PDF('Maryland-Annual-Deer-Report-2020-2021.pdf')
page = pdf.pages[6]
page.show(width=700)

table = page.extract_table(method="pdfplumber")
list(table)

rows = list(table)

df_pbutton_20_21 = pd.DataFrame(rows)

df_pbutton_20_21.to_csv("df_pbutton_20_21.csv", index=False)

In [119]:
#--------2020-2021 Button Buck and Doe Harvest Cleaning Pt. 1--------#

#1. RENAME COLUMNS BY INDEX
#https://www.geeksforgeeks.org/python/rename-column-by-index-in-pandas/

df_pbutton_20_21.rename(columns={
    df_pbutton_20_21.columns[0]: "County",
    df_pbutton_20_21.columns[1]: "Buttonbuck_2020-21",
    df_pbutton_20_21.columns[2]: "Female_or_Antlerless_2020-21",
    df_pbutton_20_21.columns[3]: "Total_2020-21",
    df_pbutton_20_21.columns[4]: "Percent_Buttonbuck"
    
}, inplace=True)
 
#2. FORMAT OF COUNTY NAMES:
    #strip \n
    #Anne Arundel
    #Prince George's 
    #Queen Anne's
df_pbutton_20_21['County']=df_pbutton_20_21['County'].str.replace("\n", " ")
#https://stackoverflow.com/questions/65666852/why-cant-i-replace-a-newline-in-my-pandas-dataframe
#https://stackoverflow.com/questions/70893764/how-to-change-the-column-type-of-all-columns-except-the-first-in-pandas

#3. Drop percent in buttonbuck
df_pbutton_20_21 = df_pbutton_20_21.drop(df_pbutton_20_21.columns[4], axis=1)

In [120]:
#--------2020-2021 Button Buck and Doe Harvest Cleaning Pt. 2--------#

#4. Replace asterisks and spaces with NaN
df_pbutton_20_21=df_pbutton_20_21.replace(r'^\*$', np.nan, regex=True)
##https://stackoverflow.com/questions/45311262/replace-a-variable-number-of-asterisks-with-nan-in-a-dataframe 

#5. Drop last row, which just has "small sample size" text
df_pbutton_20_21 = df_pbutton_20_21.iloc[:-1]

#6. Drop first row
df_pbutton_20_21.drop(labels=0, inplace=True)

#7. Strip commas
df_pbutton_20_21.replace(',','', regex=True, inplace=True)

,County,Buttonbuck_2020-21,Female_or_Antlerless_2020-21,Total_2020-21
1,Allegany,124,1255,1379
2,Anne Arundel,181,1096,1277
3,Baltimore,410,3165,3575
4,Calvert,131,785,916
5,Caroline,,,
6,Whitetail,295,1599,1894
7,Sika,1,1,2
8,Carroll,515,3491,4006
9,Cecil,327,2203,2530
10,Charles,198,1359,1557
11,Dorchester,,,
12,Whitetail,227,1100,1327
13,Sika,121,1628,1749
14,Frederick,531,3957,4488
15,Garrett,239,1792,2031
16,Harford,309,2062,2371
17,Howard,185,1391,1576
18,Kent,294,1814,2108
19,Montgomery,353,2388,2741
20,Prince George’s,110,853,963
21,Queen Anne’s,340,1981,2321
22,St. Mary’s,201,1063,1264
23,Somerset,,,
24,Whitetail,201,1365,1566
25,Sika,2,7,9
26,Talbot,285,1291,1576
27,Washington,253,2363,2616
28,Wicomico,,,
29,Whitetail,287,2002,2289
30,Sika,13,103,116
31,Worcester,,,
32,Whitetail,399,2263,2662
33,Sika,4,74,78
34,Total,6536,44451,50987

In [121]:
#--------2020-2021 Button Buck and Doe Harvest Cleaning Pt. 3--------#

#8. Change datatype from string to float for numeric avlues 

df_pbutton_20_21['Buttonbuck_2020-21'] = pd.to_numeric( df_pbutton_20_21['Buttonbuck_2020-21'], errors="coerce")
df_pbutton_20_21['Female_or_Antlerless_2020-21'] = pd.to_numeric( df_pbutton_20_21['Female_or_Antlerless_2020-21'], errors="coerce")
df_pbutton_20_21['Total_2020-21'] = pd.to_numeric( df_pbutton_20_21['Total_2020-21'], errors="coerce")

#9. Reset index after dropping rows. 
df_pbutton_20_21 = df_pbutton_20_21.reset_index(drop=True)

In [122]:
df_pbutton_20_21

,County,Buttonbuck_2020-21,Female_or_Antlerless_2020-21,Total_2020-21
0,Allegany,124.0,1255.0,1379.0
1,Anne Arundel,181.0,1096.0,1277.0
2,Baltimore,410.0,3165.0,3575.0
3,Calvert,131.0,785.0,916.0
4,Caroline,NaN,NaN,NaN
5,Whitetail,295.0,1599.0,1894.0
6,Sika,1.0,1.0,2.0
7,Carroll,515.0,3491.0,4006.0
8,Cecil,327.0,2203.0,2530.0
9,Charles,198.0,1359.0,1557.0
10,Dorchester,NaN,NaN,NaN
11,Whitetail,227.0,1100.0,1327.0
12,Sika,121.0,1628.0,1749.0
13,Frederick,531.0,3957.0,4488.0
14,Garrett,239.0,1792.0,2031.0
15,Harford,309.0,2062.0,2371.0
16,Howard,185.0,1391.0,1576.0
17,Kent,294.0,1814.0,2108.0
18,Montgomery,353.0,2388.0,2741.0
19,Prince George’s,110.0,853.0,963.0
20,Queen Anne’s,340.0,1981.0,2321.0
21,St. Mary’s,201.0,1063.0,1264.0
22,Somerset,NaN,NaN,NaN
23,Whitetail,201.0,1365.0,1566.0
24,Sika,2.0,7.0,9.0
25,Talbot,285.0,1291.0,1576.0
26,Washington,253.0,2363.0,2616.0
27,Wicomico,NaN,NaN,NaN
28,Whitetail,287.0,2002.0,2289.0
29,Sika,13.0,103.0,116.0
30,Worcester,NaN,NaN,NaN
31,Whitetail,399.0,2263.0,2662.0
32,Sika,4.0,74.0,78.0
33,Total,6536.0,44451.0,50987.0

In [123]:
#--------2020-2021 Button Buck and Doe Harvest Cleaning Pt. 4--------#

#10. Sum whitetail and sika, then move those sums to county row 

#CAROLINE COUNTY
df_pbutton_20_21.iloc[4, 1] = df_pbutton_20_21.iloc[[5, 6], 1].sum()
df_pbutton_20_21.iloc[4, 2] = df_pbutton_20_21.iloc[[5,6], 2].sum()
df_pbutton_20_21.iloc[4, 3] = df_pbutton_20_21.iloc[[5, 6], 3].sum()

# #Dorchester
df_pbutton_20_21.iloc[10, 1] = df_pbutton_20_21.iloc[[11, 12], 1].sum()
df_pbutton_20_21.iloc[10, 2] = df_pbutton_20_21.iloc[[11,12], 2].sum()
df_pbutton_20_21.iloc[10, 3] = df_pbutton_20_21.iloc[[11, 12], 3].sum()

#Somerset
df_pbutton_20_21.iloc[22, 1] = df_pbutton_20_21.iloc[[23, 24], 1].sum()
df_pbutton_20_21.iloc[22, 2] = df_pbutton_20_21.iloc[[23,24], 2].sum()
df_pbutton_20_21.iloc[22, 3] = df_pbutton_20_21.iloc[[23, 24], 3].sum()

#Wicomico
df_pbutton_20_21.iloc[27, 1] = df_pbutton_20_21.iloc[[28, 29], 1].sum()
df_pbutton_20_21.iloc[27, 2] = df_pbutton_20_21.iloc[[28,29], 2].sum()
df_pbutton_20_21.iloc[27, 3] = df_pbutton_20_21.iloc[[28, 29], 3].sum()

# #Worcester
df_pbutton_20_21.iloc[30, 1] = df_pbutton_20_21.iloc[[31, 32], 1].sum()
df_pbutton_20_21.iloc[30, 2] = df_pbutton_20_21.iloc[[31,32], 2].sum()
df_pbutton_20_21.iloc[30, 3] = df_pbutton_20_21.iloc[[31, 32], 3].sum()

In [124]:
#---------2020-2021 Button Buck and Doe Harvest FINAL CLEANING: DROPPING ROWS---------#
#11. Filter county values for "whitetail" and "sika" and drop those rows
df_pbutton_20_21=df_pbutton_20_21[ df_pbutton_20_21[ "County" ].str.contains( "Whitetail|Sika" )== False]
df_pbutton_20_21= df_pbutton_20_21.reset_index(drop=True)
df_pbutton_20_21.to_csv("df_pbutton_20_21.csv")

In [125]:
#2021-2022 Button buck and doe harvest 

# Open a PDF
pdf = PDF('Maryland-Big-Game-Report-2021-22.pdf')
page = pdf.pages[7]
page.show(width=700)

table = page.extract_table(method="pdfplumber")
list(table)

rows = list(table)

df_pbutton_21_22 = pd.DataFrame(rows)

df_pbutton_21_22.to_csv("df_pbutton_21_22.csv", index=False)

In [126]:
#--------2021-2022 Button Buck and Doe Harvest Cleaning Pt. 1--------#

#1. RENAME COLUMNS BY INDEX
#https://www.geeksforgeeks.org/python/rename-column-by-index-in-pandas/

df_pbutton_21_22.rename(columns={
    df_pbutton_21_22.columns[0]: "County",
    df_pbutton_21_22.columns[1]: "Buttonbuck_2021-22",
    df_pbutton_21_22.columns[2]: "Female_or_Antlerless_2021-22",
    df_pbutton_21_22.columns[3]: "Total_2021-22",
    df_pbutton_21_22.columns[4]: "Percent_Buttonbuck"
    
}, inplace=True)
 
#2. FORMAT OF COUNTY NAMES:
    #strip \n
    #Anne Arundel
    #Prince George's 
    #Queen Anne's
df_pbutton_21_22['County']=df_pbutton_21_22['County'].str.replace("\n", " ")
#https://stackoverflow.com/questions/65666852/why-cant-i-replace-a-newline-in-my-pandas-dataframe
#https://stackoverflow.com/questions/70893764/how-to-change-the-column-type-of-all-columns-except-the-first-in-pandas

#3. Drop percent in buttonbuck
df_pbutton_21_22 = df_pbutton_21_22.drop(df_pbutton_21_22.columns[4], axis=1)

In [127]:
#--------2021-2022 Button Buck and Doe Harvest Cleaning Pt. 2--------#

#4. Replace asterisks and spaces with NaN
df_pbutton_21_22=df_pbutton_21_22.replace(r'^\*$', np.nan, regex=True)
##https://stackoverflow.com/questions/45311262/replace-a-variable-number-of-asterisks-with-nan-in-a-dataframe 

#5. Drop last row, which just has "small sample size" text
df_pbutton_21_22 = df_pbutton_21_22.iloc[:-1]

#6. Drop first row
df_pbutton_21_22.drop(labels=0, inplace=True)

#7. Strip commas
df_pbutton_21_22.replace(',','', regex=True, inplace=True)

,County,Buttonbuck_2021-22,Female_or_Antlerless_2021-22,Total_2021-22
1,Allegany,106,1067,1173
2,Anne Arundel,152,930,1082
3,Baltimore,321,2500,2821
4,Calvert,109,678,787
5,Caroline,253,1323,1576
6,Carroll,362,2651,3013
7,Cecil,259,1737,1996
8,Charles,140,942,1082
9,Dorchester,,,
10,Whitetail,232,1003,1235
11,Sika,97,1606,1703
12,Frederick,336,3078,3414
13,Garrett,151,1327,1478
14,Harford,271,1752,2023
15,Howard,148,1096,1244
16,Kent,268,1686,1954
17,Montgomery,215,1811,2026
18,Prince George’s,114,814,928
19,Queen Anne’s,223,1661,1884
20,St. Mary’s,130,690,820
21,Somerset,,,
22,Whitetail,178,1159,1337
23,Sika,1,7,8
24,Talbot,236,1127,1363
25,Washington,207,1798,2005
26,Wicomico,,,
27,Whitetail,258,1733,1991
28,Sika,10,102,112
29,Worcester,,,
30,Whitetail,328,1927,2255
31,Sika,6,30,36
32,Total,5111,36235,41346

In [128]:
#--------2021-2022 Button Buck and Doe Harvest Cleaning Pt. 3--------#

#8. Change datatype from string to float for numeric avlues 

df_pbutton_21_22['Buttonbuck_2021-22'] = pd.to_numeric( df_pbutton_21_22['Buttonbuck_2021-22'], errors="coerce")
df_pbutton_21_22['Female_or_Antlerless_2021-22'] = pd.to_numeric( df_pbutton_21_22['Female_or_Antlerless_2021-22'], errors="coerce")
df_pbutton_21_22['Total_2021-22'] = pd.to_numeric( df_pbutton_21_22['Total_2021-22'], errors="coerce")

#9. Reset index after dropping rows. 
df_pbutton_21_22 = df_pbutton_21_22.reset_index(drop=True)

In [129]:
df_pbutton_21_22

,County,Buttonbuck_2021-22,Female_or_Antlerless_2021-22,Total_2021-22
0,Allegany,106.0,1067.0,1173.0
1,Anne Arundel,152.0,930.0,1082.0
2,Baltimore,321.0,2500.0,2821.0
3,Calvert,109.0,678.0,787.0
4,Caroline,253.0,1323.0,1576.0
5,Carroll,362.0,2651.0,3013.0
6,Cecil,259.0,1737.0,1996.0
7,Charles,140.0,942.0,1082.0
8,Dorchester,NaN,NaN,NaN
9,Whitetail,232.0,1003.0,1235.0
10,Sika,97.0,1606.0,1703.0
11,Frederick,336.0,3078.0,3414.0
12,Garrett,151.0,1327.0,1478.0
13,Harford,271.0,1752.0,2023.0
14,Howard,148.0,1096.0,1244.0
15,Kent,268.0,1686.0,1954.0
16,Montgomery,215.0,1811.0,2026.0
17,Prince George’s,114.0,814.0,928.0
18,Queen Anne’s,223.0,1661.0,1884.0
19,St. Mary’s,130.0,690.0,820.0
20,Somerset,NaN,NaN,NaN
21,Whitetail,178.0,1159.0,1337.0
22,Sika,1.0,7.0,8.0
23,Talbot,236.0,1127.0,1363.0
24,Washington,207.0,1798.0,2005.0
25,Wicomico,NaN,NaN,NaN
26,Whitetail,258.0,1733.0,1991.0
27,Sika,10.0,102.0,112.0
28,Worcester,NaN,NaN,NaN
29,Whitetail,328.0,1927.0,2255.0
30,Sika,6.0,30.0,36.0
31,Total,5111.0,36235.0,41346.0

In [130]:
#--------2021-2022 Button Buck and Doe Harvest Cleaning Pt. 4--------#

#10. Sum whitetail and sika, then move those sums to county row 
#CAROLINE COUNTY DIDN'T HAVE WHITETAIL AND SIKA DISTINCTION IN 2021-2022 REPORT 

# #Dorchester
df_pbutton_21_22.iloc[8, 1] = df_pbutton_21_22.iloc[[9, 10], 1].sum()
df_pbutton_21_22.iloc[8, 2] = df_pbutton_21_22.iloc[[9,10], 2].sum()
df_pbutton_21_22.iloc[8, 3] = df_pbutton_21_22.iloc[[9, 10], 3].sum()

#Somerset
df_pbutton_21_22.iloc[20, 1] = df_pbutton_21_22.iloc[[21, 22], 1].sum()
df_pbutton_21_22.iloc[20, 2] = df_pbutton_21_22.iloc[[21,22], 2].sum()
df_pbutton_21_22.iloc[20, 3] = df_pbutton_21_22.iloc[[21, 22], 3].sum()

#Wicomico
df_pbutton_21_22.iloc[25, 1] = df_pbutton_21_22.iloc[[26, 27], 1].sum()
df_pbutton_21_22.iloc[25, 2] = df_pbutton_21_22.iloc[[26,27], 2].sum()
df_pbutton_21_22.iloc[25, 3] = df_pbutton_21_22.iloc[[26, 27], 3].sum()

# #Worcester
df_pbutton_21_22.iloc[28, 1] = df_pbutton_21_22.iloc[[29, 30], 1].sum()
df_pbutton_21_22.iloc[28, 2] = df_pbutton_21_22.iloc[[29,30], 2].sum()
df_pbutton_21_22.iloc[28, 3] = df_pbutton_21_22.iloc[[29, 30], 3].sum()

In [131]:
df_pbutton_21_22

,County,Buttonbuck_2021-22,Female_or_Antlerless_2021-22,Total_2021-22
0,Allegany,106.0,1067.0,1173.0
1,Anne Arundel,152.0,930.0,1082.0
2,Baltimore,321.0,2500.0,2821.0
3,Calvert,109.0,678.0,787.0
4,Caroline,253.0,1323.0,1576.0
5,Carroll,362.0,2651.0,3013.0
6,Cecil,259.0,1737.0,1996.0
7,Charles,140.0,942.0,1082.0
8,Dorchester,329.0,2609.0,2938.0
9,Whitetail,232.0,1003.0,1235.0
10,Sika,97.0,1606.0,1703.0
11,Frederick,336.0,3078.0,3414.0
12,Garrett,151.0,1327.0,1478.0
13,Harford,271.0,1752.0,2023.0
14,Howard,148.0,1096.0,1244.0
15,Kent,268.0,1686.0,1954.0
16,Montgomery,215.0,1811.0,2026.0
17,Prince George’s,114.0,814.0,928.0
18,Queen Anne’s,223.0,1661.0,1884.0
19,St. Mary’s,130.0,690.0,820.0
20,Somerset,179.0,1166.0,1345.0
21,Whitetail,178.0,1159.0,1337.0
22,Sika,1.0,7.0,8.0
23,Talbot,236.0,1127.0,1363.0
24,Washington,207.0,1798.0,2005.0
25,Wicomico,268.0,1835.0,2103.0
26,Whitetail,258.0,1733.0,1991.0
27,Sika,10.0,102.0,112.0
28,Worcester,334.0,1957.0,2291.0
29,Whitetail,328.0,1927.0,2255.0
30,Sika,6.0,30.0,36.0
31,Total,5111.0,36235.0,41346.0

In [132]:
#---------2021-2022 Button Buck and Doe Harvest FINAL CLEANING: DROPPING ROWS---------#
#11. Filter county values for "whitetail" and "sika" and drop those rows
df_pbutton_21_22=df_pbutton_21_22[ df_pbutton_21_22[ "County" ].str.contains( "Whitetail|Sika" )== False]
df_pbutton_21_22= df_pbutton_21_22.reset_index(drop=True)
df_pbutton_21_22.to_csv("df_pbutton_21_22.csv")

In [133]:
#2022-2023 Button buck and doe harvest 

# Open a PDF
pdf = PDF('Maryland-Big-Game-Report-2022-2023.pdf')
page = pdf.pages[7]
page.show(width=700)

table = page.extract_table(method="pdfplumber")
list(table)

rows = list(table)

df_pbutton_22_23 = pd.DataFrame(rows)

df_pbutton_22_23.to_csv("df_pbutton_22_23.csv", index=False)

In [134]:
#--------2022-2023 Button Buck and Doe Harvest Cleaning Pt. 1--------#

#1. RENAME COLUMNS BY INDEX
#https://www.geeksforgeeks.org/python/rename-column-by-index-in-pandas/

df_pbutton_22_23.rename(columns={
    df_pbutton_22_23.columns[0]: "County",
    df_pbutton_22_23.columns[1]: "Buttonbuck_2022-23",
    df_pbutton_22_23.columns[2]: "Female_or_Antlerless_2022-23",
    df_pbutton_22_23.columns[3]: "Total_2022-23",
    df_pbutton_22_23.columns[4]: "Percent_Buttonbuck"
    
}, inplace=True)
 
#2. FORMAT OF COUNTY NAMES:
    #strip \n
    #Anne Arundel
    #Prince George's 
    #Queen Anne's
df_pbutton_22_23['County']=df_pbutton_22_23['County'].str.replace("\n", " ")
#https://stackoverflow.com/questions/65666852/why-cant-i-replace-a-newline-in-my-pandas-dataframe
#https://stackoverflow.com/questions/70893764/how-to-change-the-column-type-of-all-columns-except-the-first-in-pandas

#3. Drop percent in buttonbuck
df_pbutton_22_23 = df_pbutton_22_23.drop(df_pbutton_22_23.columns[4], axis=1)

In [135]:
#--------2022-2023 Button Buck and Doe Harvest Cleaning Pt. 2--------#

#4. Replace asterisks and spaces with NaN
df_pbutton_22_23=df_pbutton_22_23.replace(r'^\*$', np.nan, regex=True)
##https://stackoverflow.com/questions/45311262/replace-a-variable-number-of-asterisks-with-nan-in-a-dataframe 

#5. Drop last row, which just has "small sample size" text
df_pbutton_22_23 = df_pbutton_22_23.iloc[:-1]

#6. Drop first row
df_pbutton_22_23.drop(labels=0, inplace=True)

#7. Strip commas
df_pbutton_22_23.replace(',','', regex=True, inplace=True)

,County,Buttonbuck_2022-23,Female_or_Antlerless_2022-23,Total_2022-23
1,Allegany,138,1336,1474
2,Anne Arundel,149,934,1083
3,Baltimore,353,2637,2990
4,Calvert,126,753,879
5,Caroline,,,
6,,315,1652,1967
7,,0,1,1
8,Carroll,433,3001,3434
9,Cecil,283,1839,2122
10,Charles,189,1250,1439
11,Dorchester,,,
12,Whitetail,211,1107,1318
13,Sika,121,1896,2017
14,Frederick,417,3626,4043
15,Garrett,178,1698,1876
16,Harford,287,1873,2160
17,Howard,161,1200,1361
18,Kent,288,1802,2090
19,Montgomery,246,1925,2171
20,Prince George’s,80,852,932
21,Queen Anne’s,258,1741,1999
22,St. Mary’s,181,949,1130
23,Somerset,,,
24,Whitetail,178,1035,1213
25,Sika,1,11,12
26,Talbot,219,1065,1284
27,Washington,199,2180,2379
28,Wicomico,,,
29,Whitetail,273,1391,1664
30,Sika,16,131,147
31,Worcester,,,
32,Whitetail,300,1564,1864
33,Sika,4,44,48
34,Total,5604,39493,45097

In [136]:
#--------2022-2023 Button Buck and Doe Harvest Cleaning Pt. 3--------#

#8. Change datatype from string to float for numeric avlues 

df_pbutton_22_23['Buttonbuck_2022-23'] = pd.to_numeric( df_pbutton_22_23['Buttonbuck_2022-23'], errors="coerce")
df_pbutton_22_23['Female_or_Antlerless_2022-23'] = pd.to_numeric( df_pbutton_22_23['Female_or_Antlerless_2022-23'], errors="coerce")
df_pbutton_22_23['Total_2022-23'] = pd.to_numeric( df_pbutton_22_23['Total_2022-23'], errors="coerce")

#9. Reset index after dropping rows. 
df_pbutton_22_23 = df_pbutton_22_23.reset_index(drop=True)

In [137]:
df_pbutton_22_23

,County,Buttonbuck_2022-23,Female_or_Antlerless_2022-23,Total_2022-23
0,Allegany,138.0,1336.0,1474.0
1,Anne Arundel,149.0,934.0,1083.0
2,Baltimore,353.0,2637.0,2990.0
3,Calvert,126.0,753.0,879.0
4,Caroline,NaN,NaN,NaN
5,,315.0,1652.0,1967.0
6,,0.0,1.0,1.0
7,Carroll,433.0,3001.0,3434.0
8,Cecil,283.0,1839.0,2122.0
9,Charles,189.0,1250.0,1439.0
10,Dorchester,NaN,NaN,NaN
11,Whitetail,211.0,1107.0,1318.0
12,Sika,121.0,1896.0,2017.0
13,Frederick,417.0,3626.0,4043.0
14,Garrett,178.0,1698.0,1876.0
15,Harford,287.0,1873.0,2160.0
16,Howard,161.0,1200.0,1361.0
17,Kent,288.0,1802.0,2090.0
18,Montgomery,246.0,1925.0,2171.0
19,Prince George’s,80.0,852.0,932.0
20,Queen Anne’s,258.0,1741.0,1999.0
21,St. Mary’s,181.0,949.0,1130.0
22,Somerset,NaN,NaN,NaN
23,Whitetail,178.0,1035.0,1213.0
24,Sika,1.0,11.0,12.0
25,Talbot,219.0,1065.0,1284.0
26,Washington,199.0,2180.0,2379.0
27,Wicomico,NaN,NaN,NaN
28,Whitetail,273.0,1391.0,1664.0
29,Sika,16.0,131.0,147.0
30,Worcester,NaN,NaN,NaN
31,Whitetail,300.0,1564.0,1864.0
32,Sika,4.0,44.0,48.0
33,Total,5604.0,39493.0,45097.0

In [138]:
#--------2022-2023 Button Buck and Doe Harvest Cleaning Pt. 4--------#

#10. Sum whitetail and sika, then move those sums to county row 

#CAROLINE COUNTY
df_pbutton_22_23.iloc[4, 1] = df_pbutton_22_23.iloc[[5, 6], 1].sum()
df_pbutton_22_23.iloc[4, 2] = df_pbutton_22_23.iloc[[5,6], 2].sum()
df_pbutton_22_23.iloc[4, 3] = df_pbutton_22_23.iloc[[5, 6], 3].sum()

# #Dorchester
df_pbutton_22_23.iloc[10, 1] = df_pbutton_22_23.iloc[[11, 12], 1].sum()
df_pbutton_22_23.iloc[10, 2] = df_pbutton_22_23.iloc[[11,12], 2].sum()
df_pbutton_22_23.iloc[10, 3] = df_pbutton_22_23.iloc[[11, 12], 3].sum()

#Somerset
df_pbutton_22_23.iloc[22, 1] = df_pbutton_22_23.iloc[[23, 24], 1].sum()
df_pbutton_22_23.iloc[22, 2] = df_pbutton_22_23.iloc[[23,24], 2].sum()
df_pbutton_22_23.iloc[22, 3] = df_pbutton_22_23.iloc[[23, 24], 3].sum()

#Wicomico
df_pbutton_22_23.iloc[27, 1] = df_pbutton_22_23.iloc[[28, 29], 1].sum()
df_pbutton_22_23.iloc[27, 2] = df_pbutton_22_23.iloc[[28,29], 2].sum()
df_pbutton_22_23.iloc[27, 3] = df_pbutton_22_23.iloc[[28, 29], 3].sum()

# #Worcester
df_pbutton_22_23.iloc[30, 1] = df_pbutton_22_23.iloc[[31, 32], 1].sum()
df_pbutton_22_23.iloc[30, 2] = df_pbutton_22_23.iloc[[31,32], 2].sum()
df_pbutton_22_23.iloc[30, 3] = df_pbutton_22_23.iloc[[31, 32], 3].sum()

In [139]:
#---------2022-2023 Button Buck and Doe Harvest FINAL CLEANING: DROPPING ROWS---------#
#11. Filter county values for "whitetail" and "sika" and drop those rows
df_pbutton_22_23=df_pbutton_22_23[ df_pbutton_22_23[ "County" ].str.contains( "Whitetail|Sika" )== False]
df_pbutton_22_23= df_pbutton_22_23.reset_index(drop=True)
df_pbutton_22_23.to_csv("df_pbutton_22_23.csv")

In [140]:
df_pbutton_22_23

,County,Buttonbuck_2022-23,Female_or_Antlerless_2022-23,Total_2022-23
0,Allegany,138.0,1336.0,1474.0
1,Anne Arundel,149.0,934.0,1083.0
2,Baltimore,353.0,2637.0,2990.0
3,Calvert,126.0,753.0,879.0
4,Caroline,315.0,1653.0,1968.0
5,,315.0,1652.0,1967.0
6,,0.0,1.0,1.0
7,Carroll,433.0,3001.0,3434.0
8,Cecil,283.0,1839.0,2122.0
9,Charles,189.0,1250.0,1439.0
10,Dorchester,332.0,3003.0,3335.0
11,Frederick,417.0,3626.0,4043.0
12,Garrett,178.0,1698.0,1876.0
13,Harford,287.0,1873.0,2160.0
14,Howard,161.0,1200.0,1361.0
15,Kent,288.0,1802.0,2090.0
16,Montgomery,246.0,1925.0,2171.0
17,Prince George’s,80.0,852.0,932.0
18,Queen Anne’s,258.0,1741.0,1999.0
19,St. Mary’s,181.0,949.0,1130.0
20,Somerset,179.0,1046.0,1225.0
21,Talbot,219.0,1065.0,1284.0
22,Washington,199.0,2180.0,2379.0
23,Wicomico,289.0,1522.0,1811.0
24,Worcester,304.0,1608.0,1912.0
25,Total,5604.0,39493.0,45097.0

In [141]:
#---------2022-2023 Button Buck and Doe Harvest FINAL CLEANING: DROPPING ROWS---------#
#12. One additional step bc Caroline county doesn't have labeled whitetail and sika rows for this table 

#drop rows 5 and 6

df_pbutton_22_23 = df_pbutton_22_23.drop(df_pbutton_22_23.index[[5,6]])
df_pbutton_22_23= df_pbutton_22_23.reset_index(drop=True)

In [142]:
df_pbutton_22_23.to_csv("df_pbutton_22_23.csv")

In [143]:
#2023-2024 Button buck and doe harvest 

# Open a PDF
pdf = PDF('maryland-Big-Game-Report_2023-24.pdf')
page = pdf.pages[5]
page.show(width=700)

table = page.extract_table(method="pdfplumber")
list(table)

rows = list(table)

df_pbutton_23_24 = pd.DataFrame(rows)

df_pbutton_23_24.to_csv("df_pbutton_23_24.csv", index=False)

In [144]:
#--------2023-2024 Button Buck and Doe Harvest Cleaning Pt. 1--------#

#1. RENAME COLUMNS BY INDEX
#https://www.geeksforgeeks.org/python/rename-column-by-index-in-pandas/

df_pbutton_23_24.rename(columns={
    df_pbutton_23_24.columns[0]: "County",
    df_pbutton_23_24.columns[1]: "Buttonbuck_2023-24",
    df_pbutton_23_24.columns[2]: "Female_or_Antlerless_2023-24",
    df_pbutton_23_24.columns[3]: "Total_2023-24",
    df_pbutton_23_24.columns[4]: "Percent_Buttonbuck"
    
}, inplace=True)
 
#2. FORMAT OF COUNTY NAMES:
    #strip \n
    #Anne Arundel
    #Prince George's 
    #Queen Anne's
df_pbutton_23_24['County']=df_pbutton_23_24['County'].str.replace("\n", " ")
#https://stackoverflow.com/questions/65666852/why-cant-i-replace-a-newline-in-my-pandas-dataframe
#https://stackoverflow.com/questions/70893764/how-to-change-the-column-type-of-all-columns-except-the-first-in-pandas

#3. Drop percent in buttonbuck
df_pbutton_23_24 = df_pbutton_23_24.drop(df_pbutton_23_24.columns[4], axis=1)

In [145]:
#--------2023-2024 Button Buck and Doe Harvest Cleaning Pt. 2--------#

#4. Replace asterisks and spaces with NaN
df_pbutton_23_24=df_pbutton_23_24.replace(r'^\*$', np.nan, regex=True)
##https://stackoverflow.com/questions/45311262/replace-a-variable-number-of-asterisks-with-nan-in-a-dataframe 

#5. Drop last row, which just has "small sample size" text
df_pbutton_23_24 = df_pbutton_23_24.iloc[:-1]

#6. Drop first row
df_pbutton_23_24.drop(labels=0, inplace=True)

#7. Strip commas
df_pbutton_23_24.replace(',','', regex=True, inplace=True)

,County,Buttonbuck_2023-24,Female_or_Antlerless_2023-24,Total_2023-24
1,Allegany,99,1029,1128
2,Anne Arundel,131,843,974
3,Baltimore,286,2365,2651
4,Calvert,114,703,817
5,Caroline,,,
6,Whitetail,246,1420,1666
7,Sika,,1,1
8,Carroll,439,2820,3259
9,Cecil,203,1641,1844
10,Charles,157,1226,1383
11,Dorchester,,,
12,Whitetail,186,952,1138
13,Sika,96,1869,1965
14,Frederick,358,3248,3606
15,Garrett,192,1764,1956
16,Harford,264,1659,1923
17,Howard,163,1096,1259
18,Kent,196,1477,1673
19,Montgomery,215,1831,2046
20,Prince George’s,103,675,778
21,Queen Anne’s,234,1555,1789
22,Somerset,,,
23,Whitetail,151,907,1058
24,Sika,1,14,15
25,St. Mary’s,186,930,1116
26,Talbot,199,1010,1209
27,Washington,225,1920,2145
28,Wicomico,,,
29,Whitetail,239,1255,1494
30,Sika,9,152,161
31,Worcester,,,
32,Whitetail,225,1374,1599
33,Sika,8,44,52
34,Total,4925,35780,40705

In [146]:
#--------2023-2024 Button Buck and Doe Harvest Cleaning Pt. 3--------#

#8. Change datatype from string to float for numeric avlues 

df_pbutton_23_24['Buttonbuck_2023-24'] = pd.to_numeric( df_pbutton_23_24['Buttonbuck_2023-24'], errors="coerce")
df_pbutton_23_24['Female_or_Antlerless_2023-24'] = pd.to_numeric( df_pbutton_23_24['Female_or_Antlerless_2023-24'], errors="coerce")
df_pbutton_23_24['Total_2023-24'] = pd.to_numeric( df_pbutton_23_24['Total_2023-24'], errors="coerce")

#9. Reset index after dropping rows. 
df_pbutton_23_24 = df_pbutton_23_24.reset_index(drop=True)

In [147]:
df_pbutton_23_24

,County,Buttonbuck_2023-24,Female_or_Antlerless_2023-24,Total_2023-24
0,Allegany,99.0,1029.0,1128.0
1,Anne Arundel,131.0,843.0,974.0
2,Baltimore,286.0,2365.0,2651.0
3,Calvert,114.0,703.0,817.0
4,Caroline,NaN,NaN,NaN
5,Whitetail,246.0,1420.0,1666.0
6,Sika,NaN,1.0,1.0
7,Carroll,439.0,2820.0,3259.0
8,Cecil,203.0,1641.0,1844.0
9,Charles,157.0,1226.0,1383.0
10,Dorchester,NaN,NaN,NaN
11,Whitetail,186.0,952.0,1138.0
12,Sika,96.0,1869.0,1965.0
13,Frederick,358.0,3248.0,3606.0
14,Garrett,192.0,1764.0,1956.0
15,Harford,264.0,1659.0,1923.0
16,Howard,163.0,1096.0,1259.0
17,Kent,196.0,1477.0,1673.0
18,Montgomery,215.0,1831.0,2046.0
19,Prince George’s,103.0,675.0,778.0
20,Queen Anne’s,234.0,1555.0,1789.0
21,Somerset,NaN,NaN,NaN
22,Whitetail,151.0,907.0,1058.0
23,Sika,1.0,14.0,15.0
24,St. Mary’s,186.0,930.0,1116.0
25,Talbot,199.0,1010.0,1209.0
26,Washington,225.0,1920.0,2145.0
27,Wicomico,NaN,NaN,NaN
28,Whitetail,239.0,1255.0,1494.0
29,Sika,9.0,152.0,161.0
30,Worcester,NaN,NaN,NaN
31,Whitetail,225.0,1374.0,1599.0
32,Sika,8.0,44.0,52.0
33,Total,4925.0,35780.0,40705.0

In [148]:
#--------2023-2024 Button Buck and Doe Harvest Cleaning Pt. 4--------#

#10. Sum whitetail and sika, then move those sums to county row 

#CAROLINE COUNTY
df_pbutton_23_24.iloc[4, 1] = df_pbutton_23_24.iloc[[5, 6], 1].sum()
df_pbutton_23_24.iloc[4, 2] = df_pbutton_23_24.iloc[[5,6], 2].sum()
df_pbutton_23_24.iloc[4, 3] = df_pbutton_23_24.iloc[[5, 6], 3].sum()

# #Dorchester
df_pbutton_23_24.iloc[10, 1] = df_pbutton_23_24.iloc[[11, 12], 1].sum()
df_pbutton_23_24.iloc[10, 2] = df_pbutton_23_24.iloc[[11,12], 2].sum()
df_pbutton_23_24.iloc[10, 3] = df_pbutton_23_24.iloc[[11, 12], 3].sum()

#Somerset
df_pbutton_23_24.iloc[21, 1] = df_pbutton_23_24.iloc[[22, 23], 1].sum()
df_pbutton_23_24.iloc[21, 2] = df_pbutton_23_24.iloc[[22,23], 2].sum()
df_pbutton_23_24.iloc[21, 3] = df_pbutton_23_24.iloc[[22, 23], 3].sum()

#Wicomico
df_pbutton_23_24.iloc[27, 1] = df_pbutton_23_24.iloc[[28, 29], 1].sum()
df_pbutton_23_24.iloc[27, 2] = df_pbutton_23_24.iloc[[28,29], 2].sum()
df_pbutton_23_24.iloc[27, 3] = df_pbutton_23_24.iloc[[28, 29], 3].sum()

# #Worcester
df_pbutton_23_24.iloc[30, 1] = df_pbutton_23_24.iloc[[31, 32], 1].sum()
df_pbutton_23_24.iloc[30, 2] = df_pbutton_23_24.iloc[[31,32], 2].sum()
df_pbutton_23_24.iloc[30, 3] = df_pbutton_23_24.iloc[[31, 32], 3].sum()

In [149]:
#---------2023-2024 Button Buck and Doe Harvest FINAL CLEANING: DROPPING ROWS---------#
#11. Filter county values for "whitetail" and "sika" and drop those rows
df_pbutton_23_24=df_pbutton_23_24[ df_pbutton_23_24[ "County" ].str.contains( "Whitetail|Sika" )== False]
df_pbutton_23_24= df_pbutton_23_24.reset_index(drop=True)
df_pbutton_23_24.to_csv("df_pbutton_23_24.csv")

In [150]:
#2024-2025 Button buck and doe harvest 

# Open a PDF
pdf = PDF('maryland-Big-Game-Report_2024-25.pdf')
page = pdf.pages[7]
page.show(width=700)


table = page.extract_table(method="pdfplumber")
list(table)

rows = list(table)

df_pbutton_24_25 = pd.DataFrame(rows)

df_pbutton_24_25.to_csv("df_pbutton_24_25.csv", index=False)

In [151]:
df_pbutton_24_25

                  0           1                      2       3             4
0            County  Buttonbuck  Female or\nantlerless   Total  % Buttonbuck
1          Allegany         144                  1,400   1,544           9.3
2      Anne Arundel         189                  1,182   1,371          13.8
3         Baltimore         307                  2,823   3,130           9.8
4           Calvert         122                    940   1,062          11.5
5          Caroline
6      White-Tailed         314                  1,948   2,262          13.9
7              Sika           0                      2       2             0
8           Carroll         437                  3,183   3,620          12.1
9             Cecil         283                  1,977   2,260          12.5
10          Charles         208                  1,804   2,012          10.3
11       Dorchester
12     White-Tailed         222                  1,056   1,278          17.4
13             Sika         115                  2,204   2,319             5
14        Frederick         375                  3,482   3,857           9.7
15          Garrett         232                  2,143   2,375           9.8
16          Harford         287                  2,127   2,414          11.9
17           Howard         122                  1,207   1,329           9.2
18             Kent         293                  1,991   2,284          12.8
19       Montgomery         238                  1,847   2,085          11.4
20  Prince George's         117                    934   1,051          11.1
21     Queen Anne's         317                  2,237   2,554          12.4
22         Somerset
23     White-Tailed         154                  1,219   1,373          11.2
24             Sika           2                      9      11          18.2
25       St. Mary's         211                  1,259   1,470          14.4
26           Talbot         316                  1,241   1,557          20.3
27       Washington         248                  2,341   2,589           9.6
28         Wicomico
29     White-Tailed         266                  1,566   1,832          14.5
30             Sika          11                    216     227           4.8
31        Worcester
32     White-Tailed         260                  1,702   1,962          13.3
33             Sika          16                     64      80            20
34            Total       5,806                 44,104  49,910           8.6

In [152]:
#--------2024-2025 Button Buck and Doe Harvest Cleaning Pt. 1--------#

#1. RENAME COLUMNS BY INDEX
#https://www.geeksforgeeks.org/python/rename-column-by-index-in-pandas/

df_pbutton_24_25.rename(columns={
    df_pbutton_24_25.columns[0]: "County",
    df_pbutton_24_25.columns[1]: "Buttonbuck_2024-25",
    df_pbutton_24_25.columns[2]: "Female_or_Antlerless_2024-25",
    df_pbutton_24_25.columns[3]: "Total_2024-25",
    df_pbutton_24_25.columns[4]: "Percent_Buttonbuck"
    
}, inplace=True)
 
#2. FORMAT OF COUNTY NAMES:
    #strip \n
    #Anne Arundel
    #Prince George's 
    #Queen Anne's
df_pbutton_24_25['County']=df_pbutton_24_25['County'].str.replace("\n", " ")
#https://stackoverflow.com/questions/65666852/why-cant-i-replace-a-newline-in-my-pandas-dataframe
#https://stackoverflow.com/questions/70893764/how-to-change-the-column-type-of-all-columns-except-the-first-in-pandas

#3. Drop percent in buttonbuck
df_pbutton_24_25 = df_pbutton_24_25.drop(df_pbutton_24_25.columns[4], axis=1)

In [153]:
df_pbutton_24_25

,County,Buttonbuck_2024-25,Female_or_Antlerless_2024-25,Total_2024-25
0,County,Buttonbuck,Female or\nantlerless,Total
1,Allegany,144,"1,400","1,544"
2,Anne Arundel,189,"1,182","1,371"
3,Baltimore,307,"2,823","3,130"
4,Calvert,122,940,"1,062"
5,Caroline,,,
6,White-Tailed,314,"1,948","2,262"
7,Sika,0,2,2
8,Carroll,437,"3,183","3,620"
9,Cecil,283,"1,977","2,260"
10,Charles,208,"1,804","2,012"
11,Dorchester,,,
12,White-Tailed,222,"1,056","1,278"
13,Sika,115,"2,204","2,319"
14,Frederick,375,"3,482","3,857"
15,Garrett,232,"2,143","2,375"
16,Harford,287,"2,127","2,414"
17,Howard,122,"1,207","1,329"
18,Kent,293,"1,991","2,284"
19,Montgomery,238,"1,847","2,085"
20,Prince George's,117,934,"1,051"
21,Queen Anne's,317,"2,237","2,554"
22,Somerset,,,
23,White-Tailed,154,"1,219","1,373"
24,Sika,2,9,11
25,St. Mary's,211,"1,259","1,470"
26,Talbot,316,"1,241","1,557"
27,Washington,248,"2,341","2,589"
28,Wicomico,,,
29,White-Tailed,266,"1,566","1,832"
30,Sika,11,216,227
31,Worcester,,,
32,White-Tailed,260,"1,702","1,962"
33,Sika,16,64,80
34,Total,"5,806","44,104","49,910"

In [154]:
#--------2024-2025 Button Buck and Doe Harvest Cleaning Pt. 2--------#

#4. Replace asterisks and spaces with NaN
df_pbutton_24_25=df_pbutton_24_25.replace(r'^\*$', np.nan, regex=True)
##https://stackoverflow.com/questions/45311262/replace-a-variable-number-of-asterisks-with-nan-in-a-dataframe

In [155]:
df_pbutton_24_25

,County,Buttonbuck_2024-25,Female_or_Antlerless_2024-25,Total_2024-25
0,County,Buttonbuck,Female or\nantlerless,Total
1,Allegany,144,"1,400","1,544"
2,Anne Arundel,189,"1,182","1,371"
3,Baltimore,307,"2,823","3,130"
4,Calvert,122,940,"1,062"
5,Caroline,,,
6,White-Tailed,314,"1,948","2,262"
7,Sika,0,2,2
8,Carroll,437,"3,183","3,620"
9,Cecil,283,"1,977","2,260"
10,Charles,208,"1,804","2,012"
11,Dorchester,,,
12,White-Tailed,222,"1,056","1,278"
13,Sika,115,"2,204","2,319"
14,Frederick,375,"3,482","3,857"
15,Garrett,232,"2,143","2,375"
16,Harford,287,"2,127","2,414"
17,Howard,122,"1,207","1,329"
18,Kent,293,"1,991","2,284"
19,Montgomery,238,"1,847","2,085"
20,Prince George's,117,934,"1,051"
21,Queen Anne's,317,"2,237","2,554"
22,Somerset,,,
23,White-Tailed,154,"1,219","1,373"
24,Sika,2,9,11
25,St. Mary's,211,"1,259","1,470"
26,Talbot,316,"1,241","1,557"
27,Washington,248,"2,341","2,589"
28,Wicomico,,,
29,White-Tailed,266,"1,566","1,832"
30,Sika,11,216,227
31,Worcester,,,
32,White-Tailed,260,"1,702","1,962"
33,Sika,16,64,80
34,Total,"5,806","44,104","49,910"

In [156]:
#4. LAST ROW ENDS WITH TOTAL FOR 2024-2025 REPORT, NOT NOTE ABOUT SMALL SAMPLE SIZE, SO DON'T HAVE TO DROP.SKIP 

#6. Drop first row
df_pbutton_24_25.drop(labels=0, inplace=True)

#7. Strip commas
df_pbutton_24_25.replace(',','', regex=True, inplace=True)

,County,Buttonbuck_2024-25,Female_or_Antlerless_2024-25,Total_2024-25
1,Allegany,144,1400,1544
2,Anne Arundel,189,1182,1371
3,Baltimore,307,2823,3130
4,Calvert,122,940,1062
5,Caroline,,,
6,White-Tailed,314,1948,2262
7,Sika,0,2,2
8,Carroll,437,3183,3620
9,Cecil,283,1977,2260
10,Charles,208,1804,2012
11,Dorchester,,,
12,White-Tailed,222,1056,1278
13,Sika,115,2204,2319
14,Frederick,375,3482,3857
15,Garrett,232,2143,2375
16,Harford,287,2127,2414
17,Howard,122,1207,1329
18,Kent,293,1991,2284
19,Montgomery,238,1847,2085
20,Prince George's,117,934,1051
21,Queen Anne's,317,2237,2554
22,Somerset,,,
23,White-Tailed,154,1219,1373
24,Sika,2,9,11
25,St. Mary's,211,1259,1470
26,Talbot,316,1241,1557
27,Washington,248,2341,2589
28,Wicomico,,,
29,White-Tailed,266,1566,1832
30,Sika,11,216,227
31,Worcester,,,
32,White-Tailed,260,1702,1962
33,Sika,16,64,80
34,Total,5806,44104,49910

In [157]:
#--------2016-2017 Button Buck and Doe Harvest Cleaning Pt. 3--------#

#8. Change datatype from string to float for numeric avlues 

df_pbutton_24_25['Buttonbuck_2024-25'] = pd.to_numeric( df_pbutton_24_25['Buttonbuck_2024-25'], errors="coerce")
df_pbutton_24_25['Female_or_Antlerless_2024-25'] = pd.to_numeric( df_pbutton_24_25['Female_or_Antlerless_2024-25'], errors="coerce")
df_pbutton_24_25['Total_2024-25'] = pd.to_numeric( df_pbutton_24_25['Total_2024-25'], errors="coerce")

#9. Reset index after dropping rows. 
df_pbutton_24_25 = df_pbutton_24_25.reset_index(drop=True)

In [158]:
df_pbutton_24_25

,County,Buttonbuck_2024-25,Female_or_Antlerless_2024-25,Total_2024-25
0,Allegany,144.0,1400.0,1544.0
1,Anne Arundel,189.0,1182.0,1371.0
2,Baltimore,307.0,2823.0,3130.0
3,Calvert,122.0,940.0,1062.0
4,Caroline,NaN,NaN,NaN
5,White-Tailed,314.0,1948.0,2262.0
6,Sika,0.0,2.0,2.0
7,Carroll,437.0,3183.0,3620.0
8,Cecil,283.0,1977.0,2260.0
9,Charles,208.0,1804.0,2012.0
10,Dorchester,NaN,NaN,NaN
11,White-Tailed,222.0,1056.0,1278.0
12,Sika,115.0,2204.0,2319.0
13,Frederick,375.0,3482.0,3857.0
14,Garrett,232.0,2143.0,2375.0
15,Harford,287.0,2127.0,2414.0
16,Howard,122.0,1207.0,1329.0
17,Kent,293.0,1991.0,2284.0
18,Montgomery,238.0,1847.0,2085.0
19,Prince George's,117.0,934.0,1051.0
20,Queen Anne's,317.0,2237.0,2554.0
21,Somerset,NaN,NaN,NaN
22,White-Tailed,154.0,1219.0,1373.0
23,Sika,2.0,9.0,11.0
24,St. Mary's,211.0,1259.0,1470.0
25,Talbot,316.0,1241.0,1557.0
26,Washington,248.0,2341.0,2589.0
27,Wicomico,NaN,NaN,NaN
28,White-Tailed,266.0,1566.0,1832.0
29,Sika,11.0,216.0,227.0
30,Worcester,NaN,NaN,NaN
31,White-Tailed,260.0,1702.0,1962.0
32,Sika,16.0,64.0,80.0
33,Total,5806.0,44104.0,49910.0

In [159]:
#--------2024-2025 Button Buck and Doe Harvest Cleaning Pt. 4--------#

#10. Sum whitetail and sika, then move those sums to county row 

#CAROLINE COUNTY
df_pbutton_24_25.iloc[4, 1] = df_pbutton_24_25.iloc[[5, 6], 1].sum()
df_pbutton_24_25.iloc[4, 2] = df_pbutton_24_25.iloc[[5,6], 2].sum()
df_pbutton_24_25.iloc[4, 3] = df_pbutton_24_25.iloc[[5, 6], 3].sum()

# #Dorchester
df_pbutton_24_25.iloc[10, 1] = df_pbutton_24_25.iloc[[11, 12], 1].sum()
df_pbutton_24_25.iloc[10, 2] = df_pbutton_24_25.iloc[[11,12], 2].sum()
df_pbutton_24_25.iloc[10, 3] = df_pbutton_24_25.iloc[[11, 12], 3].sum()

#Somerset
df_pbutton_24_25.iloc[21, 1] = df_pbutton_24_25.iloc[[22, 23], 1].sum()
df_pbutton_24_25.iloc[21, 2] = df_pbutton_24_25.iloc[[22,23], 2].sum()
df_pbutton_24_25.iloc[21, 3] = df_pbutton_24_25.iloc[[22, 23], 3].sum()

#Wicomico
df_pbutton_24_25.iloc[27, 1] = df_pbutton_24_25.iloc[[28, 29], 1].sum()
df_pbutton_24_25.iloc[27, 2] = df_pbutton_24_25.iloc[[28,29], 2].sum()
df_pbutton_24_25.iloc[27, 3] = df_pbutton_24_25.iloc[[28, 29], 3].sum()

# #Worcester
df_pbutton_24_25.iloc[30, 1] = df_pbutton_24_25.iloc[[31, 32], 1].sum()
df_pbutton_24_25.iloc[30, 2] = df_pbutton_24_25.iloc[[31,32], 2].sum()
df_pbutton_24_25.iloc[30, 3] = df_pbutton_24_25.iloc[[31, 32], 3].sum()

In [160]:
#---------2024-2025 Button Buck and Doe Harvest FINAL CLEANING: DROPPING ROWS---------#
#11. Filter county values for "whitetail" and "sika" and drop those rows
df_pbutton_24_25=df_pbutton_24_25[ df_pbutton_24_25[ "County" ].str.contains( "White-Tailed|Sika" )== False]
df_pbutton_24_25= df_pbutton_24_25.reset_index(drop=True)
df_pbutton_24_25.to_csv("df_pbutton_24_25.csv")

In [161]:
df_pbutton_24_25

,County,Buttonbuck_2024-25,Female_or_Antlerless_2024-25,Total_2024-25
0,Allegany,144.0,1400.0,1544.0
1,Anne Arundel,189.0,1182.0,1371.0
2,Baltimore,307.0,2823.0,3130.0
3,Calvert,122.0,940.0,1062.0
4,Caroline,314.0,1950.0,2264.0
5,Carroll,437.0,3183.0,3620.0
6,Cecil,283.0,1977.0,2260.0
7,Charles,208.0,1804.0,2012.0
8,Dorchester,337.0,3260.0,3597.0
9,Frederick,375.0,3482.0,3857.0
10,Garrett,232.0,2143.0,2375.0
11,Harford,287.0,2127.0,2414.0
12,Howard,122.0,1207.0,1329.0
13,Kent,293.0,1991.0,2284.0
14,Montgomery,238.0,1847.0,2085.0
15,Prince George's,117.0,934.0,1051.0
16,Queen Anne's,317.0,2237.0,2554.0
17,Somerset,156.0,1228.0,1384.0
18,St. Mary's,211.0,1259.0,1470.0
19,Talbot,316.0,1241.0,1557.0
20,Washington,248.0,2341.0,2589.0
21,Wicomico,277.0,1782.0,2059.0
22,Worcester,276.0,1766.0,2042.0
23,Total,5806.0,44104.0,49910.0

In [162]:
#---------COMBINE BUTTON BUCK AND DOE THROUGH CONCAT, STANDARDIZE LABELS, DOUBLE-CHECK FOR CONSISTENT SPELLING OF COUNTY NAMES---------#

df_pbutton_combined_harvest = pd.concat([df_pbutton_15_16, df_pbutton_16_17, df_pbutton_17_18, df_pbutton_18_19, df_pbutton_19_20,
           df_pbutton_20_21, df_pbutton_21_22, df_pbutton_22_23, df_pbutton_23_24, df_pbutton_24_25])

df_pbutton_combined_harvest.to_csv("df_pbutton_combined_harvest.csv")