In [1]:
##-----Incidence rate data looked pretty clean to my untrained eye, so this notebook mostly includes the analysis I tried to do and that was included in the story-----##

In [2]:
#Spotted Fever Rickettsiosis (SFR)

#1. Read CSV 

import pandas as pd 
df_psfr = pd.read_csv("df_psfr.csv")
df_psfr

      STATEFP STUSPS     NAME  YEAR  CASES      POP       RATE
0           1     AL  Alabama  2000   14.0  4452173   3.144532
1           1     AL  Alabama  2001   18.0  4467634   4.028978
2           1     AL  Alabama  2002   16.0  4480089   3.571358
3           1     AL  Alabama  2003   21.0  4503491   4.663049
4           1     AL  Alabama  2004   54.0  4530729  11.918612
...       ...    ...      ...   ...    ...      ...        ...
1168       56     WY  Wyoming  2018    2.0   577601   3.462598
1169       56     WY  Wyoming  2019    6.0   578759  10.367009
1170       56     WY  Wyoming  2020    1.0   577664   1.731110
1171       56     WY  Wyoming  2021    0.0   579548   0.000000
1172       56     WY  Wyoming  2022    0.0   581629   0.000000

[1173 rows x 7 columns]

In [3]:
#Spotted Fever Rickettsiosis (SFR)

#2. Change incidence rate so that all tickborne diseases are per 1000000 people 
df_psfr['ONE_MILLION_RATE'] = (df_psfr["CASES"] / df_psfr["POP"]) * 1000000

#tried 100,000 but rates were too small to readily see a noticeable pattern.

In [4]:
#Spotted Fever Rickettsiosis (SFR)

#3. Drop "RATE" column from original table and create new dataframe 

df_psfr_updated = df_psfr.drop(["RATE"], axis = 1)

In [5]:
#Spotted Fever Rickettsiosis (SFR)

#4. Subset update dataframe to locate only Maryland's incidence rates and create new datframe just for MD

    #RangeIndex(start=240, stop=252, step=1)
    #https://www.statology.org/pandas-get-row-number/

df_psfr_updated=df_psfr_updated[df_psfr_updated['NAME'] == 'Maryland']

In [6]:
df_psfr_updated

     STATEFP STUSPS      NAME  YEAR  CASES      POP  ONE_MILLION_RATE
460       24     MD  Maryland  2000   19.0  5311034          3.577458
461       24     MD  Maryland  2001   39.0  5374691          7.256231
462       24     MD  Maryland  2002   43.0  5440389          7.903847
463       24     MD  Maryland  2003  106.0  5496269         19.285810
464       24     MD  Maryland  2004   75.0  5546935         13.520981
465       24     MD  Maryland  2005   75.0  5592379         13.411108
466       24     MD  Maryland  2006   93.0  5627367         16.526379
467       24     MD  Maryland  2007   63.0  5653408         11.143721
468       24     MD  Maryland  2008   92.0  5684965         16.183037
469       24     MD  Maryland  2009   40.0  5730388          6.980330
470       24     MD  Maryland  2010   49.0  5788645          8.464848
471       24     MD  Maryland  2011   29.0  5839419          4.966247
472       24     MD  Maryland  2012    9.0  5886992          1.528794
473       24     MD  Maryland  2013    8.0  5923188          1.350624
474       24     MD  Maryland  2014    6.0  5957283          1.007171
475       24     MD  Maryland  2015    4.0  5985562          0.668275
476       24     MD  Maryland  2016    1.0  6003323          0.166574
477       24     MD  Maryland  2017   61.0  6023868         10.126384
478       24     MD  Maryland  2018  106.0  6035802         17.561875
479       24     MD  Maryland  2019  137.0  6045680         22.660809
480       24     MD  Maryland  2020   20.0  6173689          3.239554
481       24     MD  Maryland  2021   14.0  6175045          2.267190
482       24     MD  Maryland  2022   16.0  6163981          2.595725

In [7]:
#Spotted Fever Rickettsiosis (SFR)

#5. Subset MD dataframe to extract incidence rates only from 2015-2022 (to somewhat match harvest data timeline which goes up to 2025)

#2015 begins at row 475 

df_psfr_updated = df_psfr_updated.drop(df_psfr_updated.loc[:474].index)

In [8]:
#Spotted Fever Rickettsiosis (SFR)

#6. Drop columns that don't need to be in chart

df_psfr_updated = df_psfr_updated.drop(["STATEFP", "STUSPS", "NAME", "CASES", 
"POP"], axis = 1)

In [9]:
#Spotted Fever Rickettsiosis (SFR)
#7. Reset Index 
df_psfr_updated=df_psfr_updated.reset_index(drop=True)

In [10]:
#Spotted Fever Rickettsiosis (SFR)
#8. Add disease column for grouped bar chart 
df_psfr_updated=df_psfr_updated.assign(TICKBORNE_DISEASE = "Spotted Fever Rickettsiosis")
#https://stackoverflow.com/questions/44657226/how-to-insert-a-new-column-with-repeated-values-into-a-pandas-table

In [11]:
df_psfr_updated.to_csv("df_psfr_updated.csv", index=False)

#gather incidence rates in millions for other diseases in maryland 2015-2025 and do stacked bar chart

In [12]:
#Anaplasmosis 
#1. Read CSV 

df_pana = pd.read_csv("df_pana.csv")
df_pana

,STATEFP,STUSPS,NAME,YEAR,CASES_A,CASES_EC,POP,RATE_A,RATE_EC
0,1,AL,Alabama,2008,NaN,9.0,4718206,NaN,1.907505
1,1,AL,Alabama,2009,2.0,8.0,4757938,0.420350,1.681401
2,1,AL,Alabama,2010,7.0,12.0,4785437,1.462771,2.507608
3,1,AL,Alabama,2011,4.0,5.0,4799069,0.833495,1.041869
4,1,AL,Alabama,2012,11.0,10.0,4815588,2.284249,2.076590
...,...,...,...,...,...,...,...,...,...
760,56,WY,Wyoming,2018,0.0,0.0,577601,0.000000,0.000000
761,56,WY,Wyoming,2019,0.0,1.0,578759,0.000000,1.727835
762,56,WY,Wyoming,2020,0.0,1.0,577664,0.000000,1.731110
763,56,WY,Wyoming,2021,0.0,0.0,579548,0.000000,0.000000
764,56,WY,Wyoming,2022,0.0,1.0,581629,0.000000,1.719309

In [13]:
#Anaplasmosis 
#2. Change incidence rate so that all tickborne diseases are per 1000000 people 

df_pana['ONE_MILLION_RATE'] = (df_pana["CASES_A"] / df_psfr["POP"]) * 1000000

In [14]:
#Anaplasmosis 

#3. Drop "RATE" column from original table and create new dataframe 

df_pana_updated = df_pana.drop(["RATE_A"], axis = 1)

In [15]:
#Anaplasmosis 

#4. Subset update dataframe to locate only Maryland's incidence rates and create new datframe just for MD

df_pana_updated=df_pana[df_pana['NAME'] == 'Maryland']

In [16]:
df_pana_updated

,STATEFP,STUSPS,NAME,YEAR,CASES_A,CASES_EC,POP,RATE_A,RATE_EC,ONE_MILLION_RATE
300,24,MD,Maryland,2008,4.0,61.0,5684965,0.703610,10.730057,0.320296
301,24,MD,Maryland,2009,1.0,33.0,5730388,0.174508,5.758772,0.079837
302,24,MD,Maryland,2010,15.0,22.0,5788645,2.591280,3.800544,1.194647
303,24,MD,Maryland,2011,7.0,33.0,5839419,1.198749,5.651247,0.556007
304,24,MD,Maryland,2012,5.0,37.0,5886992,0.849330,6.285043,0.396514
305,24,MD,Maryland,2013,5.0,31.0,5923188,0.844140,5.233668,0.395446
306,24,MD,Maryland,2014,2.0,38.0,5957283,0.335724,6.378747,0.157532
307,24,MD,Maryland,2015,4.0,30.0,5985562,0.668275,5.012061,0.313798
308,24,MD,Maryland,2016,7.0,36.0,6003323,1.166021,5.996679,0.547013
309,24,MD,Maryland,2017,8.0,47.0,6023868,1.328050,7.802296,0.623029
310,24,MD,Maryland,2018,9.0,76.0,6035802,1.491103,12.591533,0.699439
311,24,MD,Maryland,2019,16.0,67.0,6045680,2.646518,11.082293,1.241994
312,24,MD,Maryland,2020,6.0,54.0,6173689,0.971866,8.746796,0.465292
313,24,MD,Maryland,2021,21.0,67.0,6175045,3.400785,10.850123,1.629866
314,24,MD,Maryland,2022,22.0,69.0,6163981,3.569122,11.194064,1.710876

In [17]:
#Anaplasmosis 

#5. Subset MD dataframe to extract incidence rates only from 2015-2022 (to somewhat match harvest data timeline which goes up to 2025)

#2015 begins at row 307

df_pana_updated = df_pana_updated.drop(df_pana_updated.loc[:306].index)  
#https://stackoverflow.com/questions/15703283/pandas-drop-a-range-of-rows-from-df

In [18]:
df_pana_updated

,STATEFP,STUSPS,NAME,YEAR,CASES_A,CASES_EC,POP,RATE_A,RATE_EC,ONE_MILLION_RATE
307,24,MD,Maryland,2015,4.0,30.0,5985562,0.668275,5.012061,0.313798
308,24,MD,Maryland,2016,7.0,36.0,6003323,1.166021,5.996679,0.547013
309,24,MD,Maryland,2017,8.0,47.0,6023868,1.328050,7.802296,0.623029
310,24,MD,Maryland,2018,9.0,76.0,6035802,1.491103,12.591533,0.699439
311,24,MD,Maryland,2019,16.0,67.0,6045680,2.646518,11.082293,1.241994
312,24,MD,Maryland,2020,6.0,54.0,6173689,0.971866,8.746796,0.465292
313,24,MD,Maryland,2021,21.0,67.0,6175045,3.400785,10.850123,1.629866
314,24,MD,Maryland,2022,22.0,69.0,6163981,3.569122,11.194064,1.710876

In [19]:
#Anaplasmosis 

#6. Drop columns that don't need to be in chart

df_pana_updated = df_pana_updated.drop(["STATEFP", "STUSPS", "NAME", "CASES_A", "CASES_EC", "RATE_A",
"POP", "RATE_EC"], axis = 1)

In [20]:
#Anaplasmosis

#7. Reset Index
df_pana_updated = df_pana_updated.reset_index(drop=True)

In [21]:
#Anaplasmosis

#8. Add disease column for grouped bar chart 
df_pana_updated=df_pana_updated.assign(TICKBORNE_DISEASE = "Anaplasmosis")
#https://stackoverflow.com/questions/44657226/how-to-insert-a-new-column-with-repeated-values-into-a-pandas-table

In [22]:
#Anaplasmosis

#9. Save to CSV 
df_pana_updated.to_csv("df_pana_updated.csv", index = False)

In [23]:
#Ehrlichiosis
import pandas as pd
#1. Read CSV
df_pehr = pd.read_csv("df_pehr.csv")
df_pehr

,STATEFP,STUSPS,NAME,YEAR,CASES_A,CASES_EC,POP,RATE_A,RATE_EC
0,1,AL,Alabama,2008,NaN,9.0,4718206,NaN,1.907505
1,1,AL,Alabama,2009,2.0,8.0,4757938,0.420350,1.681401
2,1,AL,Alabama,2010,7.0,12.0,4785437,1.462771,2.507608
3,1,AL,Alabama,2011,4.0,5.0,4799069,0.833495,1.041869
4,1,AL,Alabama,2012,11.0,10.0,4815588,2.284249,2.076590
...,...,...,...,...,...,...,...,...,...
760,56,WY,Wyoming,2018,0.0,0.0,577601,0.000000,0.000000
761,56,WY,Wyoming,2019,0.0,1.0,578759,0.000000,1.727835
762,56,WY,Wyoming,2020,0.0,1.0,577664,0.000000,1.731110
763,56,WY,Wyoming,2021,0.0,0.0,579548,0.000000,0.000000
764,56,WY,Wyoming,2022,0.0,1.0,581629,0.000000,1.719309

In [24]:
#Ehrlichiosis
#2. Change incidence rate so that all tickborne diseases are per 1000000 people 

df_pehr['ONE_MILLION_RATE'] = (df_pehr["CASES_EC"] / df_pehr["POP"]) * 1000000

In [25]:
#Ehrlichiosis

#3. Drop "RATE" column from original table and create new dataframe 

df_pehr_updated = df_pehr.drop(["RATE_EC"], axis = 1)

In [26]:
#Ehrlichiosis

#4. Subset update dataframe to locate only Maryland's incidence rates and create new datframe just for MD

df_pehr_updated=df_pehr_updated[df_pehr_updated['NAME'] == 'Maryland']

In [27]:
df_pehr_updated

,STATEFP,STUSPS,NAME,YEAR,CASES_A,CASES_EC,POP,RATE_A,ONE_MILLION_RATE
300,24,MD,Maryland,2008,4.0,61.0,5684965,0.703610,10.730057
301,24,MD,Maryland,2009,1.0,33.0,5730388,0.174508,5.758772
302,24,MD,Maryland,2010,15.0,22.0,5788645,2.591280,3.800544
303,24,MD,Maryland,2011,7.0,33.0,5839419,1.198749,5.651247
304,24,MD,Maryland,2012,5.0,37.0,5886992,0.849330,6.285043
305,24,MD,Maryland,2013,5.0,31.0,5923188,0.844140,5.233668
306,24,MD,Maryland,2014,2.0,38.0,5957283,0.335724,6.378747
307,24,MD,Maryland,2015,4.0,30.0,5985562,0.668275,5.012061
308,24,MD,Maryland,2016,7.0,36.0,6003323,1.166021,5.996679
309,24,MD,Maryland,2017,8.0,47.0,6023868,1.328050,7.802296
310,24,MD,Maryland,2018,9.0,76.0,6035802,1.491103,12.591533
311,24,MD,Maryland,2019,16.0,67.0,6045680,2.646518,11.082293
312,24,MD,Maryland,2020,6.0,54.0,6173689,0.971866,8.746796
313,24,MD,Maryland,2021,21.0,67.0,6175045,3.400785,10.850123
314,24,MD,Maryland,2022,22.0,69.0,6163981,3.569122,11.194064

In [28]:
#Ehrlichiosis

#5. Subset MD dataframe to extract incidence rates only from 2015-2022 (to somewhat match harvest data timeline which goes up to 2025)


#2015 begins at row 307

df_pehr_updated = df_pehr_updated.drop(df_pehr_updated.loc[:306].index)  
#https://stackoverflow.com/questions/15703283/pandas-drop-a-range-of-rows-from-df

In [29]:
df_pehr_updated

,STATEFP,STUSPS,NAME,YEAR,CASES_A,CASES_EC,POP,RATE_A,ONE_MILLION_RATE
307,24,MD,Maryland,2015,4.0,30.0,5985562,0.668275,5.012061
308,24,MD,Maryland,2016,7.0,36.0,6003323,1.166021,5.996679
309,24,MD,Maryland,2017,8.0,47.0,6023868,1.328050,7.802296
310,24,MD,Maryland,2018,9.0,76.0,6035802,1.491103,12.591533
311,24,MD,Maryland,2019,16.0,67.0,6045680,2.646518,11.082293
312,24,MD,Maryland,2020,6.0,54.0,6173689,0.971866,8.746796
313,24,MD,Maryland,2021,21.0,67.0,6175045,3.400785,10.850123
314,24,MD,Maryland,2022,22.0,69.0,6163981,3.569122,11.194064

In [30]:
#Ehrlichiosis

#6. Drop columns that don't need to be in chart

df_pehr_updated = df_pehr_updated.drop(["STATEFP", "STUSPS", "NAME", "CASES_A", "CASES_EC", "POP", "RATE_A"], axis = 1)

In [31]:
df_pehr_updated

     YEAR  ONE_MILLION_RATE
307  2015          5.012061
308  2016          5.996679
309  2017          7.802296
310  2018         12.591533
311  2019         11.082293
312  2020          8.746796
313  2021         10.850123
314  2022         11.194064

In [32]:
#Ehrlichiosis

#7. Reset Index
df_pehr_updated = df_pehr_updated.reset_index(drop=True)

In [33]:
#Ehrlichiosis

#8. Add disease column for grouped bar chart 
df_pehr_updated=df_pehr_updated.assign(TICKBORNE_DISEASE = "Ehrlichiosis")
#https://stackoverflow.com/questions/44657226/how-to-insert-a-new-column-with-repeated-values-into-a-pandas-table

In [34]:
#ehrlichiosis

#9. Save to CSV 
df_pehr_updated.to_csv("df_pehr_updated.csv", index = False)

In [35]:
#Babesiosis 

#1. Read CSV 
df_pbabesiosis = pd.read_csv("df_pbabesiosis.csv")
df_pbabesiosis

     STATEFP STUSPS     NAME  YEAR  CASES      POP      RATE
0          1     AL  Alabama  2011    1.0  4799069  0.020837
1          1     AL  Alabama  2012    0.0  4815588  0.000000
2          1     AL  Alabama  2013    0.0  4830081  0.000000
3          1     AL  Alabama  2014    1.0  4841799  0.020653
4          1     AL  Alabama  2015    2.0  4852347  0.041217
..       ...    ...      ...   ...    ...      ...       ...
607       56     WY  Wyoming  2018    0.0   577601  0.000000
608       56     WY  Wyoming  2019    0.0   578759  0.000000
609       56     WY  Wyoming  2020    1.0   577664  0.173111
610       56     WY  Wyoming  2021    0.0   579548  0.000000
611       56     WY  Wyoming  2022    2.0   581629  0.343862

[612 rows x 7 columns]

In [36]:
#Babesiosis 

#2. Change incidence rate so that all tickborne diseases are per 1000000 people 
df_pbabesiosis['ONE_MILLION_RATE'] = (df_pbabesiosis["CASES"] / df_pbabesiosis["POP"]) * 1000000

In [37]:
#Babesiosis 

#3. Drop "RATE" column from original table and create new dataframe 

df_pbabesiosis_updated = df_pbabesiosis.drop(["RATE"], axis = 1)

In [38]:
#Babesiosis 

#4. Subset update dataframe to locate only Maryland's incidence rates and create new datframe just for MD

df_pbabesiosis_updated = df_pbabesiosis[df_pbabesiosis['NAME'] == 'Maryland']

In [39]:
df_pbabesiosis_updated

,STATEFP,STUSPS,NAME,YEAR,CASES,POP,RATE,ONE_MILLION_RATE
240,24,MD,Maryland,2011,4.0,5839419,0.068500,0.685000
241,24,MD,Maryland,2012,3.0,5886992,0.050960,0.509598
242,24,MD,Maryland,2013,9.0,5923188,0.151945,1.519452
243,24,MD,Maryland,2014,2.0,5957283,0.033572,0.335724
244,24,MD,Maryland,2015,4.0,5985562,0.066827,0.668275
245,24,MD,Maryland,2016,6.0,6003323,0.099945,0.999446
246,24,MD,Maryland,2017,5.0,6023868,0.083003,0.830031
247,24,MD,Maryland,2018,7.0,6035802,0.115975,1.159746
248,24,MD,Maryland,2019,7.0,6045680,0.115785,1.157852
249,24,MD,Maryland,2020,9.0,6173689,0.145780,1.457799
250,24,MD,Maryland,2021,13.0,6175045,0.210525,2.105248
251,24,MD,Maryland,2022,7.0,6163981,0.113563,1.135630

In [40]:
#Babesiosis 

#5. Subset MD dataframe to extract incidence rates only from 2015-2022 (to somewhat match harvest data timeline which goes up to 2025)

#2015 begins at row 244 

df_pbabesiosis_updated = df_pbabesiosis_updated.drop(df_pbabesiosis_updated.loc[:243].index)  
#https://stackoverflow.com/questions/15703283/pandas-drop-a-range-of-rows-from-df

In [41]:
#Babesiosis

#6. Drop columns that don't need to be in chart

df_pbabesiosis_updated = df_pbabesiosis_updated.drop(["STATEFP", "STUSPS", "NAME", "CASES", 
"POP", "RATE"], axis = 1)

In [42]:
#Babesiosis
#7. Reset Index
df_pbabesiosis_updated=df_pbabesiosis_updated.reset_index(drop=True)

In [43]:
#Ehrlichiosis

#8. Add disease column for grouped bar chart 
df_pbabesiosis_updated=df_pbabesiosis_updated.assign(TICKBORNE_DISEASE = "Babesiosis")
#https://stackoverflow.com/questions/44657226/how-to-insert-a-new-column-with-repeated-values-into-a-pandas-table

In [44]:
#Babesiosis
#9. SAVE TO CSV 

df_pbabesiosis_updated.to_csv("df_pbabesiosis_updated.csv", index=False)

In [45]:
#LYME DISEASE CALCUALTED IN THIS NOTEBOOK: Lyme_Disease_Incidence_Clean

In [46]:
%run Lyme_Disease_Incidence_Clean.ipynb

In [47]:
df_plyme_updated
df_pehr_updated
df_pbabesiosis_updated
df_pana_updated
df_pana_updated

   YEAR  ONE_MILLION_RATE TICKBORNE_DISEASE
0  2015          0.313798      Anaplasmosis
1  2016          0.547013      Anaplasmosis
2  2017          0.623029      Anaplasmosis
3  2018          0.699439      Anaplasmosis
4  2019          1.241994      Anaplasmosis
5  2020          0.465292      Anaplasmosis
6  2021          1.629866      Anaplasmosis
7  2022          1.710876      Anaplasmosis

In [48]:
df_md_tickborne_incidence = pd.concat(
    [df_plyme_updated,
     df_pehr_updated,
     df_pbabesiosis_updated,
     df_pana_updated,
     df_psfr_updated]
)

In [49]:
df_md_tickborne_incidence.to_csv("df_md_tickborne_incidence.csv")

In [50]:
df_md_tickborne_incidence

   ONE_MILLION_RATE            TICKBORNE_DISEASE  YEAR
0        288.694696                         Lyme  2015
1        310.827853                         Lyme  2016
2        313.419882                         Lyme  2017
3        228.967087                         Lyme  2018
4        234.382237                         Lyme  2019
5        136.061276                         Lyme  2020
6        147.043463                         Lyme  2021
7        317.976321                         Lyme  2022
0          5.012061                 Ehrlichiosis  2015
1          5.996679                 Ehrlichiosis  2016
2          7.802296                 Ehrlichiosis  2017
3         12.591533                 Ehrlichiosis  2018
4         11.082293                 Ehrlichiosis  2019
5          8.746796                 Ehrlichiosis  2020
6         10.850123                 Ehrlichiosis  2021
7         11.194064                 Ehrlichiosis  2022
0          0.668275                   Babesiosis  2015
1          0.999446                   Babesiosis  2016
2          0.830031                   Babesiosis  2017
3          1.159746                   Babesiosis  2018
4          1.157852                   Babesiosis  2019
5          1.457799                   Babesiosis  2020
6          2.105248                   Babesiosis  2021
7          1.135630                   Babesiosis  2022
0          0.313798                 Anaplasmosis  2015
1          0.547013                 Anaplasmosis  2016
2          0.623029                 Anaplasmosis  2017
3          0.699439                 Anaplasmosis  2018
4          1.241994                 Anaplasmosis  2019
5          0.465292                 Anaplasmosis  2020
6          1.629866                 Anaplasmosis  2021
7          1.710876                 Anaplasmosis  2022
0          0.668275  Spotted Fever Rickettsiosis  2015
1          0.166574  Spotted Fever Rickettsiosis  2016
2         10.126384  Spotted Fever Rickettsiosis  2017
3         17.561875  Spotted Fever Rickettsiosis  2018
4         22.660809  Spotted Fever Rickettsiosis  2019
5          3.239554  Spotted Fever Rickettsiosis  2020
6          2.267190  Spotted Fever Rickettsiosis  2021
7          2.595725  Spotted Fever Rickettsiosis  2022

In [51]:
df_md_tickborne_incidence.columns

Index(['ONE_MILLION_RATE', 'TICKBORNE_DISEASE', 'YEAR'], dtype='str')

In [52]:
#https://pandas.pydata.org/docs/user_guide/reshaping.html
df_md_tickborne_incidence=df_md_tickborne_incidence.pivot(index ='YEAR', 
                                                          columns = 'TICKBORNE_DISEASE', 
                                                          values = 'ONE_MILLION_RATE')
print(df_md_tickborne_incidence)

TICKBORNE_DISEASE  Anaplasmosis  Babesiosis  Ehrlichiosis        Lyme  \
YEAR
2015                   0.313798    0.668275      5.012061  288.694696
2016                   0.547013    0.999446      5.996679  310.827853
2017                   0.623029    0.830031      7.802296  313.419882
2018                   0.699439    1.159746     12.591533  228.967087
2019                   1.241994    1.157852     11.082293  234.382237
2020                   0.465292    1.457799      8.746796  136.061276
2021                   1.629866    2.105248     10.850123  147.043463
2022                   1.710876    1.135630     11.194064  317.976321

TICKBORNE_DISEASE  Spotted Fever Rickettsiosis
YEAR
2015                                  0.668275
2016                                  0.166574
2017                                 10.126384
2018                                 17.561875
2019                                 22.660809
2020                                  3.239554
2021                                  2.267190
2022                                  2.595725

In [53]:
df_md_tickborne_incidence.to_csv("df_md_tickborne_incidence.csv")